import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {ROLES,CAPS,WEIGHTS,questionsFor} from '../lib/assessment.js';import{aggregate,routing}from'../lib/scoring.js';
function render(record){const elements=new Map();const element=()=>({value:'',innerHTML:'',classList:{add(){},remove(){}}});const doc={querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll:()=>[]};const context=vm.createContext({document:doc,Date,URLSearchParams,fetch(){throw new Error('Unexpected network');}});const source=fs.readFileSync(new URL('../admin.js',import.meta.url),'utf8').replace(/auth\(\)\.catch\([^\n]+\);/,'');vm.runInContext(source,context);context.fixture=record;context.cfg={roles:ROLES,caps:CAPS,weights:WEIGHTS};vm.runInContext('config=cfg;current=fixture;renderAssessment(fixture.record)',context);return elements.get('#detailContent').innerHTML;}
test('admin renders a replacement baseline without original pre-test and keeps legacy scores identifiable',()=>{
 const qs=questionsFor('comparison'),answers=Object.fromEntries(qs.map(q=>[q.id,'Verifikasi, langkah spesifik dan bukti.'])),grades=qs.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,confidence:.9})),flags:[]})),result=aggregate('comparison',answers,grades);
 const record={token:'test',preferences:[],stages:{comparison:{status:'submitted',answers,grades,result,grading:{status:'complete'},scoreHistory:[{at:0,reason:'fixture',previousResult:{roleFits:result.roleFits.map(x=>({...x,score:40}))}}]}},notes:''};
 const html=render({record,primaryAssessment:{source:'comparison',label:'Pendalaman pembanding',result},routing:routing(result),materials:{selected:[],released:false},roleResults:[]});assert.match(html,/Dasar hasil: Pendalaman pembanding/);assert.match(html,/10 soal/);assert.match(html,/Skor lama/);assert.match(html,/jawaban kosong dihitung 0/);assert.match(html,/Kecukupan bukti/);assert.doesNotMatch(html,/Soal yang tidak dijawab bernilai 0/);
});

test('admin shows leadership score separately from the universal baseline',async()=>{const {aggregateLeadership,LEADERSHIP}=await import('../lib/leadership.js');const answers=Object.fromEntries(LEADERSHIP.map(q=>[q.id,'Langkah spesifik.'])),grades=LEADERSHIP.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,confidence:.9})),flags:[]}));const record={token:'test',preferences:[],stages:{leadership:{status:'submitted',answers,grades,result:aggregateLeadership(answers,grades),grading:{status:'complete'}}},notes:''};const html=render({record,primaryAssessment:{source:'pre',label:'Pre-test diagnostik'},materials:{selected:[],released:false},roleResults:[]});assert.match(html,/Assessment Leader PW/);assert.match(html,/Skor kepemimpinan: 75/);assert.match(html,/4 soal/);assert.match(html,/Terpisah dari skor delapan posisi/);});

test('admin filters combine team and stage completion without treating automatic partial submits as complete',()=>{
 const elements=new Map(),doc={querySelector:s=>{if(!elements.has(s))elements.set(s,{value:'',checked:false,innerHTML:'',textContent:''});return elements.get(s)},querySelectorAll:()=>[]};
 const context=vm.createContext({document:doc,Date,URLSearchParams,fetch(){throw new Error('Filter must not call network');}});
 const source=fs.readFileSync(new URL('../admin.js',import.meta.url),'utf8').replace(/auth\(\)\.catch\([^\n]+\);/,'');vm.runInContext(source,context);
 const fixtures=[{token:'full',candidateName:'Full',currentTeam:'Marketing',shortlist:[],preferences:['cc-creative'],profileStatus:'saved',stages:{pre:{status:'terminated',answeredCount:32,grading:'complete'},comparison:{status:'submitted',answeredCount:10,grading:'complete',comparable:true}}},{token:'partial',candidateName:'Partial',currentTeam:'Marketing',shortlist:[],preferences:[],stages:{pre:{status:'terminated',answeredCount:16,grading:'complete'},comparison:{status:'active'}}},{token:'pending',candidateName:'Pending',currentTeam:'Design',shortlist:[],preferences:[],leaderTrack:true,stages:{comparison:{status:'submitted',answeredCount:10,grading:'pending'}}},{token:'new',candidateName:'New',shortlist:[],preferences:[],stages:{}}];
 context.fixtures=fixtures;context.cfg={roles:ROLES};vm.runInContext('records=fixtures;config=cfg;renderFilterOptions()',context);
 const check=(filters,expected)=>{for(const id of ['filterTeam','filterPre','filterComparison','filterLeadership','filterProfile','filterTrack','filterRole','filterReview'])doc.querySelector('#'+id).value=filters[id]||'';assert.deepEqual(Array.from(vm.runInContext('records.filter(matchesAdminFilters).map(r=>r.token)',context)),expected);};
 check({filterTeam:'Marketing',filterComparison:'complete'},['full']);check({filterPre:'partial'},['partial']);check({filterPre:'complete'},['full']);check({filterComparison:'pending_ai',filterTrack:'leader'},['pending']);check({filterComparison:'not_started'},['new']);check({filterProfile:'saved',filterRole:'cc-creative'},['full']);check({filterTeam:'__none__'},['new']);check({filterComparison:'active'},['partial']);
 check({},fixtures.map(r=>r.token));vm.runInContext('renderList()',context);assert.match(doc.querySelector('#filterCount').textContent,/Menampilkan 4 sesi/);assert.deepEqual(fixtures[1].stages.pre,{status:'terminated',answeredCount:16,grading:'complete'});
});
