import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {ROLES,CAPS,WEIGHTS,questionsFor} from '../lib/assessment.js';import{aggregate,routing}from'../lib/scoring.js';
function render(record){const elements=new Map();const element=()=>({value:'',innerHTML:'',classList:{add(){},remove(){}}});const doc={querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll:()=>[]};const context=vm.createContext({document:doc,Date,URLSearchParams,fetch(){throw new Error('Unexpected network');}});const source=fs.readFileSync(new URL('../admin.js',import.meta.url),'utf8').replace(/auth\(\)\.catch\([^\n]+\);/,'');vm.runInContext(source,context);context.fixture=record;context.cfg={roles:ROLES,caps:CAPS,weights:WEIGHTS};vm.runInContext('config=cfg;current=fixture;renderAssessment(fixture.record)',context);return elements.get('#detailContent').innerHTML;}
test('admin renders a replacement baseline without original pre-test and keeps legacy scores identifiable',()=>{
 const qs=questionsFor('comparison'),answers=Object.fromEntries(qs.map(q=>[q.id,'Verifikasi, langkah spesifik dan bukti.'])),grades=qs.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,confidence:.9})),flags:[]})),result=aggregate('comparison',answers,grades);
 const record={token:'test',preferences:[],stages:{comparison:{status:'submitted',answers,grades,result,grading:{status:'complete'},scoreHistory:[{at:0,reason:'fixture',previousResult:{roleFits:result.roleFits.map(x=>({...x,score:40}))}}]}},notes:''};
 const html=render({record,primaryAssessment:{source:'comparison',label:'Pendalaman pembanding',result},routing:routing(result),materials:{selected:[],released:false},roleResults:[]});assert.match(html,/Dasar hasil: Pendalaman pembanding/);assert.match(html,/10 soal/);assert.match(html,/Skor lama/);assert.match(html,/jawaban kosong dihitung 0/);assert.match(html,/Kecukupan bukti/);assert.doesNotMatch(html,/Soal yang tidak dijawab bernilai 0/);
});

test('admin shows leadership score separately from the universal baseline',async()=>{const {aggregateLeadership,LEADERSHIP}=await import('../lib/leadership.js');const answers=Object.fromEntries(LEADERSHIP.map(q=>[q.id,'Langkah spesifik.'])),grades=LEADERSHIP.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,confidence:.9})),flags:[]}));const record={token:'test',preferences:[],stages:{leadership:{status:'submitted',answers,grades,result:aggregateLeadership(answers,grades),grading:{status:'complete'}}},notes:''};const html=render({record,primaryAssessment:{source:'pre',label:'Pre-test diagnostik'},materials:{selected:[],released:false},roleResults:[]});assert.match(html,/Assessment Leader PW/);assert.match(html,/Skor kepemimpinan: 75/);assert.match(html,/4 soal/);assert.match(html,/Terpisah dari skor delapan posisi/);});
