// These workflow fixtures exercise the period before the separately tested cutoff.
const originalNow=Date.now;Date.now=()=>Date.parse('2026-10-02T06:00:00Z');
import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/index.js';import {reset} from './memory-blob.js';import {mutate,write} from '../lib/storage.js';import {PRE,questionsFor} from '../lib/assessment.js';
process.env.ADMIN_PASSWORD='test-only-password';process.env.ADMIN_SECRET='test-only-random-secret-for-cookie';
let cookie='';async function req(action,data,params={},auth=true){const headers={host:'localhost:3000',...(auth&&cookie?{cookie}:{})};const request={url:'/api/index?'+new URLSearchParams({action,...params}),method:data?'POST':'GET',headers,body:data};const response={code:200,headers:{},status(c){this.code=c;return this;},setHeader(k,v){this.headers[k]=v;},json(value){this.value=value;return this;},send(value){this.value=value;return this;}};await handler(request,response);return response;}
const answers=stage=>Object.fromEntries(questionsFor(stage).map(q=>[q.id,q.type==='sjt'?0:'Verifikasi fakta dan risiko, tentukan owner serta tenggat, siapkan alternatif dan catat bukti tindak lanjut.']));
test('post timer is nine server minutes per module and locks saved answers exactly at expiry',async()=>{
 reset();const fixedNow=Date.now;let now=fixedNow();Date.now=()=>now;
 try{
  const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];
  await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:false,selfServeMaterials:false});
  const token=(await req('admin-invite',{candidateName:'QA nine-minute post'})).value.token;
  await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre={status:'submitted',securityEvents:[],grading:{status:'complete'},result:{complete:true,capability:[],roleFits:[{roleKey:'cc-creative',score:50},{roleKey:'pw-curator',score:50}]}};r.materialSelection={roles:['cc-creative','pw-curator'],releasedAt:now};r.materialRead={'cc-creative':now,'pw-curator':now};r.postTestAccess={enabled:true};});
  const stage='post:cc-creative',start=await req('start',{token,stage});assert.equal(start.code,200);assert.equal(start.value.expiresAt-start.value.serverNow,540000);
  now+=539999;const first=questionsFor(stage)[0].id;
  assert.equal((await req('save',{token,stage,answers:{[first]:0},revision:1})).code,200);
  assert.equal((await req('quiz',null,{token,stage})).value.expiresAt,start.value.expiresAt);
  assert.equal((await req('violation',{token,stage,type:'time_expired',answers:{[first]:1}})).code,409);
  now++;assert.equal((await req('save',{token,stage,answers:{[first]:1},revision:2})).code,409);
  assert.equal((await req('quiz',null,{token,stage})).code,409);
  assert.equal((await req('violation',{token,stage,type:'time_expired',answers:{[first]:1}})).code,200);
  const s=(await req('admin-submissions',null,{id:token})).value.record.stages[stage];assert.deepEqual(s.answers,{[first]:0});assert.equal(s.status,'terminated');assert.equal(s.terminationReason,'time_expired');assert.equal(s.submittedAt,start.value.expiresAt);
  const second=await req('start',{token,stage:'post:pw-curator'});assert.equal(second.code,200);assert.equal(second.value.expiresAt-now,540000);
 }finally{Date.now=fixedNow;}
});
function mockAI(){globalThis.fetch=async(url,opt)=>{const input=JSON.parse(JSON.parse(opt.body).input);return new Response(JSON.stringify({status:'completed',model:'mock-for-tests',usage:{total_tokens:1},output:[{content:[{type:'output_text',text:JSON.stringify({grades:input.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,evidence:q.answer,confidence:.9,fulfilled:['Langkah tindak lanjut'],missing:['Rincian pemeriksaan'],rationale:'Langkah dapat dijalankan, pemeriksaan belum lengkap.'})),flags:[]}))})}]}]}),{status:200});};}
test('kode tetap sampai post, pre 15 menit, materi admin, profil non-scoring dan practical eksternal',async()=>{reset();const realFetch=globalThis.fetch;try{assert.equal((await req('admin-invite',{candidateName:'Uji'}, {},false)).code,401);const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];assert.equal(login.code,200);await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:false});const inv=await req('admin-invite',{candidateName:'QA kandidat',currentTeam:'Tim QA',expiresHours:24});const token=inv.value.token;assert.ok(token);assert.match(inv.value.accessCode,/^[1-9]\d{5}$/);assert.equal((await req('resolve-code',{code:inv.value.accessCode},{},false)).value.token,token);assert.equal((await req('invite',null,{token})).value.duration,15);assert.equal((await req('invite',null,{token})).code,200);
 const start={token,stage:'pre',identity:{name:'QA kandidat',contact:'qa@example.invalid'},preferences:['pw-workplace']};const starts=await Promise.all([req('start',start),req('start',start)]);assert.deepEqual(starts.map(r=>r.code).sort(),[200,409]);
 const q=await req('quiz',null,{token,stage:'pre'});assert.equal(q.value.questions.length,32);assert.deepEqual(q.value.questions,starts.find(r=>r.code===200).value.questions);assert.deepEqual((await req('quiz',null,{token,stage:'pre'})).value.questions,q.value.questions);assert.ok(!JSON.stringify(q.value).includes('signals'));const expires=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(expires.expiresAt-expires.startedAt,900000);
 assert.equal((await req('materials',null,{token,role:'pw-workplace'})).code,403);
 const pre=answers('pre');assert.equal((await req('save',{token,stage:'pre',answers:pre,revision:1})).code,200);assert.equal((await req('submit',{token,stage:'pre',answers:pre})).code,200);
 assert.equal((await req('evaluate',{token,stage:'pre'})).code,503);assert.equal((await req('invite',null,{token})).value.shortlist.length,0);
 assert.equal((await req('profile',{token,profile:{english:'',mbti:'ISTP',hobbies:'musik',zodiac:'Libra'}})).code,200);
 assert.equal((await req('admin-ai',{apiKey:'sk-test-key-not-real',model:'gpt-4o-mini'})).code,200);mockAI();assert.equal((await req('evaluate',{token,stage:'pre'})).code,200);const status=(await req('invite',null,{token})).value;assert.equal(status.shortlist.length,2);assert.ok(!JSON.stringify(status).includes('roleFits'));const role=status.shortlist[0].roleKey;
 const before=(await req('admin-submissions',null,{id:token})).value.record.stages.pre.result;await req('profile',{token,profile:{english:'Fluent',mbti:'ENFP',zodiac:'Aries'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before);
 assert.equal((await req('start',{token,stage:'post:'+role})).code,409);assert.equal((await req('materials',null,{token,role})).code,403);
 assert.equal((await req('admin-materials',{token,roles:[role]}, {},false)).code,401);
 const plan=await req('admin-submissions',null,{id:token});assert.ok(plan.value.materials.suggested.includes('pw-workplace'));assert.equal(plan.value.materials.released,false);
 assert.equal((await req('admin-post-access',{token,enabled:true})).code,409);
 const released=await req('admin-materials',{token,roles:[role]});assert.equal(released.code,200);assert.ok(released.value.qr.includes('<svg'));assert.ok(released.value.url.includes('code='+inv.value.accessCode));assert.equal((await req('materials',null,{token,role})).code,200);assert.equal((await req('materials-read',{token,role})).code,200);
 assert.equal((await req('start',{token,stage:'practical:'+role})).code,409);
 assert.equal((await req('invite',null,{token})).value.postTestEnabled,false);assert.equal((await req('start',{token,stage:'post:'+role})).code,409);assert.equal((await req('admin-post-access',{token,enabled:true},{},false)).code,401);assert.equal((await req('admin-post-access',{token,enabled:true})).code,200);assert.equal((await req('invite',null,{token})).value.postTestEnabled,true);assert.equal((await req('admin-post-access',{token,enabled:false})).code,200);assert.equal((await req('start',{token,stage:'post:'+role})).code,409);await req('admin-post-access',{token,enabled:true});
 const stage='post:'+role;assert.equal((await req('start',{token,stage})).code,200);assert.equal((await req('admin-post-access',{token,enabled:false})).code,409);assert.equal((await req('quiz',null,{token,stage})).value.expiresAt-Date.now(),540000);assert.equal((await req('save',{token,stage,answers:answers(stage),revision:1})).code,200);assert.equal((await req('submit',{token,stage,answers:answers(stage)})).code,200);assert.equal((await req('evaluate',{token,stage})).code,200);
 assert.equal((await req('resolve-code',{code:inv.value.accessCode},{},false)).value.token,token);
 const detail=(await req('admin-submissions',null,{id:token})).value;assert.notEqual(detail.roleResults[0].post,null);assert.equal(detail.roleResults[0].practicalStatus,'external');assert.equal(detail.record.profile.english,'Fluent');const scoreBeforeNotes=detail.record.stages.pre.result;await req('admin-notes',{token,notes:'Observasi tambahan',checklist:{creative:'yes',risk:'mid'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,scoreBeforeNotes);assert.equal((await req('admin-bank',null,{stage:'pre'},false)).code,401);assert.equal((await req('start',start)).code,409);
 }finally{globalThis.fetch=realFetch;}});
test('security warnings preserve the active attempt and answers until participant confirms',async()=>{const inv=await req('admin-invite',{candidateName:'QA warning'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA warning',contact:'qa@example.invalid'},preferences:['cc-creative']});const initial=(await req('quiz',null,{token,stage:'pre'})).value;const warning={token,stage:'pre',answers:{pre01:1},revision:2,eventId:'warning-one',type:'fullscreen_exit'};assert.equal((await req('security-warning',warning)).code,200);assert.equal((await req('security-warning',warning)).code,200);await req('security-warning',{...warning,answers:{pre01:0},revision:1});let q=(await req('quiz',null,{token,stage:'pre'})).value;assert.equal(q.warning.id,'warning-one');assert.equal((await req('submit',{token,stage:'pre',answers:answers('pre')})).code,409);assert.deepEqual(q.answers,{pre01:1});assert.equal(q.expiresAt,initial.expiresAt);let s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.equal(s.securityEvents.length,1);assert.equal(s.reviewRequired,true);assert.equal((await req('security-resume',{token,stage:'pre',eventId:'warning-one'})).code,200);q=(await req('quiz',null,{token,stage:'pre'})).value;assert.equal(q.warning,null);assert.deepEqual(q.answers,{pre01:1});assert.equal(q.expiresAt,initial.expiresAt);s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.ok(s.securityEvents[0].confirmedAt);await req('violation',{token,stage:'pre',answers:{pre01:0},type:'tab_or_app_switch'});s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.deepEqual(s.answers,{pre01:1});q=(await req('quiz',null,{token,stage:'pre'})).value;await req('security-resume',{token,stage:'pre',eventId:q.warning.id});assert.equal((await req('submit',{token,stage:'pre',answers:answers('pre')})).code,200);s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'submitted');assert.equal(s.reviewRequired,true);});

test('server deadline freezes saved evidence and stale autosaves cannot replace newer evidence',async()=>{const inv=await req('admin-invite',{candidateName:'QA expiry'});const token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA expiry',contact:'qa@example.invalid'},preferences:['cc-strategist']});await req('save',{token,stage:'pre',answers:{pre01:2},revision:2});await req('save',{token,stage:'pre',answers:{pre01:0},revision:1});await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.expiresAt=Date.now()-5000;});assert.equal((await req('save',{token,stage:'pre',answers:{pre01:1},revision:3})).code,410);assert.equal((await req('security-resume',{token,stage:'pre'})).code,410);await req('submit',{token,stage:'pre',answers:answers('pre')});const r=(await req('admin-submissions',null,{id:token})).value.record;assert.equal(r.stages.pre.status,'terminated');assert.equal(r.stages.pre.terminationReason,'time_expired');assert.deepEqual(r.stages.pre.answers,{pre01:2});assert.equal((await req('invite',null,{token})).value.shortlist.length,2);});


test('admin can choose applied or additional roles beyond automatic top two; PDF matches selection',async()=>{const realFetch=globalThis.fetch;try{mockAI();const inv=await req('admin-invite',{candidateName:'QA manual materials',currentTeam:'Tim lama'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA manual materials',contact:'qa@example.invalid'},preferences:['cc-creative']});await req('submit',{token,stage:'pre',answers:answers('pre')});await req('evaluate',{token,stage:'pre'});const d=(await req('admin-submissions',null,{id:token})).value;assert.ok(d.materials.selected.includes('cc-creative'));assert.equal(d.materials.released,false);const before=d.record.stages.pre.result;await req('admin-materials',{token,roles:['cc-creative']});const pdf=await req('material-pdf',null,{code:inv.value.accessCode},false);assert.equal(pdf.code,200);assert.equal(pdf.headers['Content-Type'],'application/pdf');assert.equal(pdf.value.subarray(0,4).toString(),'%PDF');const {PDFDocument}=await import('pdf-lib');assert.equal((await PDFDocument.load(pdf.value)).getPageCount(),2);assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before);assert.equal((await req('materials',null,{token,role:'pw-curator'})).code,403);await req('materials-read',{token,role:'cc-creative'});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,409);await req('admin-post-access',{token,enabled:true});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,200);assert.equal((await req('admin-materials',{token,roles:['pw-curator']})).code,409);assert.equal((await req('admin-materials',{token,roles:[]})).code,400);}finally{globalThis.fetch=realFetch;}});

test('six digit codes are unique, invalid codes are rejected and repeated guesses are limited',async()=>{const codes=[];for(let i=0;i<4;i++){const x=await req('admin-invite',{candidateName:'QA codes '+i});assert.equal(x.code,200);assert.match(x.value.accessCode,/^[1-9]\d{5}$/);codes.push(x.value.accessCode);}assert.equal(new Set(codes).size,codes.length);assert.equal((await req('resolve-code',{code:'123'}, {},false)).code,400);const {read}=await import('../lib/storage.js');let unknown=100000;while(await read('access/v2-codes/'+unknown+'.json'))unknown++;for(let i=0;i<20;i++)assert.equal((await req('resolve-code',{code:String(unknown)}, {},false)).code,404);assert.equal((await req('resolve-code',{code:String(unknown)}, {},false)).code,429);});


test('unanswered security warning locks partial answers after ten seconds, including reload and late confirmation',async()=>{const inv=await req('admin-invite',{candidateName:'QA warning expiry'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA warning expiry',contact:'qa@example.invalid'},preferences:['cc-creative']});const w=await req('security-warning',{token,stage:'pre',answers:{pre01:2},revision:1,eventId:'expires-warning',type:'tab_or_app_switch'});assert.equal(w.code,200);const d=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(w.value.deadlineAt-d.securityEvents[0].at,10000);assert.equal((await req('security-resume',{token,stage:'pre',eventId:'wrong'})).code,409);const duplicate=await req('security-warning',{token,stage:'pre',answers:{pre01:0},revision:2,eventId:'different-id',type:'page_exit'});assert.equal(duplicate.value.deadlineAt,w.value.deadlineAt);assert.equal(duplicate.value.eventId,'expires-warning');await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.securityEvents[0].deadlineAt=Date.now()-1;});assert.equal((await req('security-resume',{token,stage:'pre',eventId:'expires-warning'})).code,410);assert.equal((await req('save',{token,stage:'pre',answers:{pre01:0},revision:3})).code,409);assert.equal((await req('security-timeout',{token,stage:'pre'})).code,200);const r=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(r.status,'submitted');assert.equal(r.autoSubmitReason,'security_confirmation_timeout');assert.deepEqual(r.answers,{pre01:2});assert.equal(r.reviewRequired,true);assert.ok(r.securityEvents[0].timedOutAt);assert.equal((await req('quiz',null,{token,stage:'pre'})).code,409);assert.equal((await req('invite',null,{token})).value.stages.pre.autoSubmitReason,'security_confirmation_timeout');});


test('admin deletion checks exact identity, removes participant codes and preserves other candidates',async()=>{reset();const inv=(await req('admin-invite',{candidateName:'QA deletion'})).value,keep=(await req('admin-invite',{candidateName:'Candidate preserved'})).value;const payload={token:inv.token,expectedName:inv.candidateName};assert.equal((await req('admin-delete-candidate',payload,{},false)).code,401);assert.equal((await req('admin-delete-candidate',{...payload,expectedName:'Wrong name'})).code,409);assert.equal((await req('resolve-code',{code:inv.accessCode},{},false)).code,200);assert.equal((await req('admin-delete-candidate',payload)).code,200);assert.equal((await req('admin-delete-candidate',payload)).code,200);assert.equal((await req('invite',null,{token:inv.token})).code,404);assert.equal((await req('resolve-code',{code:inv.accessCode},{},false)).code,404);assert.equal((await req('invite',null,{token:keep.token})).code,200);const list=(await req('admin-submissions')).value;assert.equal(list.records.some(r=>r.token===inv.token),false);assert.equal(list.records.some(r=>r.token===keep.token),true);const {write}=await import('../lib/storage.js');await write('submissions/legacy-deletion-fixture.json',{submissionId:'qa-delete-legacy',candidateName:'QA legacy deletion'});const legacy={submissionId:'qa-delete-legacy',expectedName:'QA legacy deletion'};assert.equal((await req('admin-delete-candidate',{...legacy,expectedName:'Wrong name'})).code,409);assert.equal((await req('admin-delete-candidate',legacy)).code,200);assert.equal((await req('admin-submissions')).value.legacy.some(r=>r.submissionId===legacy.submissionId),false);});

test('a client clock cannot terminate a test before its server deadline',async()=>{const inv=(await req('admin-invite',{candidateName:'QA clock'})).value,token=inv.token;const start=await req('start',{token,stage:'pre',identity:{name:'QA clock',contact:'qa-clock@example.invalid'},preferences:['cc-creative']});assert.ok(start.value.serverNow<start.value.expiresAt);await req('save',{token,stage:'pre',answers:{pre01:2},revision:1});assert.equal((await req('violation',{token,stage:'pre',answers:{pre01:2},type:'time_expired'})).code,409);const s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.deepEqual(s.answers,{pre01:2});assert.equal((await req('admin-recover-premature',{token,expectedName:inv.candidateName})).code,409);});
test('provably premature termination is recovered with answers and starts remaining time only on resume',async()=>{const inv=(await req('admin-invite',{candidateName:'QA recovery'})).value,token=inv.token;await req('start',{token,stage:'pre',identity:{name:'QA recovery',contact:'qa@example.invalid'},preferences:['cc-creative']});await mutate('assessments/v2/'+token+'.json',r=>{const s=r.stages.pre;s.answers={pre01:1};s.status='terminated';s.terminationReason='time_expired';s.submittedAt=s.startedAt+500;s.result={complete:true};});const payload={token,expectedName:inv.candidateName};assert.equal((await req('admin-recover-premature',payload,{},false)).code,401);assert.equal((await req('admin-recover-premature',payload)).code,200);const q=(await req('quiz',null,{token,stage:'pre'})).value;assert.equal(q.recoverable,true);assert.equal(q.expiresAt,null);assert.deepEqual(q.answers,{pre01:1});assert.equal((await req('start',{token,stage:'pre'})).code,409);const resumed=await req('resume-recovered',{token,stage:'pre'});assert.equal(resumed.code,200);assert.ok(resumed.value.expiresAt-resumed.value.serverNow>899000);assert.deepEqual(resumed.value.answers,{pre01:1});const s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.recoveryHistory[0].previous.status,'terminated');assert.equal(s.result,undefined);});

test('expired pre-test still permits untimed non-scoring profile, partial grading and material QR while post-test stays manual',async()=>{await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:false});const realFetch=globalThis.fetch;try{await req('admin-ai',{apiKey:'sk-test-key-not-real',model:'gpt-4o-mini'});mockAI();const inv=(await req('admin-invite',{candidateName:'QA partial expiry'})).value,token=inv.token;await req('start',{token,stage:'pre',identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['cc-creative']});await req('save',{token,stage:'pre',answers:{pre01:1,pre25:'Verifikasi kebutuhan, tentukan owner dan tenggat lalu dokumentasikan hasil.'},revision:1});await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.expiresAt=Date.now()-5000;});await req('violation',{token,stage:'pre',answers:{},type:'time_expired'});assert.equal((await req('profile',{token,profile:{interests:'Menulis',talents:'Desain'}})).code,200);assert.equal((await req('evaluate',{token,stage:'pre'})).code,200);const before=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(before.status,'terminated');assert.equal(before.result.answeredCount,2);assert.equal(before.result.totalQuestions,32);assert.equal(before.result.complete,true);assert.equal((await req('invite',null,{token})).value.shortlist.length,2);const release=await req('admin-materials',{token,roles:['cc-creative']});assert.equal(release.code,200);assert.match(release.value.qr,/<svg/);assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,200);await req('materials-read',{token,role:'cc-creative'});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,409);await req('profile',{token,profile:{interests:'Musik'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before.result);await req('admin-post-access',{token,enabled:true});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,200);}finally{globalThis.fetch=realFetch;}});

test('scoring revision archives old scores once, preserves answers and holds materials until common comparison is complete',async()=>{
 const realFetch=globalThis.fetch;try{
 await req('admin-operations',{postTestsLocked:false,materialsHeld:true,comparisonEnabled:true});mockAI();
 const inv=(await req('admin-invite',{candidateName:'QA scoring revision'})).value,token=inv.token;
 await req('start',{token,stage:'pre',identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['cc-creative']});const a=answers('pre');await req('submit',{token,stage:'pre',answers:a});await req('evaluate',{token,stage:'pre'});
 await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.result.scoringVersion='legacy';r.materialSelection={roles:['cc-strategist'],releasedAt:Date.now()};});
 const before=(await req('admin-submissions',null,{id:token})).value.record;
 assert.equal((await req('admin-recalculate',{token},{},false)).code,401);
 assert.equal((await req('admin-recalculate',{token})).code,200);assert.equal((await req('admin-recalculate',{token})).code,200);
 let d=(await req('admin-submissions',null,{id:token})).value;
 assert.deepEqual(d.record.stages.pre.answers,a);assert.equal(d.record.stages.pre.scoreHistory.length,1);assert.deepEqual(d.record.stages.pre.scoreHistory[0].previousResult,before.stages.pre.result);assert.equal(d.record.materialSelectionHistory.length,1);assert.equal(d.download,null);
 assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,423);
 assert.equal((await req('start',{token,stage:'comparison'})).code,400);
 const first=await req('start',{token,stage:'comparison',consent:true});assert.equal(first.code,200);assert.equal(first.value.expiresAt,null);assert.deepEqual(first.value.questions.map(q=>q.id),questionsFor('comparison').map(q=>q.id));await req('admin-operations',{postTestsLocked:false,materialsHeld:true,comparisonEnabled:false});assert.equal((await req('quiz',null,{token,stage:'comparison'})).code,200);await req('admin-operations',{postTestsLocked:false,materialsHeld:true,comparisonEnabled:true});
 assert.equal((await req('admin-materials',{token,roles:['cc-creative']})).code,409);
 const followup=answers('comparison');await req('save',{token,stage:'comparison',answers:followup,revision:1});await req('submit',{token,stage:'comparison',answers:followup});await req('evaluate',{token,stage:'comparison'});
 d=(await req('admin-submissions',null,{id:token})).value;assert.equal(d.primaryAssessment.source,'comparison');assert.equal(d.primaryAssessment.result.answeredCount,10);assert.deepEqual(d.record.stages.pre.answers,a);
 await req('admin-materials',{token,roles:['cc-creative']});assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,423);
 await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true});assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,200);
 assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,409);
 assert.equal((await req('admin-comparison-reset',{token,reason:'Test'})).code,409);
 }finally{globalThis.fetch=realFetch;}
});
test('a participant who never started the timed pre-test can use the replacement common baseline with the same code',async()=>{
 const realFetch=globalThis.fetch;try{mockAI();await req('admin-operations',{postTestsLocked:false,materialsHeld:true,comparisonEnabled:true});const inv=(await req('admin-invite',{candidateName:'QA replacement baseline'})).value,token=inv.token;
 const payload={token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['pw-curator']};const start=await req('start',payload);assert.equal(start.code,200);assert.equal(start.value.expiresAt,null);await req('submit',{token,stage:'comparison',answers:answers('comparison')});await req('evaluate',{token,stage:'comparison'});const d=(await req('admin-submissions',null,{id:token})).value;assert.equal(d.primaryAssessment.source,'comparison');assert.equal(d.record.stages.pre,undefined);assert.equal((await req('profile',{token,profile:{english:'optional'}})).code,200);assert.equal((await req('admin-materials',{token,roles:['pw-curator']})).code,200);
 }finally{globalThis.fetch=realFetch;}
});

test('admin visibility is reversible, admin-only and preserves candidate access and assessment data',async()=>{
 reset();const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];
 const invite=await req('admin-invite',{candidateName:'Visibility fixture',currentTeam:'QA',expiresHours:24});const token=invite.value.token;
 const before=(await req('admin-submissions',null,{id:token})).value.record;
 assert.equal((await req('admin-visibility',{token,hidden:true},{},false)).code,401);
 assert.equal((await req('admin-visibility',{token,hidden:'true'})).code,400);
 assert.equal((await req('admin-visibility',{token,hidden:true})).code,200);
 assert.equal((await req('admin-submissions')).value.records.find(r=>r.token===token).hidden,true);
 const after=(await req('admin-submissions',null,{id:token})).value.record;delete after.adminVisibility;assert.deepEqual(after,before);
 assert.equal((await req('resolve-code',{code:invite.value.accessCode},{},false)).value.token,token);
 assert.equal((await req('admin-visibility',{token,hidden:false})).code,200);
 assert.equal((await req('admin-submissions')).value.records.find(r=>r.token===token).hidden,false);
});

test('self-service requires complete graded comparison, returns only role scores and serves selected PDF while post stays manual',async()=>{
 reset();const realFetch=globalThis.fetch;process.env.OPENAI_API_KEY='test-only-key';try{const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true});mockAI();
 const inv=(await req('admin-invite',{candidateName:'Self-service fixture'})).value,token=inv.token;
 assert.equal((await req('candidate-materials',{token,roles:['cc-creative']})).code,409);assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,403);
 await req('start',{token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['cc-creative']});
 const submitted=await req('submit',{token,stage:'comparison',answers:answers('comparison')});assert.equal(submitted.code,200);assert.equal(submitted.value.summary.stages.comparison.grading,'complete');
 const state=(await req('invite',null,{token},false)).value;assert.equal(state.roleSelection.choices.length,8);assert.equal(state.roleSelection.choices.filter(x=>x.recommended).length,2);assert.ok(state.roleSelection.choices.find(x=>x.roleKey==='cc-creative').selected);assert.equal(state.download,null);for(const field of ['capability','criteria','evidence','grades','scoreHistory','finalScore'])assert.ok(!JSON.stringify(state).includes('"'+field+'"'));
 assert.equal((await req('candidate-materials',{token,roles:[]})).code,400);assert.equal((await req('candidate-materials',{token,roles:['cc-creative','cc-creative']})).code,400);
 const selection=await req('candidate-materials',{token,roles:['cc-creative','pw-workplace']});assert.equal(selection.code,200);assert.match(selection.value.qr,/<svg/);const pdf=await req('material-pdf',null,{code:inv.accessCode},false);assert.equal(pdf.code,200);assert.equal(pdf.value.subarray(0,4).toString(),'%PDF');
 const next=(await req('invite',null,{token})).value;assert.deepEqual(next.materialRoles.map(x=>x.roleKey),['cc-creative','pw-workplace']);assert.ok(next.download);assert.equal(next.postTestEnabled,false);await req('materials-read',{token,role:'cc-creative'});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,409);
 await req('admin-operations',{postTestsLocked:false,materialsHeld:true,comparisonEnabled:true,selfServeMaterials:true});assert.equal((await req('candidate-materials',{token,roles:['cc-creative']})).code,423);assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,423);
 }finally{globalThis.fetch=realFetch;delete process.env.OPENAI_API_KEY;}
});

test('an interrupted self-service comparison resumes unanswered cases with archived results and immutable prior answers',async()=>{
 reset();const realFetch=globalThis.fetch;process.env.OPENAI_API_KEY='test-only-key';try{const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true});mockAI();const inv=(await req('admin-invite',{candidateName:'Resume fixture'})).value,token=inv.token;await req('start',{token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['pw-curator']});
 const first={cmp01:'Periksa fakta dan urgensi. Catat penanggung jawab serta tenggat.'};await req('security-warning',{token,stage:'comparison',answers:first,revision:1,eventId:'warning-fixture',type:'tab_or_app_switch'});await mutate('assessments/v2/'+token+'.json',r=>{r.stages.comparison.securityEvents[0].deadlineAt=Date.now()-1;});let state=(await req('invite',null,{token})).value;assert.equal(state.stages.comparison.status,'submitted');assert.equal(state.roleSelection,null);assert.equal((await req('comparison-resume',{token})).code,200);const q=(await req('quiz',null,{token,stage:'comparison'})).value;assert.deepEqual(q.answers,first);assert.deepEqual(q.lockedAnswers,['cmp01']);assert.equal(q.expiresAt,null);assert.equal((await req('security-resume',{token,stage:'comparison'})).code,200);const recovered=(await req('admin-submissions',null,{id:token})).value.record.stages.comparison;assert.equal(recovered.autoSubmitReason,undefined);assert.equal(recovered.submittedAt,undefined);assert.equal(recovered.resumeHistory[0].previous.autoSubmitReason,'security_confirmation_timeout');
 assert.equal((await req('save',{token,stage:'comparison',answers:{cmp01:'Rewritten'},revision:2})).code,409);const complete={...answers('comparison'),...first};assert.equal((await req('submit',{token,stage:'comparison',answers:complete})).code,200);const d=(await req('admin-submissions',null,{id:token})).value;assert.equal(d.record.stages.comparison.result.comparable,true);assert.equal(d.record.stages.comparison.resumeHistory.length,1);assert.equal(d.record.stages.comparison.resumeHistory[0].previous.answers.cmp01,first.cmp01);assert.equal(d.record.stages.comparison.securityEvents.length,1);assert.equal((await req('comparison-resume',{token})).code,409);
 }finally{globalThis.fetch=realFetch;delete process.env.OPENAI_API_KEY;}
});

test('automatic AI failure preserves all submitted answers and permits retry without retaking comparison',async()=>{
 reset();const realFetch=globalThis.fetch;try{const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true});const inv=(await req('admin-invite',{candidateName:'AI retry fixture'})).value,token=inv.token;await req('start',{token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['cc-strategist']});process.env.OPENAI_API_KEY='test-only-key';globalThis.fetch=async()=>new Response(JSON.stringify({error:'fixture'}),{status:503});const a=answers('comparison');assert.equal((await req('submit',{token,stage:'comparison',answers:a})).code,200);let d=(await req('admin-submissions',null,{id:token})).value;assert.deepEqual(d.record.stages.comparison.answers,a);assert.equal(d.record.stages.comparison.grading.status,'failed');assert.equal((await req('invite',null,{token})).value.roleSelection,null);mockAI();assert.equal((await req('evaluate',{token,stage:'comparison'})).code,200);assert.equal((await req('invite',null,{token})).value.roleSelection.choices.length,8);
 }finally{globalThis.fetch=realFetch;delete process.env.OPENAI_API_KEY;}
});

test('leader applicant flag is admin-only, reversible and preserves candidate evidence',async()=>{const inv=(await req('admin-invite',{candidateName:'QA leader flag'})).value,token=inv.token;await mutate('assessments/v2/'+token+'.json',r=>{r.preferences=['pw-curator'];r.stages.pre={status:'submitted',answers:{pre01:2}};r.profile={interests:'Coaching'};});const before=(await req('admin-submissions',null,{id:token})).value.record;assert.equal((await req('admin-leader-track',{token,enabled:true},{},false)).code,401);assert.equal((await req('admin-leader-track',{token,enabled:'true'})).code,400);assert.equal((await req('admin-leader-track',{token,enabled:true})).code,200);assert.equal((await req('admin-submissions')).value.records.find(r=>r.token===token).leaderTrack,true);const after=(await req('admin-submissions',null,{id:token})).value.record;const{leaderTrack,...unchanged}=after;assert.deepEqual(unchanged,before);assert.equal(leaderTrack.enabled,true);assert.equal((await req('admin-leader-track',{token,enabled:false})).code,200);assert.equal((await req('admin-submissions')).value.records.find(r=>r.token===token).leaderTrack,false);});

test('leader module gates materials, resumes only missing answers, grades automatically and preserves the common baseline',async()=>{const realFetch=globalThis.fetch;try{
 await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true});mockAI();await req('admin-ai',{apiKey:'sk-test-key-not-real',model:'gpt-4o-mini'});
 const inv=(await req('admin-invite',{candidateName:'QA leader module'})).value,token=inv.token;
 assert.equal((await req('start',{token,stage:'leadership',consent:true})).code,403);
 await req('admin-leader-track',{token,enabled:true});assert.equal((await req('start',{token,stage:'leadership',consent:true})).code,409);
 await req('start',{token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['pw-curator']});await req('submit',{token,stage:'comparison',answers:answers('comparison')});
 const baseline=structuredClone((await req('admin-submissions',null,{id:token})).value.record.stages.comparison);
 let state=(await req('invite',null,{token})).value;assert.equal(state.leaderTrack,true);assert.equal(state.leadershipReady,false);assert.equal(state.roleSelection,null);assert.equal(state.download,null);
 assert.equal((await req('candidate-materials',{token,roles:['pw-curator']})).code,409);assert.equal((await req('admin-materials',{token,roles:['pw-curator']})).code,409);
 assert.equal((await req('start',{token,stage:'leadership'})).code,400);const started=await req('start',{token,stage:'leadership',consent:true});assert.equal(started.value.expiresAt,null);assert.equal(started.value.questions.length,4);assert.deepEqual(started.value.questions.map(q=>q.id),questionsFor('leadership').map(q=>q.id));assert.ok(!JSON.stringify(started.value).includes('criteria'));
 const first={ldr01:'Tentukan owner, pendampingan dan tenggat; verifikasi jumlah barang dan laporan progres.'};await req('security-warning',{token,stage:'leadership',answers:first,revision:1,eventId:'leader-security',type:'tab_or_app_switch'});
 await mutate('assessments/v2/'+token+'.json',r=>{r.stages.leadership.securityEvents[0].deadlineAt=Date.now()-1;});state=(await req('invite',null,{token})).value;assert.equal(state.stages.leadership.status,'submitted');assert.equal(state.leadershipReady,false);
 await req('evaluate',{token,stage:'leadership'});const partial=(await req('admin-submissions',null,{id:token})).value.record.stages.leadership.result;assert.equal(partial.leadershipScore,null);assert.equal(partial.observedScore,75);assert.equal(partial.answeredCount,1);
 assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,403);await req('leadership-resume',{token});const q=(await req('quiz',null,{token,stage:'leadership'})).value;assert.deepEqual(q.lockedAnswers,['ldr01']);assert.deepEqual(q.answers,first);assert.equal((await req('security-resume',{token,stage:'leadership'})).code,200);assert.equal((await req('admin-submissions',null,{id:token})).value.record.stages.leadership.autoSubmitReason,undefined);
 assert.equal((await req('save',{token,stage:'leadership',answers:{ldr01:'Ubah jawaban'},revision:2})).code,409);
 const full={...answers('leadership'),...first};assert.equal((await req('submit',{token,stage:'leadership',answers:full})).code,200);
 state=(await req('invite',null,{token})).value;assert.equal(state.leadershipReady,true);assert.equal(state.stages.leadership.grading,'complete');assert.equal(state.roleSelection.choices.length,8);for(const field of ['leadershipScore','observedScore','grades','capability','criteria'])assert.ok(!JSON.stringify(state).includes('"'+field+'"'));
 const detail=(await req('admin-submissions',null,{id:token})).value;assert.equal(detail.record.stages.leadership.result.leadershipScore,75);assert.deepEqual(detail.record.stages.comparison,baseline);assert.equal(detail.primaryAssessment.source,'comparison');assert.equal(detail.record.stages.leadership.resumeHistory.length,1);
 assert.equal((await req('candidate-materials',{token,roles:['pw-curator']})).code,200);assert.equal((await req('material-pdf',null,{code:inv.accessCode},false)).code,200);assert.equal((await req('leadership-resume',{token})).code,409);
 }finally{globalThis.fetch=realFetch;}});

test('leader AI failure preserves committed answers and supports grading retry without a retest',async()=>{const realFetch=globalThis.fetch;try{await req('admin-operations',{postTestsLocked:false,materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true});mockAI();const inv=(await req('admin-invite',{candidateName:'QA leader AI retry'})).value,token=inv.token;await req('admin-leader-track',{token,enabled:true});await req('start',{token,stage:'comparison',consent:true,identity:{name:inv.candidateName,contact:'qa@example.invalid'},preferences:['pw-workplace']});await req('submit',{token,stage:'comparison',answers:answers('comparison')});await req('start',{token,stage:'leadership',consent:true});globalThis.fetch=async()=>new Response(JSON.stringify({error:'fixture'}),{status:503});const full=answers('leadership');assert.equal((await req('submit',{token,stage:'leadership',answers:full})).code,200);let detail=(await req('admin-submissions',null,{id:token})).value.record;assert.deepEqual(detail.stages.leadership.answers,full);assert.equal(detail.stages.leadership.grading.status,'failed');assert.equal((await req('invite',null,{token})).value.roleSelection,null);mockAI();assert.equal((await req('evaluate',{token,stage:'leadership'})).code,200);assert.equal((await req('invite',null,{token})).value.leadershipReady,true);assert.equal((await req('start',{token,stage:'leadership',consent:true})).code,409);}finally{globalThis.fetch=realFetch;}});

test('global post-test lock blocks direct APIs even for an existing active post session',async()=>{await req('admin-operations',{materialsHeld:false,comparisonEnabled:true,selfServeMaterials:true,postTestsLocked:true});const inv=(await req('admin-invite',{candidateName:'QA global post lock'})).value,token=inv.token;await mutate('assessments/v2/'+token+'.json',r=>{r.postTestAccess={enabled:true};r.stages['post:pw-curator']={status:'active',answers:{},revision:0,expiresAt:null,securityEvents:[]};});assert.equal((await req('invite',null,{token})).value.postTestEnabled,false);for(const action of ['start','save','submit','evaluate','security-warning'])assert.equal((await req(action,{token,stage:'post:pw-curator',answers:{},revision:1})).code,409,action);assert.equal((await req('quiz',null,{token,stage:'post:pw-curator'})).code,409);assert.equal((await req('admin-grade',{token,stage:'post:pw-curator'})).code,409);assert.equal((await req('admin-post-access',{token,enabled:true})).code,409);assert.equal((await req('admin-operations',{materialsHeld:false,comparisonEnabled:true,postTestsLocked:'no'})).code,400);});

test('started comparison code remains usable after invitation expiry; unused expired code stays closed',async()=>{const started=(await req('admin-invite',{candidateName:'QA started expiry'})).value,unused=(await req('admin-invite',{candidateName:'QA unused expiry'})).value;await mutate('assessments/v2/'+started.token+'.json',r=>{r.expiresAt=Date.now()-1;r.stages.comparison={status:'active',answers:{},expiresAt:null,securityEvents:[]};});await mutate('assessments/v2/'+unused.token+'.json',r=>{r.expiresAt=Date.now()-1;});assert.equal((await req('resolve-code',{code:started.accessCode},{},false)).code,200);assert.equal((await req('resolve-code',{code:unused.accessCode},{},false)).code,410);});

 test('already recovered active stages ignore historical timeout metadata but enforce a new warning deadline',async()=>{
 reset();const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];await req('admin-operations',{comparisonEnabled:true,selfServeMaterials:true,postTestsLocked:true});
 for(const stage of ['comparison','leadership']){
 const inv=(await req('admin-invite',{candidateName:'Legacy recovery fixture'})).value,token=inv.token;
 await mutate('assessments/v2/'+token+'.json',r=>{r.stages[stage]={status:'active',expiresAt:null,answers:{},revision:0,securityEvents:[{id:'old-warning',kind:'warning',deadlineAt:Date.now()-20000,confirmedAt:Date.now()-10000,timedOutAt:Date.now()-20000}],autoSubmitReason:'security_confirmation_timeout',submittedAt:Date.now()-20000,resumedAt:Date.now()-10000};});
 assert.equal((await req('security-resume',{token,stage})).code,200);
 assert.equal((await req('security-warning',{token,stage,answers:{},revision:1,eventId:'new-warning'})).code,200);
 await mutate('assessments/v2/'+token+'.json',r=>{r.stages[stage].securityEvents.at(-1).deadlineAt=Date.now()-1;});
 assert.equal((await req('security-resume',{token,stage,eventId:'new-warning'})).code,410);
 const closed=(await req('admin-submissions',null,{id:token})).value.record.stages[stage];assert.equal(closed.status,'submitted');assert.equal(closed.securityEvents.length,2);assert.ok(closed.securityEvents[1].timedOutAt);
 }
 });

test.after(()=>{Date.now=originalNow;});
