import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/index.js';import {reset} from './memory-blob.js';import {mutate} from '../lib/storage.js';import {PRE,questionsFor} from '../lib/assessment.js';
process.env.ADMIN_PASSWORD='test-only-password';process.env.ADMIN_SECRET='test-only-random-secret-for-cookie';
let cookie='';async function req(action,data,params={},auth=true){const headers={host:'localhost:3000',...(auth&&cookie?{cookie}:{})};const request={url:'/api/index?'+new URLSearchParams({action,...params}),method:data?'POST':'GET',headers,body:data};const response={code:200,headers:{},status(c){this.code=c;return this;},setHeader(k,v){this.headers[k]=v;},json(value){this.value=value;return this;},send(value){this.value=value;return this;}};await handler(request,response);return response;}
const answers=stage=>Object.fromEntries(questionsFor(stage).map(q=>[q.id,q.type==='sjt'?0:'Verifikasi fakta dan risiko, tentukan owner serta tenggat, siapkan alternatif dan catat bukti tindak lanjut.']));
function mockAI(){globalThis.fetch=async(url,opt)=>{const input=JSON.parse(JSON.parse(opt.body).input);return new Response(JSON.stringify({status:'completed',model:'mock-for-tests',usage:{total_tokens:1},output:[{content:[{type:'output_text',text:JSON.stringify({grades:input.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,evidence:q.answer,confidence:.9})),flags:[]}))})}]}]}),{status:200});};}
test('kode tetap sampai post, pre 15 menit, materi admin, profil non-scoring dan practical eksternal',async()=>{reset();const realFetch=globalThis.fetch;try{assert.equal((await req('admin-invite',{candidateName:'Uji'}, {},false)).code,401);const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];assert.equal(login.code,200);const inv=await req('admin-invite',{candidateName:'QA kandidat',currentTeam:'Tim QA',expiresHours:24});const token=inv.value.token;assert.ok(token);assert.match(inv.value.accessCode,/^[1-9]\d{5}$/);assert.equal((await req('resolve-code',{code:inv.value.accessCode},{},false)).value.token,token);assert.equal((await req('invite',null,{token})).value.duration,15);assert.equal((await req('invite',null,{token})).code,200);
 const start={token,stage:'pre',identity:{name:'QA kandidat',contact:'qa@example.invalid'},preferences:['pw-workplace']};const starts=await Promise.all([req('start',start),req('start',start)]);assert.deepEqual(starts.map(r=>r.code).sort(),[200,409]);
 const q=await req('quiz',null,{token,stage:'pre'});assert.equal(q.value.questions.length,32);assert.deepEqual(q.value.questions,starts.find(r=>r.code===200).value.questions);assert.deepEqual((await req('quiz',null,{token,stage:'pre'})).value.questions,q.value.questions);assert.ok(!JSON.stringify(q.value).includes('signals'));const expires=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(expires.expiresAt-expires.startedAt,900000);
 assert.equal((await req('materials',null,{token,role:'pw-workplace'})).code,403);
 const pre=answers('pre');assert.equal((await req('save',{token,stage:'pre',answers:pre,revision:1})).code,200);assert.equal((await req('submit',{token,stage:'pre',answers:pre})).code,200);
 assert.equal((await req('evaluate',{token,stage:'pre'})).code,503);assert.equal((await req('invite',null,{token})).value.shortlist.length,0);
 assert.equal((await req('profile',{token,profile:{english:'',mbti:'ISTP',hobbies:'musik',zodiac:'Libra'}})).code,200);
 assert.equal((await req('admin-ai',{apiKey:'sk-test-key-not-real',model:'gpt-4o-mini'})).code,200);mockAI();assert.equal((await req('evaluate',{token,stage:'pre'})).code,200);const status=(await req('invite',null,{token})).value;assert.equal(status.shortlist.length,2);assert.ok(!JSON.stringify(status).includes('roleFits'));const role=status.shortlist[0].roleKey;
 const before=(await req('admin-submissions',null,{id:token})).value.record.stages.pre.result;await req('profile',{token,profile:{english:'Fluent',mbti:'ENFP',zodiac:'Aries'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before);
 assert.equal((await req('start',{token,stage:'post:'+role})).code,409);assert.equal((await req('materials',null,{token,role})).code,403);
 assert.equal((await req('admin-materials',{token,roles:[role]}, {},false)).code,401);
 const plan=await req('admin-submissions',null,{id:token});assert.ok(plan.value.materials.suggested.includes('pw-workplace'));assert.equal(plan.value.materials.released,false);
 const released=await req('admin-materials',{token,roles:[role]});assert.equal(released.code,200);assert.ok(released.value.qr.includes('<svg'));assert.ok(released.value.url.includes('code='+inv.value.accessCode));assert.equal((await req('materials',null,{token,role})).code,200);assert.equal((await req('materials-read',{token,role})).code,200);
 assert.equal((await req('start',{token,stage:'practical:'+role})).code,409);
 const stage='post:'+role;assert.equal((await req('start',{token,stage})).code,200);assert.equal((await req('quiz',null,{token,stage})).value.expiresAt,null);assert.equal((await req('save',{token,stage,answers:answers(stage),revision:1})).code,200);assert.equal((await req('submit',{token,stage,answers:answers(stage)})).code,200);assert.equal((await req('evaluate',{token,stage})).code,200);
 assert.equal((await req('resolve-code',{code:inv.value.accessCode},{},false)).value.token,token);
 const detail=(await req('admin-submissions',null,{id:token})).value;assert.notEqual(detail.roleResults[0].post,null);assert.equal(detail.roleResults[0].practicalStatus,'external');assert.equal(detail.record.profile.english,'Fluent');const scoreBeforeNotes=detail.record.stages.pre.result;await req('admin-notes',{token,notes:'Observasi tambahan',checklist:{creative:'yes',risk:'mid'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,scoreBeforeNotes);assert.equal((await req('admin-bank',null,{stage:'pre'},false)).code,401);assert.equal((await req('start',start)).code,409);
 }finally{globalThis.fetch=realFetch;}});
test('security warnings preserve the active attempt and answers until participant confirms',async()=>{const inv=await req('admin-invite',{candidateName:'QA warning'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA warning',contact:'qa@example.invalid'},preferences:['cc-creative']});const initial=(await req('quiz',null,{token,stage:'pre'})).value;const warning={token,stage:'pre',answers:{pre01:1},revision:2,eventId:'warning-one',type:'fullscreen_exit'};assert.equal((await req('security-warning',warning)).code,200);assert.equal((await req('security-warning',warning)).code,200);await req('security-warning',{...warning,answers:{pre01:0},revision:1});let q=(await req('quiz',null,{token,stage:'pre'})).value;assert.equal(q.warning.id,'warning-one');assert.equal((await req('submit',{token,stage:'pre',answers:answers('pre')})).code,409);assert.deepEqual(q.answers,{pre01:1});assert.equal(q.expiresAt,initial.expiresAt);let s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.equal(s.securityEvents.length,1);assert.equal(s.reviewRequired,true);assert.equal((await req('security-resume',{token,stage:'pre',eventId:'warning-one'})).code,200);q=(await req('quiz',null,{token,stage:'pre'})).value;assert.equal(q.warning,null);assert.deepEqual(q.answers,{pre01:1});assert.equal(q.expiresAt,initial.expiresAt);s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.ok(s.securityEvents[0].confirmedAt);await req('violation',{token,stage:'pre',answers:{pre01:0},type:'tab_or_app_switch'});s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'active');assert.deepEqual(s.answers,{pre01:1});q=(await req('quiz',null,{token,stage:'pre'})).value;await req('security-resume',{token,stage:'pre',eventId:q.warning.id});assert.equal((await req('submit',{token,stage:'pre',answers:answers('pre')})).code,200);s=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(s.status,'submitted');assert.equal(s.reviewRequired,true);});

test('server deadline freezes saved evidence and stale autosaves cannot replace newer evidence',async()=>{const inv=await req('admin-invite',{candidateName:'QA expiry'});const token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA expiry',contact:'qa@example.invalid'},preferences:['cc-strategist']});await req('save',{token,stage:'pre',answers:{pre01:2},revision:2});await req('save',{token,stage:'pre',answers:{pre01:0},revision:1});await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.expiresAt=Date.now()-5000;});assert.equal((await req('save',{token,stage:'pre',answers:{pre01:1},revision:3})).code,410);assert.equal((await req('security-resume',{token,stage:'pre'})).code,410);await req('submit',{token,stage:'pre',answers:answers('pre')});const r=(await req('admin-submissions',null,{id:token})).value.record;assert.equal(r.stages.pre.status,'terminated');assert.equal(r.stages.pre.terminationReason,'time_expired');assert.deepEqual(r.stages.pre.answers,{pre01:2});assert.equal((await req('invite',null,{token})).value.shortlist.length,0);});


test('admin can choose applied or additional roles beyond automatic top two; PDF matches selection',async()=>{const realFetch=globalThis.fetch;try{mockAI();const inv=await req('admin-invite',{candidateName:'QA manual materials',currentTeam:'Tim lama'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA manual materials',contact:'qa@example.invalid'},preferences:['cc-creative']});await req('submit',{token,stage:'pre',answers:answers('pre')});await req('evaluate',{token,stage:'pre'});const d=(await req('admin-submissions',null,{id:token})).value;assert.ok(d.materials.selected.includes('cc-creative'));assert.equal(d.materials.released,false);const before=d.record.stages.pre.result;await req('admin-materials',{token,roles:['cc-creative']});const pdf=await req('material-pdf',null,{code:inv.value.accessCode},false);assert.equal(pdf.code,200);assert.equal(pdf.headers['Content-Type'],'application/pdf');assert.equal(pdf.value.subarray(0,4).toString(),'%PDF');const {PDFDocument}=await import('pdf-lib');assert.equal((await PDFDocument.load(pdf.value)).getPageCount(),2);assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before);assert.equal((await req('materials',null,{token,role:'pw-curator'})).code,403);await req('materials-read',{token,role:'cc-creative'});assert.equal((await req('start',{token,stage:'post:cc-creative'})).code,200);assert.equal((await req('admin-materials',{token,roles:['pw-curator']})).code,409);assert.equal((await req('admin-materials',{token,roles:[]})).code,400);}finally{globalThis.fetch=realFetch;}});

test('six digit codes are unique, invalid codes are rejected and repeated guesses are limited',async()=>{const codes=[];for(let i=0;i<4;i++){const x=await req('admin-invite',{candidateName:'QA codes '+i});assert.equal(x.code,200);assert.match(x.value.accessCode,/^[1-9]\d{5}$/);codes.push(x.value.accessCode);}assert.equal(new Set(codes).size,codes.length);assert.equal((await req('resolve-code',{code:'123'}, {},false)).code,400);const {read}=await import('../lib/storage.js');let unknown=100000;while(await read('access/v2-codes/'+unknown+'.json'))unknown++;for(let i=0;i<20;i++)assert.equal((await req('resolve-code',{code:String(unknown)}, {},false)).code,404);assert.equal((await req('resolve-code',{code:String(unknown)}, {},false)).code,429);});


test('unanswered security warning locks partial answers after ten seconds, including reload and late confirmation',async()=>{const inv=await req('admin-invite',{candidateName:'QA warning expiry'}),token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA warning expiry',contact:'qa@example.invalid'},preferences:['cc-creative']});const w=await req('security-warning',{token,stage:'pre',answers:{pre01:2},revision:1,eventId:'expires-warning',type:'tab_or_app_switch'});assert.equal(w.code,200);const d=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(w.value.deadlineAt-d.securityEvents[0].at,10000);assert.equal((await req('security-resume',{token,stage:'pre',eventId:'wrong'})).code,409);const duplicate=await req('security-warning',{token,stage:'pre',answers:{pre01:0},revision:2,eventId:'different-id',type:'page_exit'});assert.equal(duplicate.value.deadlineAt,w.value.deadlineAt);assert.equal(duplicate.value.eventId,'expires-warning');await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.securityEvents[0].deadlineAt=Date.now()-1;});assert.equal((await req('security-resume',{token,stage:'pre',eventId:'expires-warning'})).code,410);assert.equal((await req('save',{token,stage:'pre',answers:{pre01:0},revision:3})).code,409);assert.equal((await req('security-timeout',{token,stage:'pre'})).code,200);const r=(await req('admin-submissions',null,{id:token})).value.record.stages.pre;assert.equal(r.status,'submitted');assert.equal(r.autoSubmitReason,'security_confirmation_timeout');assert.deepEqual(r.answers,{pre01:2});assert.equal(r.reviewRequired,true);assert.ok(r.securityEvents[0].timedOutAt);assert.equal((await req('quiz',null,{token,stage:'pre'})).code,409);assert.equal((await req('invite',null,{token})).value.stages.pre.autoSubmitReason,'security_confirmation_timeout');});
