import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/index.js';import {reset} from './memory-blob.js';import {mutate} from '../lib/storage.js';import {PRE,questionsFor} from '../lib/assessment.js';
process.env.ADMIN_PASSWORD='test-only-password';process.env.ADMIN_SECRET='test-only-random-secret-for-cookie';
let cookie='';async function req(action,data,params={},auth=true){const headers={host:'localhost:3000',...(auth&&cookie?{cookie}:{})};const request={url:'/api/index?'+new URLSearchParams({action,...params}),method:data?'POST':'GET',headers,body:data};const response={code:200,headers:{},status(c){this.code=c;return this;},setHeader(k,v){this.headers[k]=v;},json(value){this.value=value;return this;}};await handler(request,response);return response;}
const answers=stage=>Object.fromEntries(questionsFor(stage).map(q=>[q.id,q.type==='sjt'?0:'Verifikasi fakta dan risiko, tentukan owner serta tenggat, siapkan alternatif dan catat bukti tindak lanjut.']));
function mockAI(){globalThis.fetch=async(url,opt)=>{const input=JSON.parse(JSON.parse(opt.body).input);return new Response(JSON.stringify({status:'completed',model:'mock-for-tests',usage:{total_tokens:1},output:[{content:[{type:'output_text',text:JSON.stringify({grades:input.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:3,evidence:q.answer,confidence:.9})),flags:[]}))})}]}]}),{status:200});};}
test('aliran lengkap: login, invite, single-attempt, pre, profil non-scoring, materi, post, practical dan hasil',async()=>{reset();const realFetch=globalThis.fetch;try{assert.equal((await req('admin-invite',{candidateName:'Uji'}, {},false)).code,401);const login=await req('admin-login',{password:process.env.ADMIN_PASSWORD});cookie=login.headers['Set-Cookie'].split(';')[0];assert.equal(login.code,200);const inv=await req('admin-invite',{candidateName:'QA kandidat',duration:55,expiresHours:24});const token=inv.value.token;assert.ok(token);assert.equal((await req('invite',null,{token})).code,200);
 const start={token,stage:'pre',identity:{name:'QA kandidat',contact:'qa@example.invalid'},preferences:['pw-workplace']};const starts=await Promise.all([req('start',start),req('start',start)]);assert.deepEqual(starts.map(r=>r.code).sort(),[200,409]);
 const q=await req('quiz',null,{token,stage:'pre'});assert.equal(q.value.questions.length,32);assert.ok(!JSON.stringify(q.value).includes('signals'));
 assert.equal((await req('materials',null,{token,role:'pw-workplace'})).code,403);
 const pre=answers('pre');assert.equal((await req('save',{token,stage:'pre',answers:pre,revision:1})).code,200);assert.equal((await req('submit',{token,stage:'pre',answers:pre})).code,200);
 assert.equal((await req('evaluate',{token,stage:'pre'})).code,503);assert.equal((await req('invite',null,{token})).value.shortlist.length,0);
 assert.equal((await req('profile',{token,profile:{english:'',mbti:'ISTP',hobbies:'musik',zodiac:'Libra'}})).code,200);
 assert.equal((await req('admin-ai',{apiKey:'sk-test-key-not-real',model:'gpt-4o-mini'})).code,200);mockAI();assert.equal((await req('evaluate',{token,stage:'pre'})).code,200);const status=(await req('invite',null,{token})).value;assert.equal(status.shortlist.length,2);assert.ok(!JSON.stringify(status).includes('roleFits'));const role=status.shortlist[0].roleKey;
 const before=(await req('admin-submissions',null,{id:token})).value.record.stages.pre.result;await req('profile',{token,profile:{english:'Fluent',mbti:'ENFP',zodiac:'Aries'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,before);
 assert.equal((await req('start',{token,stage:'post:'+role})).code,409);assert.equal((await req('materials',null,{token,role})).code,200);assert.equal((await req('materials-read',{token,role})).code,200);
 assert.equal((await req('start',{token,stage:'practical:'+role})).code,409);
 for(const kind of ['post','practical']){const stage=kind+':'+role;assert.equal((await req('start',{token,stage})).code,200);assert.equal((await req('submit',{token,stage,answers:answers(stage)})).code,200);assert.equal((await req('evaluate',{token,stage})).code,200);}
 const detail=(await req('admin-submissions',null,{id:token})).value;assert.notEqual(detail.roleResults[0].final,null);assert.equal(detail.record.profile.english,'Fluent');const scoreBeforeNotes=detail.record.stages.pre.result;await req('admin-notes',{token,notes:'Observasi tambahan',checklist:{creative:'yes',risk:'mid'}});assert.deepEqual((await req('admin-submissions',null,{id:token})).value.record.stages.pre.result,scoreBeforeNotes);assert.equal((await req('admin-bank',null,{stage:'pre'},false)).code,401);assert.equal((await req('start',start)).code,409);
 }finally{globalThis.fetch=realFetch;}});
test('termination dan kedaluwarsa tidak membuka pendalaman; data tersimpan dan retry idempotent',async()=>{const inv=await req('admin-invite',{candidateName:'QA termination'});const token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA termination',contact:'qa@example.invalid'},preferences:['cc-creative']});const a={pre01:1};await req('violation',{token,stage:'pre',answers:a,type:'fullscreen_exit'});await req('submit',{token,stage:'pre',answers:answers('pre')});const d=(await req('admin-submissions',null,{id:token})).value.record;assert.equal(d.stages.pre.status,'terminated');assert.equal(d.stages.pre.answers.pre01,1);assert.equal(d.stages.pre.securityEvents.length,1);assert.equal((await req('materials',null,{token,role:'cc-creative'})).code,403);assert.equal((await req('profile',{token,skip:true})).code,409);});

test('server deadline freezes saved evidence and stale autosaves cannot replace newer evidence',async()=>{const inv=await req('admin-invite',{candidateName:'QA expiry'});const token=inv.value.token;await req('start',{token,stage:'pre',identity:{name:'QA expiry',contact:'qa@example.invalid'},preferences:['cc-strategist']});await req('save',{token,stage:'pre',answers:{pre01:2},revision:2});await req('save',{token,stage:'pre',answers:{pre01:0},revision:1});await mutate('assessments/v2/'+token+'.json',r=>{r.stages.pre.expiresAt=Date.now()-5000;});assert.equal((await req('save',{token,stage:'pre',answers:{pre01:1},revision:3})).code,410);await req('submit',{token,stage:'pre',answers:answers('pre')});const r=(await req('admin-submissions',null,{id:token})).value.record;assert.equal(r.stages.pre.status,'terminated');assert.equal(r.stages.pre.terminationReason,'time_expired');assert.deepEqual(r.stages.pre.answers,{pre01:2});assert.equal((await req('invite',null,{token})).value.shortlist.length,0);});
