import test from 'node:test';import assert from 'node:assert/strict';import {recoverPost} from '../lib/post-recovery.js';import handler from '../api/index.js';import {read,write} from '../lib/storage.js';import {reset} from './memory-blob.js';
test('post recovery archives grade, preserves answers/presentation/version and is idempotent without a live timer',()=>{
 const original={status:'terminated',answers:{'cc-executor-post1':0,'cc-executor-post5':'Existing partial essay'},revision:7,presentation:{questions:['cc-executor-post1','cc-executor-post5']},questionBankVersion:'role-advanced-20261008',expiresAt:1,result:{complete:true},grades:[{id:'old'}],securityEvents:[{kind:'warning',confirmedAt:null}]};const r={materialSelection:{roles:['cc-executor']},stages:{'post:cc-executor':structuredClone(original)}};const config={stage:'post:cc-executor',incidentId:'outage-recovery',minutes:5};
 recoverPost(r,config,1000);const s=r.stages[config.stage];assert.deepEqual(s.answers,original.answers);assert.deepEqual(s.presentation,original.presentation);assert.equal(s.revision,7);assert.equal(s.questionBankVersion,original.questionBankVersion);assert.equal(s.expiresAt,null);assert.equal(s.remainingMs,300000);assert.equal(s.status,'paused');assert.deepEqual(s.recoveryHistory[0].previous.result,original.result);assert.equal(recoverPost(r,config,2000).alreadyRecovered,true);assert.equal(s.recoveryHistory.length,1);
});
test('opening recovered quiz does not start clock; continuing starts exactly five minutes and preserves later active modules',async()=>{
 reset();const oldNow=Date.now;let now=Date.parse('2026-10-08T17:00:00+07:00');Date.now=()=>now;process.env.ADMIN_SECRET='qa-recovery-secret';
 const token='recovery_fixture_token_12345',key='assessments/v2/'+token+'.json',result={complete:true,comparable:true,roleFits:[{roleKey:'cc-executor',score:80}]},r={token,candidateName:'QA',preferences:[],postTestAccess:{enabled:true},materialRead:{},materialSelection:{releasedAt:1,roles:['cc-executor','pw-executor']},stages:{comparison:{status:'submitted',result},'post:cc-executor':{status:'terminated',answers:{'cc-executor-post1':0},revision:4,questionBankVersion:'role-advanced-20261008',securityEvents:[]}}};
 recoverPost(r,{stage:'post:cc-executor',incidentId:'outage-qa'});await write(key,r);await write('settings/v3-operations.json',{postTestsLocked:false,materialsHeld:false,selfServeMaterials:false});
 const api=async action=>{const res={code:200,status(n){this.code=n;return this;},setHeader(){},json(v){this.value=v;return this;}};await handler({url:'/api?'+new URLSearchParams({action,token,stage:'post:cc-executor'}),method:action==='quiz'?'GET':'POST',headers:{host:'localhost'},body:{token,stage:'post:cc-executor'}},res);return res;};
 try{assert.equal((await api('quiz')).value.expiresAt,null);const held=(await read(key)).value;held.stages['post:pw-executor']={status:'active',startedAt:now,expiresAt:now+540000,answers:{},securityEvents:[]};await write(key,held);assert.equal((await api('resume-recovered')).code,409);const preserved=(await read(key)).value;assert.equal(preserved.stages['post:pw-executor'].expiresAt,now+540000);assert.equal(preserved.stages['post:cc-executor'].expiresAt,null);preserved.stages['post:pw-executor'].status='submitted';await write(key,preserved);now+=600000;assert.equal((await api('quiz')).value.expiresAt,null);const resumed=await api('resume-recovered');assert.equal(resumed.code,200);assert.equal(resumed.value.expiresAt,now+300000);assert.deepEqual(resumed.value.answers,{'cc-executor-post1':0});assert.equal((await api('resume-recovered')).code,409);assert.equal((await read(key)).value.stages['post:cc-executor'].revision,4);}finally{Date.now=oldNow;}
});
