import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {webcrypto} from 'node:crypto';
function screen(touch=false){let now=100000,deviceNow=100000,fullscreenAttempts=0;const els=new Map(),events={},calls=[],timeouts=[];function el(id){return{id,textContent:'',prepend(x){this.html=(x.html||'')+(this.html||'');},focus(){},remove(){els.delete('#'+this.id);},setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},set innerHTML(v){this.html=v;for(const m of v.matchAll(/id="([^"]+)"/g))els.set('#'+m[1],el(m[1]));}};}for(const id of ['app','timer','submit'])els.set('#'+id,el(id));const doc={querySelector:s=>els.get(s)||null,querySelectorAll:()=>[],addEventListener:(name,fn)=>events[name]=fn,fullscreenElement:null,hidden:false,hasFocus:()=>doc.focused,focused:true,activeElement:null,documentElement:{async requestFullscreen(){fullscreenAttempts++;throw Error('Keyboard/browser fullscreen unsupported');}},body:{append(x){els.set('#'+x.id,x);},classList:{add(){},remove(){}}},createElement:()=>el('')};class Clock extends Date{static now(){return deviceNow;}}const ctx=vm.createContext({document:doc,window:{addEventListener:(name,fn)=>events[name]=fn},location:{search:''},sessionStorage:{getItem:()=>''},URLSearchParams,crypto:webcrypto,structuredClone,Date:Clock,performance:{now:()=>now},setTimeout:fn=>{timeouts.push(fn);return timeouts.length;},clearTimeout(){},setInterval:()=>1,clearInterval(){},navigator:{maxTouchPoints:touch?5:0},Blob,fetch:async(u,opt)=>{const action=new URLSearchParams(u.split('?')[1]).get('action');calls.push({action,data:opt?JSON.parse(opt.body):null});return{ok:true,json:async()=>({ok:true})};}});let source=fs.readFileSync(new URL('../candidate.js',import.meta.url),'utf8');source=source.slice(0,source.lastIndexOf('if(token){loading();'));vm.runInContext(source,ctx);vm.runInContext("syncClock(100000);active=true;stage='pre';quiz={expiresAt:1000000};answers={pre01:1};revision=1;refresh=async()=>{};",ctx);return{ctx,doc,events,els,calls,timeouts,advance:n=>{now+=n;deviceNow+=n;},setDeviceClock:n=>deviceNow=n,fullscreenAttempts:()=>fullscreenAttempts};}
test('iPad keyboard and fullscreen exit allow typing; a hidden page still warns',async()=>{const s=screen(true);await vm.runInContext('fullscreen()',s.ctx);assert.equal(s.fullscreenAttempts(),1);assert.equal(s.events.fullscreenchange,undefined);s.doc.activeElement={matches:()=>true};s.doc.focused=false;s.events.blur();s.timeouts.at(-1)();assert.equal(s.calls.length,0);s.doc.hidden=true;s.events.visibilitychange();assert.equal(s.els.get('#securityWarning').open,true);assert.equal(s.calls[0].action,'security-warning');});
test('confirmation continues the same session without requiring fullscreen',async()=>{const s=screen();s.doc.hidden=true;s.events.visibilitychange();s.doc.hidden=false;await s.els.get('#continueTest').onclick();assert.deepEqual(s.calls.map(x=>x.action),['security-warning','security-resume']);assert.equal(s.fullscreenAttempts(),0);assert.equal(s.els.has('#securityWarning'),false);assert.equal(vm.runInContext('active && !closed && answers.pre01===1 && quiz.expiresAt===1000000',s.ctx),true);});
test('copy paste, clipboard input and new-window shortcuts are prevented',()=>{for(const name of ['copy','paste','beforeinput','keydown']){const s=screen();let prevented=false,stopped=false;const event={key:'t',ctrlKey:true,inputType:'insertFromPaste',preventDefault(){prevented=true;},stopPropagation(){stopped=true;}};s.events[name](event);assert.equal(prevented,true,name);assert.equal(stopped,true,name);assert.equal(s.els.get('#securityWarning').open,true);}});
test('no confirmation within ten seconds auto-submits partial answers without overwriting them',async()=>{const s=screen();s.doc.hidden=true;s.events.visibilitychange();s.advance(10001);await vm.runInContext('warningAutoSubmit()',s.ctx);assert.deepEqual(s.calls.map(x=>x.action),['security-warning','security-timeout','evaluate']);assert.equal(s.calls[0].data.answers.pre01,1);assert.equal(vm.runInContext('closed && !active',s.ctx),true);assert.equal(s.els.has('#securityWarning'),false);});

test('post-test start buttons stay hidden until the admin releases access',()=>{const s=screen();vm.runInContext("state={candidateName:'QA',stages:{pre:{status:'submitted',grading:'complete'}},materialRoles:[{roleKey:'cc-creative',team:'CC',role:'Creative'}],materialsReleased:true};dashboard();",s.ctx);assert.doesNotMatch(s.els.get('#app').html,/data-post=/);assert.match(s.els.get('#app').html,/data-material=/);vm.runInContext('state.postTestEnabled=true;dashboard();',s.ctx);assert.match(s.els.get('#app').html,/data-post="cc-creative"/);});

test('server-based assessment and warning timers ignore devices with clocks hours ahead or behind',()=>{for(const skew of [-86400000,86400000]){const s=screen();s.setDeviceClock(100000+skew);vm.runInContext('tick()',s.ctx);assert.equal(s.els.get('#timer').textContent,'15:00');assert.equal(s.calls.length,0);s.doc.hidden=true;s.events.visibilitychange();vm.runInContext('tick()',s.ctx);assert.match(s.els.get('#warningCountdown').textContent,/10 detik/);s.setDeviceClock(100000-skew);s.advance(2000);vm.runInContext('tick()',s.ctx);assert.match(s.els.get('#warningCountdown').textContent,/8 detik/);}});

test('terminated candidate can fill a profile and access released materials without a post-test button',()=>{const s=screen();vm.runInContext("state={candidateName:'QA',profile:{interests:'Musik'},profileStatus:'saved',stages:{pre:{status:'terminated',grading:'complete',terminationReason:'time_expired'}},materialRoles:[{roleKey:'cc-creative',team:'CC',role:'Creative'}],materialsReleased:true};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/id="editProfile"/);assert.match(s.els.get('#app').html,/data-material=/);assert.doesNotMatch(s.els.get('#app').html,/data-post=/);s.els.get('#editProfile').onclick();assert.match(s.els.get('#app').html,/TANPA BATAS WAKTU/);assert.match(s.els.get('#app').html,/>Musik<\/textarea>/);});

test('common comparison is visible with the same code while held materials and post-test are absent',()=>{const s=screen();vm.runInContext("state={candidateName:'QA',accessCode:'123456',comparisonEnabled:true,materialsHeld:true,roles:{'cc-creative':{team:'CC',role:'Creative'}},stages:{pre:{status:'paused'}},materialRoles:[],preferences:['cc-creative']};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/Pendalaman pembanding/);assert.match(s.els.get('#app').html,/123456/);assert.doesNotMatch(s.els.get('#app').html,/data-post=|data-material=|id="downloadPDF"/);s.els.get('#beginComparison').onclick();assert.match(s.els.get('#app').html,/10 KASUS/);assert.match(s.els.get('#app').html,/TANPA BATAS WAKTU/);assert.ok(s.els.has('#comparisonConsent'));});
test('a complete replacement baseline can render without any original timed pre-test',()=>{const s=screen();vm.runInContext("state={candidateName:'QA',comparisonEnabled:true,materialsHeld:true,roles:{},preferences:[],stages:{comparison:{status:'submitted',grading:'complete',comparable:true,answeredCount:10,totalQuestions:10}},materialRoles:[]};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/penilaian pendalaman sudah tersimpan/);assert.doesNotMatch(s.els.get('#app').html,/id="beginComparison"/);});

test('self-service shows applied and recommended role scores, confirmation and PDF QR without exposing a post-test start',async()=>{const s=screen();vm.runInContext("state={candidateName:'QA',accessCode:'123456',selfServeMaterials:true,comparisonEnabled:true,materialsHeld:false,roles:{},stages:{comparison:{status:'submitted',grading:'complete',comparable:true,answeredCount:10}},roleSelection:{choices:[{roleKey:'cc-creative',team:'CC',role:'Creative',score:80,applied:true,recommended:false,selected:true,reason:'Pilihan awal'},{roleKey:'pw-curator',team:'PW',role:'Curator',score:90,applied:false,recommended:true,selected:true,reason:'Rekomendasi'}]},materialRoles:[],download:null};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/80\/100/);assert.match(s.els.get('#app').html,/90\/100/);assert.match(s.els.get('#app').html,/Pilihan awalmu/);assert.match(s.els.get('#app').html,/Rekomendasi sistem/);assert.doesNotMatch(s.els.get('#app').html,/downloadPDF|data-post=/);s.doc.querySelectorAll=selector=>selector==='[name=candidateMaterialRole]:checked'?[{value:'pw-curator'}]:[];await s.els.get('#confirmMaterialRoles').onclick();assert.equal(s.calls.at(-1).action,'candidate-materials');assert.deepEqual(s.calls.at(-1).data.roles,['pw-curator']);vm.runInContext("state.download={url:'/api?action=material-pdf&code=123456',qr:'<svg></svg>'};state.materialsReleased=true;state.materialRoles=[{roleKey:'pw-curator',team:'PW',role:'Curator'}];dashboard();",s.ctx);assert.match(s.els.get('#app').html,/downloadPDF/);assert.match(s.els.get('#app').html,/QR unduh PDF/);assert.doesNotMatch(s.els.get('#app').html,/data-post=/);});

test('self-service incomplete comparison presents continuation and no material selection',async()=>{const s=screen();vm.runInContext("state={candidateName:'QA',selfServeMaterials:true,comparisonEnabled:true,stages:{comparison:{status:'submitted',grading:'complete',comparable:false,answeredCount:2}},materialRoles:[]};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/2\/10/);assert.match(s.els.get('#app').html,/resumeComparison/);assert.doesNotMatch(s.els.get('#app').html,/candidateMaterialRole|downloadPDF/);await s.els.get('#resumeComparison').onclick();assert.equal(s.calls[0].action,'comparison-resume');});

test('leader candidates see four-case gate before material selection, with no leadership score exposed',async()=>{const s=screen();vm.runInContext("state={candidateName:'QA',selfServeMaterials:true,leaderTrack:true,leadershipReady:false,comparisonEnabled:true,stages:{comparison:{status:'submitted',grading:'complete',comparable:true,answeredCount:10}},roleSelection:null,materialRoles:[]};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/beginLeadership/);assert.doesNotMatch(s.els.get('#app').html,/candidateMaterialRole|downloadPDF/);s.els.get('#beginLeadership').onclick();assert.match(s.els.get('#app').html,/4 KASUS/);assert.match(s.els.get('#app').html,/15–20 menit/);assert.match(s.els.get('#app').html,/TANPA BATAS WAKTU/);vm.runInContext("state.stages.leadership={status:'submitted',grading:'complete',answeredCount:1};dashboard();",s.ctx);assert.match(s.els.get('#app').html,/1\/4/);await s.els.get('#resumeLeadership').onclick();assert.equal(s.calls.at(-1).action,'leadership-resume');});

test('leader exam reuses copy and tab warning with ten-second confirmation without a test deadline',async()=>{const s=screen();vm.runInContext("stage='leadership';quiz={expiresAt:null};answers={ldr01:'Tentukan owner.'};",s.ctx);s.doc.hidden=true;s.events.visibilitychange();s.advance(10001);await vm.runInContext('warningAutoSubmit()',s.ctx);assert.equal(s.calls[0].data.stage,'leadership');assert.equal(s.calls[0].data.answers.ldr01,'Tentukan owner.');assert.deepEqual(s.calls.map(x=>x.action),['security-warning','security-timeout','evaluate']);});
