const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let config,records=[],selected=null,current=null,view='assessment';
async function api(action,data,params={}){const r=await fetch('/api?'+new URLSearchParams({action,...params}),data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});let j;try{j=await r.json();}catch{throw new Error('Koneksi bermasalah');}if(!r.ok)throw new Error(j.error||'Terjadi kendala');return j;}
const msg=(id,s,ok=false)=>{const e=$(id);if(e){e.textContent=s;e.className=ok?'small success':'small danger';}};
const roleLabel=k=>config.roles[k]?config.roles[k].team+' · '+config.roles[k].role:k;
const stageLabel=s=>s==='leadership'?'Assessment Leader PW':s==='comparison'?'Pendalaman pembanding':s==='pre'?'Pre-assessment':(s.startsWith('post:')?'Post-test · ':'Practical · ')+roleLabel(s.split(':')[1]);
async function auth(){const a=await api('admin-me');if(!a.authenticated){$('#login').innerHTML='<section class="card hero"><h1>Admin login.</h1><div class="field"><label for="pw">PASSWORD</label><input type="password" id="pw" autocomplete="current-password"></div><button class="btn blue" id="loginBtn">Masuk</button><p id="loginMsg"></p></section>';$('#loginBtn').onclick=login;$('#pw').onkeydown=e=>{if(e.key==='Enter')login();};return;}$('#login').classList.add('hidden');$('#admin').classList.remove('hidden');$('#logout').classList.remove('hidden');config=await api('admin-config');wire();renderAI();renderOperations();renderBank();await load();}
async function login(){try{await api('admin-login',{password:$('#pw').value});await auth();}catch(e){msg('#loginMsg',e.message);}}
function wire(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{for(const el of document.querySelectorAll('[data-tab]'))el.classList.toggle('active',el===b);for(const id of ['results','invite','settings','bank'])$('#'+id).classList.toggle('hidden',id!==b.dataset.tab);});$('#logout').onclick=async()=>{await api('admin-logout',{});location.reload();};$('#search').oninput=renderList;$('#sortBy').onchange=renderList;$('#scoreMin').oninput=renderList;$('#scoreMax').oninput=renderList;for(const id of filterIds)$('#'+id).onchange=renderList;$('#resetFilters').onclick=()=>{for(const id of filterIds)$('#'+id).value='';$('#search').value='';$('#sortBy').value='newest';$('#showZeroAnswers').checked=false;$('#showHiddenParticipants').checked=false;visibilityChanged();};$('#showZeroAnswers').onchange=visibilityChanged;$('#showHiddenParticipants').onchange=visibilityChanged;$('#refreshList').onclick=()=>load().catch(e=>msg('#listMsg',e.message));$('#createInvite').onclick=create;$('#saveAI').onclick=saveAI;}
function renderAI(){$('#aiStatus').innerHTML='<p class="pill '+(config.ai.configured?'green':'amber')+'">'+(config.ai.configured?'API key terpasang':'API key belum terpasang')+'</p><p class="small muted">Model: '+esc(config.ai.model)+'</p>';$('#model').value=config.ai.model;}
async function saveAI(){const btn=$('#saveAI');btn.disabled=true;try{await api('admin-ai',{apiKey:$('#apiKey').value.trim(),model:$('#model').value.trim()});$('#apiKey').value='';config=await api('admin-config');renderAI();msg('#aiMsg','Konfigurasi tersimpan. Proses satu jawaban uji untuk memverifikasi layanan AI.',true);}catch(e){msg('#aiMsg',e.message);}finally{btn.disabled=false;}}
async function create(){const btn=$('#createInvite');btn.disabled=true;$('#inviteResult').innerHTML='';try{const r=await api('admin-invite',{candidateName:$('#invName').value.trim(),currentTeam:$('#invTeam').value.trim(),expiresHours:Number($('#invExpiry').value)});$('#inviteResult').innerHTML='<p>'+esc(r.candidateName)+' · '+esc(r.currentTeam||'Tim belum diisi')+'</p><div class="codebox" id="newCode">'+esc(r.accessCode)+'</div><p class="small">Peserta membuka '+esc(location.origin)+' lalu mengetik kode yang sama untuk pre-test dan post-test.</p><button class="btn" id="copy">Salin kode</button>';$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(r.accessCode);$('#copy').textContent='Tersalin';}catch{msg('#inviteMsg','Salin kode yang tampil secara manual.');}};msg('#inviteMsg','Kode peserta dibuat.',true);await load();}catch(e){msg('#inviteMsg',e.message);}finally{btn.disabled=false;}}
async function load(){const r=await api('admin-submissions');records=r.records;renderFilterOptions();renderList();$('#legacy').innerHTML=(r.legacy||[]).map(x=>'<p>'+esc(x.candidateName)+' · '+esc(x.team)+' · '+esc(x.role)+' · '+x.score+'%</p>').join('')||'<p class="muted">Tidak ada arsip.</p>';}
function zeroAnswerSession(r){const pre=r?.stages?.pre;return !!pre&&['submitted','terminated'].includes(pre.status)&&pre.answeredCount===0&&!Object.entries(r.stages).some(([stage,s])=>stage!=='pre'&&s.answeredCount>0);}
function visibleRecord(r){return ($('#showZeroAnswers').checked||!zeroAnswerSession(r))&&($('#showHiddenParticipants').checked||!r.hidden);}
function visibilityChanged(){if(selected&&!visibleRecord(records.find(r=>r.token===selected)||{})){selected=null;current=null;$('#detail').innerHTML='<div class="card"><p>Peserta disembunyikan dari daftar. Gunakan pilihan filter untuk menampilkannya kembali.</p></div>';}renderList();}
async function setParticipantHidden(hidden){const token=current.record.token,btn=$('#toggleParticipantHidden');btn.disabled=true;try{await api('admin-visibility',{token,hidden});await load();if(visibleRecord(records.find(r=>r.token===token)||{}))await open(token);else visibilityChanged();msg('#listMsg',hidden?'Peserta disembunyikan. Centang Tampilkan peserta tersembunyi untuk mengembalikannya.':'Peserta ditampilkan kembali.',true);}catch(e){msg('#visibilityMsg',e.message);btn.disabled=false;}}
const filterIds=['filterTeam','filterPre','filterComparison','filterLeadership','filterProfile','filterTrack','filterRole','filterReview','scoreRole','filterTrend','scoreMin','scoreMax'];
function renderFilterOptions(){const box=$('#filterTeam'),value=box.value;const teams=[...new Set(records.map(r=>(r.currentTeam||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'id'));box.innerHTML='<option value="">Semua tim asal</option><option value="__none__">Tim belum diisi</option>'+teams.map(t=>'<option value="'+esc(t)+'">'+esc(t)+'</option>').join('');box.value=value==='__none__'||teams.includes(value)?value:'';const roles=$('#filterRole'),old=roles.value;roles.innerHTML='<option value="">Semua posisi pilihan</option>'+Object.keys(config.roles).map(k=>'<option value="'+esc(k)+'">'+esc(roleLabel(k))+'</option>').join('');roles.value=config.roles[old]?old:'';const scoreBox=$('#scoreRole'),scoreOld=scoreBox.value;scoreBox.innerHTML='<option value="">Posisi tertinggi di pendalaman</option>'+Object.keys(config.roles).map(k=>'<option value="'+esc(k)+'">'+esc(roleLabel(k))+'</option>').join('');scoreBox.value=config.roles[scoreOld]?scoreOld:'';}
function stageMatches(stage,value,total){if(!value)return true;if(value==='not_started')return !stage;if(!stage)return false;const ended=['submitted','terminated'].includes(stage.status),full=stage.answeredCount===total,complete=ended&&full&&stage.grading==='complete'&&(total!==10||stage.comparable);return value==='complete'?complete:value==='incomplete'?!complete:value==='active'?['active','paused'].includes(stage.status):value==='ended'?ended:value==='partial'?ended&&!full:value==='pending_ai'?ended&&full&&stage.grading!=='complete':false;}
function matchesAdminFilters(r){const team=$('#filterTeam').value,track=$('#filterTrack').value,profile=$('#filterProfile').value,role=$('#filterRole').value,review=$('#filterReview').value;return (!team||(team==='__none__'?!(r.currentTeam||'').trim():(r.currentTeam||'').trim()===team))&&(!track||(track==='leader'?!!r.leaderTrack:!r.leaderTrack))&&(!profile||(profile==='not_set'?(!r.profileStatus||r.profileStatus==='not_set'):r.profileStatus===profile))&&(!role||(r.preferences||[]).includes(role))&&(!review||(review==='yes'?!!r.reviewRequired:!r.reviewRequired))&&stageMatches(r.stages?.pre,$('#filterPre').value,32)&&stageMatches(r.stages?.comparison,$('#filterComparison').value,10)&&stageMatches(r.stages?.leadership,$('#filterLeadership').value,4);}
function listScore(r){const final=(r.scoreSummary?.final||[]).filter(f=>Number.isFinite(f.score)),key=$('#scoreRole').value,fit=key?final.find(f=>f.roleKey===key):[...final].sort((a,b)=>b.score-a.score||a.roleKey.localeCompare(b.roleKey))[0];if(!fit)return {score:null,delta:null,roleKey:key||null};const previous=(r.scoreSummary?.pre||[]).find(f=>f.roleKey===fit.roleKey);return {score:fit.score,roleKey:fit.roleKey,delta:Number.isFinite(previous?.score)?fit.score-previous.score:null};}
function scoreRange(){const min=$('#scoreMin').value,max=$('#scoreMax').value,low=min===''?0:Number(min),high=max===''?100:Number(max);return {low,high,enabled:min!==''||max!=='',valid:Number.isFinite(low)&&Number.isFinite(high)&&low>=0&&high<=100&&low<=high};}
function matchesScoreFilters(r){const range=scoreRange(),s=listScore(r),trend=$('#filterTrend').value;if(!range.valid)return false;if(range.enabled&&(s.score===null||s.score<range.low||s.score>range.high))return false;return !trend||(trend==='up'?s.delta!==null&&s.delta>0:trend==='down'?s.delta!==null&&s.delta<0:trend==='same'?s.delta===0:trend==='unknown'?s.delta===null:false);}
function sortedRecords(rows){const mode=$('#sortBy').value,name=(a,b)=>(a.candidateName||'').localeCompare(b.candidateName||'','id',{sensitivity:'base',numeric:true})||String(a.token).localeCompare(String(b.token));return [...rows].sort((a,b)=>{if(mode==='name_asc')return name(a,b);if(mode==='name_desc')return -name(a,b);if(mode==='score_asc'||mode==='score_desc'){const x=listScore(a).score,y=listScore(b).score;if(x===null&&y===null)return name(a,b);if(x===null)return 1;if(y===null)return -1;return (mode==='score_asc'?x-y:y-x)||name(a,b);}if(mode==='team')return (a.currentTeam||'').localeCompare(b.currentTeam||'','id')||name(a,b);return (mode==='oldest'?a.createdAt-b.createdAt:b.createdAt-a.createdAt)||name(a,b);});}
function listScoreLabel(r){const s=listScore(r);return s.score===null?'Nilai akhir: belum tersedia':'Nilai akhir '+s.score+'% · '+esc(roleLabel(s.roleKey))+(s.delta===null?' · Selisih belum tersedia':' · '+(s.delta>0?'+':'')+s.delta+' poin dari pre-test');}
function renderList(){const zeroCount=records.filter(zeroAnswerSession).length,manualCount=records.filter(r=>r.hidden).length;$('#zeroAnswerCount').textContent=zeroCount+' sesi 0/32 · '+manualCount+' peserta disembunyikan manual. Data dan kode tetap tersimpan.';const active=records.filter(r=>!r.hidden&&!zeroAnswerSession(r)),required=active.filter(r=>r.requiresComparison&&!r.stages.comparison?.comparable).length;$('#comparisonCount').textContent=active.length+' peserta/sesi di luar filter · '+required+' masih diwajibkan pendalaman oleh aturan sistem saat ini. Jumlah ini bukan keputusan siapa yang wajib tes ulang secara metodologis.';const q=$('#search').value.toLowerCase(),filtered=sortedRecords(records.filter(visibleRecord).filter(matchesAdminFilters).filter(matchesScoreFilters).filter(r=>(r.candidateName+' '+(r.currentTeam||'')+' '+(r.accessCode||'')+' '+r.shortlist.map(x=>roleLabel(x.roleKey)).join(' ')).toLowerCase().includes(q)));msg('#scoreFilterMsg',scoreRange().valid?'':'Rentang nilai harus 0–100 dan minimum tidak boleh melebihi maksimum.');$('#filterCount').textContent='Menampilkan '+filtered.length+' sesi sesuai filter. Di luar filter tersembunyi/0 jawaban: '+active.length+'. Total tersimpan: '+records.length+'.';$('#list').innerHTML=filtered.map(r=>'<div class="listitem '+(selected===r.token?'active':'')+'" data-token="'+r.token+'"><b>'+esc(r.candidateName)+'</b><p class="small">'+esc(r.currentTeam||'')+' · Kode '+esc(r.accessCode||'belum dibuat')+'</p><div class="small muted">'+new Date(r.createdAt).toLocaleDateString('id-ID')+'</div><span class="pill '+(r.stages.pre?.status==='terminated'?'red':r.stages.pre?.grading==='complete'?'green':'amber')+'">'+esc(r.stages.pre?.status||'Diundang')+' · '+esc(r.stages.pre?.grading||'Belum dinilai')+'</span><p class="small">'+listScoreLabel(r)+'</p>'+(r.leaderTrack?'<p class="small">Pelamar Leader PW</p>':'')+(r.hidden?'<p class="small warning">Disembunyikan manual</p>':'')+(zeroAnswerSession(r)?'<p class="small warning">Sesi kosong · 0/32</p>':'')+(r.reviewRequired?'<p class="small danger">Perlu validasi</p>':'')+'</div>').join('')||'<p class="muted">Tidak ada peserta yang cocok dengan filter.</p>';document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>open(b.dataset.token));}
async function open(token){try{selected=token;renderList();current=await api('admin-submissions',null,{id:token});renderDetail();}catch(e){msg('#listMsg',e.message);}}
function scoreText(value){return value===null||value===undefined?'Belum terukur':value+'%';}
function fitsTable(fits,preferences=[]){return '<div class="wide-table"><table><thead><tr><th>Posisi</th><th>Kualitas bukti</th><th>Kecukupan bukti*</th><th>Status</th><th>Preferensi</th></tr></thead><tbody>'+fits.map(f=>'<tr><td>'+esc(roleLabel(f.roleKey))+'</td><td>'+scoreText(f.score)+'</td><td>'+f.coverage+'%</td><td>'+(f.score===null?'Belum terukur':f.reviewRequired?'Perlu review rubrik':f.evidenceReady?'Bukti awal tersedia':'Bukti terbatas')+'</td><td>'+(preferences.includes(f.roleKey)?'Dipilih':'Potensi lain')+'</td></tr>').join('')+'</tbody></table></div><p class="small muted">*Kecukupan dihitung dari jumlah pengamatan per kompetensi, terpisah dari kualitas. Ini indikator operasional pilot, bukan confidence statistik atau batas kelulusan.</p>';}

function renderDetail(){const r=current.record;$('#detail').innerHTML='<section class="card"><span class="tag">'+esc(r.version)+'</span><h2>'+esc(r.candidateName)+'</h2><p class="muted">'+esc(r.identity?.contact||'Belum mulai')+'</p><button id="toggleParticipantHidden" class="btn">'+(r.adminVisibility?.hidden?'Tampilkan kembali peserta ini':'Filter / sembunyikan peserta ini')+'</button><p id="visibilityMsg" class="small muted">Filter daftar admin; jawaban dan kode tetap tersimpan.</p><label><input id="leaderTrack" type="checkbox" '+(r.leaderTrack?.enabled?'checked':'')+'> Pelamar Leader PW</label><p id="leaderTrackMsg" class="small muted">Jalur assessment, bukan keputusan kelulusan. Modul empat kasus leader aktif setelah pendalaman umum.</p><div class="detail-tabs"><button id="assessmentTab" class="btn '+(view==='assessment'?'blue':'')+'">Assessment</button><button id="profileTab" class="btn '+(view==='profile'?'blue':'')+'">Personal Profile</button></div><div id="detailContent"></div></section>';$('#leaderTrack').onchange=async e=>{const box=e.target;box.disabled=true;try{await api('admin-leader-track',{token:r.token,enabled:box.checked});await load();await open(r.token);}catch(error){box.checked=!!r.leaderTrack?.enabled;box.disabled=false;msg('#leaderTrackMsg',error.message);}};$('#toggleParticipantHidden').onclick=()=>setParticipantHidden(!r.adminVisibility?.hidden);$('#assessmentTab').onclick=()=>{view='assessment';renderDetail();};$('#profileTab').onclick=()=>{view='profile';renderDetail();};if($('#assignCode'))$('#assignCode').onclick=async()=>{await api('admin-code',{token:r.token});await open(r.token);await load();};if(view==='profile')renderProfile(r);else renderAssessment(r);}
function renderProfile(r){const labels={interests:'Minat',talents:'Bakat',education:'Pendidikan',reading:'Bacaan',hobbies:'Hobi',learningInterests:'Minat belajar',mbti:'MBTI',zodiac:'Zodiak',rolePreferences:'Catatan preferensi',english:'English'};$('#detailContent').innerHTML='<div class="notice small">Seluruh profil opsional dan non-scoring. English tidak memengaruhi ranking, routing atau kelulusan.</div><p>Status: '+esc(r.profileStatus)+'</p>'+Object.entries(labels).map(([k,l])=>'<h3>'+esc(l)+'</h3><p class="prewrap">'+esc(r.profile?.[k]||'Tidak diisi')+'</p>').join('');}
function renderAssessment(r){const originalPre=r.stages.pre,primary=current.primaryAssessment||{source:'pre',label:'Pre-test diagnostik',result:originalPre?.result};const pre={...originalPre,result:primary.result};const route=current.routing;const final=current.roleResults||[];let html='<div class="notice small"><b>Dasar hasil: '+esc(primary.label)+'.</b> '+(primary.source==='comparison'?'Kasus sama untuk seluruh peserta. Rubrik dan bobot masih pilot; review bukti diperlukan.':'Hasil lama dihitung ulang secara diagnostik. Jangan membuat ranking lintas kandidat dari kualitas jawaban terisi saja. Pendalaman pembanding menjadi dasar baru setelah lengkap dan dinilai.')+'</div><h3>Preferensi kandidat</h3><p>'+esc(r.preferences.map(roleLabel).join(' / ')||'Belum dipilih')+'</p>';
 if(route?.status==='ready'&&(primary.source==='comparison'||['submitted','terminated'].includes(pre?.status)))html+='<h3>Potensi posisi · indikatif</h3><div class="grid">'+route.shortlist.map(f=>'<div class="fit-card"><span>'+esc(roleLabel(f.roleKey))+'</span><strong>'+scoreText(f.score)+'</strong><p class="small">'+(f.applied?'Dipilih kandidat':'Potensi posisi lain')+'</p></div>').join('')+'</div>'+(route.thirdFlag?'<p class="warning small">Posisi ketiga berdekatan: '+esc(roleLabel(route.thirdFlag.roleKey))+'. '+esc(route.thirdFlag.reason)+' Tidak otomatis ditambahkan.</p>':'');
 if((primary.source==='comparison'||['submitted','terminated'].includes(pre?.status))&&pre.result?.complete){const plan=current.materials||{},selectedRoles=plan.selected||[];html+='<h3>Pilih materi setelah diskusi dengan kandidat</h3>'+((r.requiresComparison&&primary.source!=='comparison')?'<p class="warning small">Pendalaman pembanding belum lengkap dan dinilai. Materi belum dapat diterbitkan.</p>':'')+'<p class="small muted">Pilihan awal menggabungkan minat kandidat dan dua rekomendasi sistem. Sesuaikan pilihan bersama kandidat. Post-test mengikuti posisi yang diterbitkan dan baru terlihat setelah akses dibuka manual di bawah.</p><div class="grid">'+Object.entries(config.roles).map(([key,role])=>{const fit=pre.result.roleFits.find(f=>f.roleKey===key),applied=r.preferences.includes(key),recommended=route.shortlist.some(f=>f.roleKey===key);return '<label class="option"><input type="checkbox" name="materialRole" value="'+key+'" '+(selectedRoles.includes(key)?'checked':'')+'><span><b>'+esc(role.team+' · '+role.role)+'</b><br>'+scoreText(fit.score)+' · '+(applied&&recommended?'Minat awal + rekomendasi sistem':applied?'Minat awal':recommended?'Rekomendasi sistem':'Pilihan tambahan')+'</span></label>';}).join('')+'</div><div class="spacer"></div><button id="publishMaterials" class="btn blue" '+(r.requiresComparison&&primary.source!=='comparison'?'disabled':'')+'>'+(plan.released?'Perbarui materi pilihan':'Terbitkan materi pilihan')+'</button><p id="materialsMsg"></p>'+(current.download?'<div class="card material-download"><h3>Scan QR untuk mengunduh PDF</h3><img class="material-qr" alt="QR unduh materi PDF pilihan" src="data:image/svg+xml;charset=utf-8,'+encodeURIComponent(current.download.qr)+'"><p><a class="btn" href="'+esc(current.download.url)+'">Unduh PDF materi pilihan</a></p><p class="small muted">QR berisi akses materi peserta ini. Kode yang sama tetap dipakai untuk post-test.</p></div>':'');}
 if(current.materials?.released){const enabled=!!r.postTestAccess?.enabled,started=Object.keys(r.stages).some(k=>k.startsWith('post:'));html+='<h3>Akses post-test</h3><p class="small">'+(enabled?'Post-test dibuka untuk kandidat ini.':'Post-test masih disembunyikan dari kandidat ini.')+'</p><button id="togglePostTest" class="btn '+(enabled?'':'blue')+'" '+(started||current.operations?.postTestsLocked?'disabled':'')+'>'+(current.operations?.postTestsLocked?'Post-test dikunci global':started?'Post-test sudah dimulai':enabled?'Tutup akses post-test':'Buka post-test')+'</button><p id="postAccessMsg"></p>';}
 if(final.length)html+='<h3>Hasil post-test</h3><div class="wide-table"><table><thead><tr><th>Posisi</th><th>Pre</th><th>Post</th><th>Perbandingan</th></tr></thead><tbody>'+final.map(f=>'<tr><td>'+esc(roleLabel(f.roleKey))+'</td><td>'+f.pre+'</td><td>'+(f.post??'—')+'</td><td>'+(f.gain===null?'—':(f.gain>0?'+':'')+f.gain)+'</td></tr>').join('')+'</tbody></table></div><p class="small muted">Pre/pendalaman dan post-test berbeda bentuk; selisihnya tidak ditafsirkan sebagai learning gain. Practical dilakukan di luar web.</p>';
 html+=Object.entries(r.stages).filter(([stage])=>!stage.startsWith('practical:')).map(([stage,s])=>'<div class="stage-box"><h3>'+esc(stageLabel(stage))+'</h3><p class="small">Terjawab '+Object.keys(s.answers||{}).filter(k=>s.answers[k]!==null&&s.answers[k]!==''&&s.answers[k]!==undefined).length+' / '+(stage==='pre'?32:stage==='comparison'?10:stage==='leadership'?4:6)+' soal. Jawaban kosong belum terukur; tidak menjadi nilai 0.</p><p>Status: '+esc(s.status)+' · Penilaian: '+esc(s.grading?.status||'pending')+'</p>'+(s.autoSubmitReason?'<p class="danger">Jawaban dikirim otomatis: konfirmasi peringatan 10 detik terlewat.</p>':'')+(s.terminationReason?'<p class="danger">Tes diakhiri: '+esc(s.terminationReason)+'</p>':'')+(s.reviewRequired?'<p class="warning small">Perlu validasi: confidence rendah, flag rubrik, peringatan keamanan, atau penghentian tes.</p>':'')+(stage==='leadership'&&s.result?'<p><b>Skor kepemimpinan: '+scoreText(s.result.leadershipScore)+'</b></p><p class="small muted">Terpisah dari skor delapan posisi. Empat kasus berbobot sama, rubrik pilot; nilai final tersedia setelah lengkap. '+(!s.result.comparable?'Kualitas bukti terisi: '+scoreText(s.result.observedScore)+'. ':'')+'Validasi melalui interview dan bukti pengalaman.</p>':'')+(s.result?'<div class="grid3">'+s.result.capability.map(c=>'<div class="fit-card"><span class="small">'+esc(c.label)+'</span><strong>'+scoreText(c.score)+'</strong><span class="small muted">'+c.observations+' pengamatan · '+(c.essayObservations||0)+' esai</span></div>').join('')+'</div><p class="small muted">'+(s.result.complete?'Seluruh jawaban terisi telah dinilai. Ini tidak berarti semua kompetensi cukup terukur.':'Sementara: esai belum seluruhnya dinilai; routing belum final.')+'</p>':'')+(['pre','comparison'].includes(stage)&&s.result?fitsTable(s.result.roleFits,r.preferences):'')+(['submitted','terminated'].includes(s.status)?'<div class="row"><button class="btn blue" data-grade="'+stage+'">'+(s.grading?.status==='complete'?'Sudah dinilai':'Proses penilaian AI')+'</button><button class="btn" data-evidence="'+stage+'">Jawaban &amp; rubrik / review</button></div>':'')+(s.securityEvents?.length?'<h4>Security log</h4><ul>'+s.securityEvents.map(x=>'<li>'+esc(x.type)+' · '+new Date(x.at).toLocaleString('id-ID')+(x.timedOutAt?' · auto-submit':x.confirmedAt?' · dikonfirmasi':' · belum dikonfirmasi')+'</li>').join('')+'</ul>':'')+(s.grading?.model?'<p class="small muted">Model '+esc(s.grading.model)+' · Rubrik '+esc(s.grading.version)+(s.grading.gradingVersion?' · Metode '+esc(s.grading.gradingVersion):'')+' · '+new Date(s.grading.gradedAt).toLocaleString('id-ID')+'</p>':'')+'<div id="evidence-'+stage.replaceAll(':','-')+'"></div></div>').join('');
 html+=Object.entries(r.stages).filter(([,s])=>s.scoreHistory?.length).map(([stage,s])=>'<details class="evidence"><summary>Riwayat skor sebelum pembaruan · '+esc(stageLabel(stage))+'</summary>'+s.scoreHistory.map(h=>'<p class="small">'+new Date(h.at).toLocaleString('id-ID')+' · '+esc(h.reason)+'</p>'+legacyFitsTable(h.previousResult.roleFits||[])).join('')+'</details>').join('');
 if(r.stages.comparison&&['submitted','terminated'].includes(r.stages.comparison.status))html+='<details class="evidence"><summary>Pulihkan kesempatan pendalaman</summary><p class="small">Untuk gangguan teknis. Seluruh jawaban dan nilai percobaan sebelumnya disimpan sebagai riwayat.</p><input id="comparisonResetReason" placeholder="Alasan pemulihan" maxlength="500"><button id="resetComparison" class="btn">Buka kesempatan ulang</button><p id="comparisonResetMsg"></p></details>';
 html+='<h3>Checklist validasi kemampuan · opsional</h3><p class="small muted">Isi hanya bila ada bukti interview/observasi. Checklist ini tidak mengganti atau mengubah skor dan routing otomatis.</p><div class="wide-table"><table><thead><tr><th>Kemampuan</th><th>Validasi</th></tr></thead><tbody>'+Object.entries(config.caps).map(([cap,name])=>'<tr><td>'+esc(name)+'</td><td><select data-checklist="'+cap+'">'+[['','Belum diamati'],['yes','Kuat'],['mid','Perlu validasi'],['no','Belum tampak']].map(([value,text])=>'<option value="'+value+'" '+(r.validationChecklist?.[cap]===value?'selected':'')+'>'+text+'</option>').join('')+'</select></td></tr>').join('')+'</tbody></table></div><h3>Catatan validasi / checklist kemampuan</h3><p class="small muted">Catatan interview atau observasi melengkapi evidence. Override nilai hanya digunakan untuk pengecualian dan tercatat dengan alasan.</p><div class="field"><textarea id="notes" maxlength="5000">'+esc(r.notes||'')+'</textarea></div><button id="saveNotes" class="btn">Simpan catatan</button><p id="detailMsg"></p>';
 $('#detailContent').innerHTML=html;if($('#resetComparison'))$('#resetComparison').onclick=async()=>{try{await api('admin-comparison-reset',{token:r.token,reason:$('#comparisonResetReason').value});await open(r.token);}catch(e){msg('#comparisonResetMsg',e.message);}};if($('#togglePostTest'))$('#togglePostTest').onclick=async()=>{const btn=$('#togglePostTest');btn.disabled=true;try{await api('admin-post-access',{token:r.token,enabled:!r.postTestAccess?.enabled});await open(r.token);}catch(e){msg('#postAccessMsg',e.message);btn.disabled=false;}};if($('#publishMaterials'))$('#publishMaterials').onclick=async()=>{const btn=$('#publishMaterials');btn.disabled=true;try{const roles=[...document.querySelectorAll('[name=materialRole]:checked')].map(x=>x.value);await api('admin-materials',{token:r.token,roles});await open(r.token);}catch(e){msg('#materialsMsg',e.message);btn.disabled=false;}};document.querySelectorAll('[data-grade]').forEach(b=>{if(r.stages[b.dataset.grade].grading?.status==='complete')b.disabled=true;else b.onclick=()=>grade(b.dataset.grade,b);});document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>showEvidence(b.dataset.evidence));$('#saveNotes').onclick=async()=>{try{await api('admin-notes',{token:r.token,notes:$('#notes').value,checklist:Object.fromEntries([...document.querySelectorAll('[data-checklist]')].map(el=>[el.dataset.checklist,el.value]))});msg('#detailMsg','Catatan tersimpan.',true);}catch(e){msg('#detailMsg',e.message);}};}
async function grade(stage,btn){btn.disabled=true;btn.textContent='Menilai…';try{await api('admin-grade',{token:selected,stage});await open(selected);await load();}catch(e){msg('#detailMsg',e.message);btn.disabled=false;btn.textContent='Coba nilai lagi';}}
function renderCriterion(c){
 const quotes=Array.isArray(c.evidenceQuotes)?c.evidenceQuotes:(c.evidence?[c.evidence]:[]);
 return '<div class="evidence"><p><b>'+esc(config.leaderCaps?.[c.cap]||config.caps[c.cap])+': '+c.score+'/4</b> · confidence '+esc(c.confidence)+'</p>'+quotes.map(q=>'<blockquote class="prewrap">'+esc(q)+'</blockquote>').join('')+(c.rationale?'<p><b>Alasan skor:</b> '+esc(c.rationale)+'</p><p><b>Terpenuhi:</b> '+(c.fulfilled||[]).map(esc).join('; ')+'</p><p><b>Belum terpenuhi / kontradiksi:</b> '+((c.missing||[]).map(esc).join('; ')||'Tidak ada unsur rubrik yang belum terpenuhi menurut penilai.')+'</p>':'<p class="small muted">Penilaian lama: alasan rinci belum tersedia. Kutipan lama perlu diaudit.</p>')+'</div>';
}
function evidenceRepairPanel(stage,s){
 if(!['pre','comparison','leadership'].includes(stage)||!s.grades?.length)return '';
 const key=stage.replaceAll(':','-'),p=s.evidenceRevision;
 let html='<details class="evidence"><summary>Audit bukti &amp; riwayat perbaikan nilai</summary><p class="small muted">Confidence adalah estimasi penilai, bukan probabilitas akurasi. Audit memeriksa bukti rubrik, bukan penggunaan AI oleh peserta. Penilaian ulang membuat usulan; nilai aktif berubah hanya setelah diterapkan.</p><div class="row"><button class="btn" id="audit-evidence-'+key+'">Audit relevansi bukti</button><button class="btn" id="regrade-evidence-'+key+'">Buat usulan nilai ulang</button></div><p id="repair-msg-'+key+'"></p>';
 if(s.evidenceAudit)html+='<p><b>Audit AI:</b> '+(s.evidenceAudit.needsReview?'Ada kriteria perlu ditinjau':'Tidak ditemukan masalah oleh audit AI')+'</p><ul>'+s.evidenceAudit.findings.filter(f=>f.status==='needs_review').map(f=>'<li>'+esc(f.id)+' · '+esc(config.leaderCaps?.[f.cap]||config.caps[f.cap])+': '+esc(f.reason)+'</li>').join('')+'</ul>';
 if(p){html+='<p><b>Usulan:</b> '+esc(p.status)+' · '+new Date(p.createdAt).toLocaleString('id-ID')+'</p><div class="wide-table"><table><thead><tr><th>Soal / kriteria</th><th>Lama</th><th>Baru</th><th>Alasan baru</th></tr></thead><tbody>'+p.changes.map(c=>'<tr><td>'+esc(c.id)+' · '+esc(config.leaderCaps?.[c.cap]||config.caps[c.cap])+'</td><td>'+esc(c.before)+'/4</td><td>'+c.after+'/4</td><td>'+esc(c.rationale)+'</td></tr>').join('')+'</tbody></table></div><details><summary>Bukti dan alasan lengkap usulan</summary>'+p.evaluated.grades.map(g=>'<h4>'+esc(g.id)+'</h4>'+g.criteria.map(renderCriterion).join('')).join('')+'</details>';
 if(p.status==='ready')html+='<label>Alasan penerapan<textarea id="repair-reason-'+key+'" maxlength="1000"></textarea></label><button class="btn" id="apply-evidence-'+key+'">Terapkan usulan &amp; simpan nilai lama</button>';
 }
 for(const h of (s.reviewHistory||[]).filter(h=>h.method==='evidence_repair'))html+='<details><summary>Nilai sebelum perbaikan · '+new Date(h.at).toLocaleString('id-ID')+'</summary><p>'+esc(h.reason)+'</p>'+h.previousGrades.map(g=>'<h4>'+esc(g.id)+'</h4>'+g.criteria.map(renderCriterion).join('')).join('')+'</details>';
 return html+'</details>';
}
function wireEvidenceRepair(stage){
 const key=stage.replaceAll(':','-'),token=current.record.token;
 for(const [prefix,action]of [['audit','admin-evidence-audit'],['regrade','admin-evidence-regrade'],['apply','admin-evidence-apply']]){
 const btn=$('#'+prefix+'-evidence-'+key);if(!btn)continue;btn.onclick=async()=>{btn.disabled=true;msg('#repair-msg-'+key,'Memproses…',true);try{const payload={token,stage};if(prefix==='apply'){payload.proposalId=current.record.stages[stage].evidenceRevision.id;payload.reason=$('#repair-reason-'+key).value;}await api(action,payload);await load();await open(token);await showEvidence(stage);}catch(e){msg('#repair-msg-'+key,e.message);btn.disabled=false;}};
 }
}
async function showEvidence(stage){const s=current.record.stages[stage];const container=$('#evidence-'+stage.replaceAll(':','-'));if(container.innerHTML){container.innerHTML='';return;}const qs=stage==='pre'?config.bank:(await api('admin-bank',null,{stage})).questions;const essays=qs.filter(q=>q.type==='essay'&&s.answers[q.id]?.trim());container.innerHTML='<div class="hr"></div>'+evidenceRepairPanel(stage,s)+qs.map(q=>{const a=s.answers[q.id];return'<details class="evidence"><summary>'+esc(q.id)+' · '+esc(q.q)+'</summary><p class="prewrap">'+esc(q.type==='sjt'?q.options[a]?.text||'Tidak dijawab':a||'Tidak dijawab')+'</p>'+(q.criteria?'<ul>'+q.criteria.map(c=>'<li><b>'+esc(config.leaderCaps?.[c.cap]||config.caps[c.cap])+'</b>: '+esc(c.description)+'</li>').join('')+'</ul>':'')+(s.grades?.find(g=>g.id===q.id)?.criteria||[]).map(renderCriterion).join('')+'</details>';}).join('')+(essays.length?'<details class="evidence"><summary>Review pengecualian / override rubrik</summary><p class="small muted">Gunakan hanya saat AI gagal atau hasil perlu koreksi. Evidence harus kutipan persis jawaban kandidat. Semua kriteria esai pada tahap ini harus terisi.</p>'+essays.map(q=>'<h4>'+esc(q.id)+'</h4>'+q.criteria.map(c=>{const g=s.grades?.find(x=>x.id===q.id)?.criteria.find(x=>x.cap===c.cap);return'<div class="grid"><div class="field"><label>'+esc(config.leaderCaps?.[c.cap]||config.caps[c.cap])+' · SKOR 0–4</label><input type="number" min="0" max="4" step="1" data-override-score="'+q.id+'|'+c.cap+'" value="'+(g?.score??0)+'"></div><div class="field"><label>KUTIPAN PERSIS DARI JAWABAN</label><input data-override-evidence="'+q.id+'|'+c.cap+'" value="'+esc(g?.evidence||'')+'"></div></div>';}).join('')).join('')+'<div class="field"><label>ALASAN OVERRIDE</label><textarea id="override-reason-'+stage.replaceAll(':','-')+'"></textarea></div><button class="btn" id="override-'+stage.replaceAll(':','-')+'">Simpan review pengecualian</button><p id="override-msg-'+stage.replaceAll(':','-')+'"></p></details>':'');wireEvidenceRepair(stage);const btn=$('#override-'+stage.replaceAll(':','-'));if(btn)btn.onclick=async()=>{try{const grades=essays.map(q=>({id:q.id,criteria:q.criteria.map(c=>({cap:c.cap,score:Number(container.querySelector('[data-override-score="'+q.id+'|'+c.cap+'"]').value),evidence:container.querySelector('[data-override-evidence="'+q.id+'|'+c.cap+'"]').value,confidence:1})),flags:[]}));await api('admin-review',{token:selected,stage,grades,reason:$('#override-reason-'+stage.replaceAll(':','-')).value});await open(selected);}catch(e){msg('#override-msg-'+stage.replaceAll(':','-'),e.message);}};}
function renderBank(){$('#bankContent').innerHTML='<div class="field"><label>TAHAP</label><select id="bankStage"><option value="pre">Pre-assessment universal</option><option value="comparison">Pendalaman pembanding universal</option><option value="leadership">Assessment Leader PW</option>'+Object.keys(config.roles).map(k=>'<option value="post:'+k+'">Post-test · '+esc(roleLabel(k))+'</option>').join('')+'</select></div><div id="bankQuestions"></div><h3>Bobot draft per posisi</h3>'+Object.keys(config.roles).map(k=>'<details class="evidence"><summary>'+esc(roleLabel(k))+'</summary><p>'+Object.entries(config.weights[k]).map(([c,w])=>esc(config.caps[c])+': '+w).join(' · ')+'</p></details>').join('');const display=qs=>$('#bankQuestions').innerHTML=qs.map(q=>'<details class="evidence"><summary>'+esc(q.id)+' · '+esc(q.q)+'</summary>'+(q.options?'<ol>'+q.options.map(o=>'<li>'+esc(o.text)+'<p class="small muted">'+Object.entries(o.signals).map(([c,v])=>esc(config.caps[c])+': '+v+'/4').join(' · ')+'</p></li>').join('')+'</ol>':'<ul>'+q.criteria.map(c=>'<li>'+esc(config.leaderCaps?.[c.cap]||config.caps[c.cap])+': '+esc(c.description)+'</li>').join('')+'</ul>')+'</details>').join('');display(config.bank);$('#bankStage').onchange=async()=>{try{display((await api('admin-bank',null,{stage:$('#bankStage').value})).questions);}catch(e){$('#bankQuestions').textContent=e.message;}};}
auth().catch(e=>{$('#login').innerHTML='<p class="danger">'+esc(e.message)+'</p>';});


function renderOperations(){const ops=config.operations||{},migration=config.migration;$('#operations').innerHTML='<h2>Distribusi &amp; pendalaman</h2>'+(migration?'<p class="pill '+(migration.state==='complete'?'green':'amber')+'">Hitung ulang: '+esc(migration.state)+' · '+(migration.verified||0)+' / '+(migration.total||0)+' sesi</p>':'')+'<p class="small">Skor '+esc(config.scoring?.version||'versi lama')+'. Materi dapat disiapkan setelah pendalaman pembanding lengkap dan dinilai. Post-test tetap dibuka manual per kandidat.</p><label class="option"><input id="holdMaterials" type="checkbox" '+(ops.materialsHeld?'checked':'')+'> Tahan seluruh akses materi peserta</label><label class="option"><input id="enableComparison" type="checkbox" '+(ops.comparisonEnabled?'checked':'')+'> Buka kesempatan memulai pendalaman yang sama untuk seluruh peserta</label><label class="option"><input id="selfServeMaterials" type="checkbox" '+(ops.selfServeMaterials?'checked':'')+'> Peserta memilih posisi dan menerbitkan materi setelah pendalaman lengkap</label><label class="option"><input id="lockPostTests" type="checkbox" '+(ops.postTestsLocked!==false?'checked':'')+'> Kunci post-test untuk seluruh peserta (tetap aktif selama tahap ini)</label><button id="saveOperations" class="btn blue">Simpan pengaturan</button><p id="operationsMsg"></p>';$('#saveOperations').onclick=async()=>{try{await api('admin-operations',{materialsHeld:$('#holdMaterials').checked,comparisonEnabled:$('#enableComparison').checked,selfServeMaterials:$('#selfServeMaterials').checked,postTestsLocked:$('#lockPostTests').checked});config=await api('admin-config');renderOperations();if(selected)await open(selected);msg('#operationsMsg','Pengaturan tersimpan.',true);}catch(e){msg('#operationsMsg',e.message);}};}

function legacyFitsTable(fits){return '<table><thead><tr><th>Posisi</th><th>Skor lama · jawaban kosong dihitung 0</th></tr></thead><tbody>'+fits.map(f=>'<tr><td>'+esc(roleLabel(f.roleKey))+'</td><td>'+scoreText(f.score)+'</td></tr>').join('')+'</tbody></table>';}
