const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const label=k=>k==='leadership'?'Assessment Leader PW':k==='comparison'?'Pendalaman pembanding':k==='pre'?'Pre-assessment universal':(k.startsWith('post:')?'Post-test':'Practical');
let token=new URLSearchParams(location.search).get('invite')||sessionStorage.getItem('ccpw_token')||'',state=null,stage=null,quiz=null,answers={},revision=0,active=false,closed=false,armed=0,timer=null,saveTimer=null,saving=Promise.resolve(),closing=false,retryPayload=null,warningOpen=false,warningId='',warningRequest=Promise.resolve(),resuming=false,warningDeadline=0,warningTimeout=null;
let clockBase=null,clockTick=0;const autoGradingAttempted=new Set();let gradingBusy=false;let gradingPoll=null;let saveRetryTimer=null;
function syncClock(serverNow){if(!Number.isFinite(serverNow))throw new Error('Jam server tidak tersedia. Muat ulang halaman.');clockBase=serverNow;clockTick=performance.now();}
function testNow(){return clockBase===null?Date.now():clockBase+performance.now()-clockTick;}
async function api(action,data,params={}){const url='/api?'+new URLSearchParams({action,token,...params});const options=data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...data})}:{};if(typeof AbortSignal!=='undefined'&&AbortSignal.timeout)options.signal=AbortSignal.timeout(['submit','evaluate','security-timeout'].includes(action)?75000:15000);const r=await fetch(url,options);let j;try{j=await r.json();}catch{throw new Error('Koneksi bermasalah; coba lagi.');}if(!r.ok)throw Object.assign(new Error(j.error||'Terjadi kendala'),{status:r.status});if(['start','quiz','resume-recovered'].includes(action))syncClock(j.serverNow);return j;}
function message(id,text,ok=false){const el=$(id);if(el){el.textContent=text;el.className=ok?'success small':'danger small';}}
function loading(text='Memuat…'){$('#app').innerHTML='<section class="card hero"><h1>'+esc(text)+'</h1></section>';}
function draftKey(){return 'ccpw_draft:'+token+':'+stage;}
function stashDraft(){try{sessionStorage.setItem(draftKey(),JSON.stringify({answers,revision}));}catch{/* Server autosave still operates when browser storage is unavailable. */}}
function clearDraft(){try{sessionStorage.removeItem(draftKey());}catch{}}
function restoreDraft(){try{const d=JSON.parse(sessionStorage.getItem(draftKey())||'null');if(d&&Number.isInteger(d.revision)&&d.revision>revision&&d.answers&&typeof d.answers==='object'){const permitted=new Set(quiz.questions.map(q=>q.id));for(const [k,v]of Object.entries(d.answers))if(permitted.has(k)&&!quiz.lockedAnswers?.includes(k))answers[k]=v;revision=d.revision;}}catch{}}
function committedRefreshError(error){$('#app').innerHTML='<section class="card hero"><h1>Jawaban sudah tersimpan.</h1><p>Halaman status belum berhasil dimuat. Kamu tidak perlu mengirim ulang atau mengulang tes.</p><button id="retryStatus" class="btn blue">Muat ulang status</button><p id="statusRetryMsg"></p></section>';message('#statusRetryMsg',error.message);$('#retryStatus').onclick=()=>refresh().catch(e=>message('#statusRetryMsg',e.message));}
function landing(){$('#app').innerHTML='<section class="card hero"><span class="tag">ASSESSMENT KANDIDAT</span><h1>Assessment Kandidat<br>CC–PW</h1><p>Evaluasi kompetensi kandidat untuk tim Corporate Communications dan People &amp; Workplace.</p><div class="journey"><span>01 · Pre-test &amp; pendalaman</span><span>02 · Pilihan posisi &amp; materi</span><span>03 · Post-test</span></div><div class="field"><label for="inviteInput">KODE PESERTA · 6 DIGIT</label><input id="inviteInput" placeholder="Contoh: 123456" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="off"></div><button class="btn blue" id="openInvite">Masuk</button><p id="landingMsg" role="status"></p></section>';$('#openInvite').onclick=async()=>{const btn=$('#openInvite');btn.disabled=true;try{const r=await api('resolve-code',{code:$('#inviteInput').value.trim()});token=r.token;await refresh();}catch(e){message('#landingMsg',e.message);btn.disabled=false;}};$('#inviteInput').onkeydown=e=>{if(e.key==='Enter')$('#openInvite').click();};}
async function refresh(){state=await api('invite');sessionStorage.setItem('ccpw_token',token);const pre=state.stages.pre;
 const running=Object.entries(state.stages).find(([k,s])=>(!state.postTestsLocked||!k.startsWith('post:'))&&((state.comparisonEnabled||state.stages.comparison)?['pre','comparison','leadership'].includes(k):true)&&['active','paused'].includes(s.status));
 if(running){stage=running[0];quiz=await api('quiz',null,{stage});answers=quiz.answers||{};revision=quiz.revision||0;restoreDraft();if(quiz.warning){renderExam();return showSecurityWarning(quiz.warning.type,quiz.warning);}return restorePrompt();}
 if(state.initialPreRequired&&!pre)return gate();
 if(state.initialPreRequired&&pre&&['submitted','terminated'].includes(pre.status)&&state.profileStatus==='not_set')return profile();
 if(state.comparisonEnabled||state.stages.comparison)return dashboard();
 if(!pre)return gate();if(['submitted','terminated'].includes(pre.status)&&state.profileStatus==='not_set')return profile();dashboard();}

function gate(){const roles=Object.entries(state.roles).map(([k,r])=>'<label class="option role-option"><input type="checkbox" name="preference" value="'+k+'"><span>'+esc(r.team)+'<b>'+esc(r.role)+'</b></span></label>').join('');$('#app').innerHTML='<section class="card hero"><span class="tag">32 SOAL · '+state.duration+' MENIT</span><h1>Halo, '+esc(state.candidateName)+'.</h1><p>24 situasi kerja, 4 esai singkat, dan 4 kasus lintas posisi. Pilihan posisi menunjukkan minatmu; penilaian tetap mencakup semua posisi.</p><div class="grid"><div class="field"><label for="name">NAMA LENGKAP</label><input id="name" maxlength="150" value="'+esc(state.candidateName)+'"></div><div class="field"><label for="contact">EMAIL / NO. HP</label><input id="contact" maxlength="200"></div></div><div class="field"><label for="currentRole">POSISI SAAT INI · OPSIONAL</label><input id="currentRole" maxlength="200" value="'+esc(state.currentTeam||'')+'"></div><h3>Posisi yang kamu minati</h3><div class="grid">'+roles+'</div><div class="spacer"></div>'+rules()+'<label class="option"><input type="checkbox" id="consent"> Saya memahami aturan tes dan setuju jawaban kerja dikirim ke layanan AI untuk penilaian berbasis rubrik. Profil personal tidak ikut dinilai.</label><button class="btn blue" id="start">Masuk fullscreen &amp; mulai</button><p id="gateMsg" role="status"></p></section>';$('#start').onclick=()=>start('pre');}
function rules(){return '<div class="warning small"><b>Aturan tes:</b> fullscreen dicoba saat mulai, tetapi keluar fullscreen untuk mengetik tidak dianggap curang. Tetap berada di halaman tes. Pindah tab/aplikasi atau mencoba copy/paste memunculkan peringatan: konfirmasi dalam 10 detik atau jawaban yang tersimpan dikirim otomatis. Timer tetap berjalan untuk tahap berbatas waktu. Pendalaman umum dan modul leader tanpa batas waktu. Copy/paste, menu konteks, drag/drop dan shortcut tertentu dibatasi. Jawaban disimpan berkala. Pada pre-test berbatas waktu, tes ditutup saat waktu habis. Materi dibaca di luar mode tes.</div>';}
async function fullscreen(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{/* Fullscreen is optional: tablet keyboards and browsers may exit or reject it. */}}
async function start(nextStage){const btn=$('#start');if(btn)btn.disabled=true;try{const data={stage:nextStage};if(nextStage==='leadership'){data.consent=!!$('#leaderConsent')?.checked;if(!data.consent)throw new Error('Setujui aturan modul leader sebelum mulai.');}if(nextStage==='pre'){data.identity={name:$('#name').value.trim(),contact:$('#contact').value.trim(),currentRole:$('#currentRole').value.trim()};data.preferences=[...document.querySelectorAll('[name=preference]:checked')].map(x=>x.value);if(!data.identity.name||!data.identity.contact||!data.preferences.length||!$('#consent').checked)throw new Error('Isi nama dan kontak, pilih posisi, lalu setujui aturan tes.');}if(nextStage==='comparison'){data.consent=!!$('#comparisonConsent')?.checked;if(!data.consent)throw new Error('Setujui aturan pendalaman sebelum mulai.');data.identity={name:$('#comparisonName').value.trim(),contact:$('#comparisonContact').value.trim()};data.preferences=[...document.querySelectorAll('[name=comparisonPreference]:checked')].map(x=>x.value);if(!data.identity.name||!data.identity.contact)throw new Error('Isi nama dan kontak.');}await fullscreen();quiz=await api('start',data);stage=nextStage;answers={};revision=0;renderExam();}catch(e){active=false;try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}message('#gateMsg',e.message);if(btn)btn.disabled=false;}}
function restorePrompt(){const warning=quiz.warning;$('#app').innerHTML='<section class="card hero"><h1>'+(warning?'Kecurangan terdeteksi':'Tes sudah dimulai.')+'</h1><p>Jawaban tersimpan. Sesi yang dipulihkan baru menjalankan timer saat dilanjutkan. Fullscreen bersifat opsional.</p>'+rules()+'<button id="restore" class="btn blue">'+(warning?'lanjutkan tes':'Lanjutkan sesi')+'</button><p id="gateMsg"></p></section>';$('#restore').onclick=async()=>{try{await fullscreen();if(quiz.recoverable)quiz=await api('resume-recovered',{stage});else await api('security-resume',{stage,eventId:warning?.id});renderExam();}catch(e){if(quiz.expiresAt!==null&&testNow()>quiz.expiresAt)return close(true,'time_expired');message('#gateMsg',e.message);}};}
function renderExam(){if(revision>quiz.revision)saveTimer=setTimeout(()=>save(),800);warningOpen=false;warningId='';warningDeadline=0;clearTimeout(warningTimeout);resuming=false;active=true;closed=false;closing=false;armed=testNow()+1500;document.body.classList.add('no-select');$('#app').innerHTML='<section><div class="test-head"><div class="row between"><div><b>'+esc(label(stage))+'</b><div class="small muted">'+esc(state.candidateName)+'</div></div><div id="timer" class="timer"></div></div><div class="progressbar"><div id="progress"></div></div><div class="small muted" id="saveState">Jawaban akan disimpan berkala.</div></div><div id="questions">'+quiz.questions.map((q,i)=>'<section class="card question"><div class="small muted">'+(i+1)+' / '+quiz.questions.length+' · '+(q.type==='essay'?'ESAI SINGKAT':'SITUASI KERJA')+'</div><h3>'+esc(q.q)+'</h3>'+(q.type==='sjt'?q.options.map(o=>'<label class="option"><input type="radio" name="'+q.id+'" value="'+o.id+'" '+(answers[q.id]===o.id?'checked':'')+'>'+esc(o.text)+'</label>').join(''):'<textarea aria-label="Jawaban soal '+(i+1)+'" data-question="'+q.id+'" '+(quiz.lockedAnswers?.includes(q.id)?'readonly':'')+' maxlength="'+q.maxLength+'" placeholder="Jelaskan langkah dan alasanmu…">'+esc(answers[q.id]||'')+'</textarea><div class="small muted">Maksimal '+q.maxLength+' karakter.'+(quiz.lockedAnswers?.includes(q.id)?' Jawaban ini tersimpan sebelum pemulihan dan terkunci.':'')+'</div>')+'</section>').join('')+'</div><div class="card"><div class="row between"><span id="answered"></span><button id="submit" class="btn blue">Kirim jawaban</button></div><p id="examMsg" role="status"></p></div></section>';
 document.querySelectorAll('#questions input').forEach(el=>el.onchange=()=>{answers[el.name]=Number(el.value);changed();});document.querySelectorAll('#questions textarea').forEach(el=>el.oninput=()=>{answers[el.dataset.question]=el.value;changed();});$('#submit').onclick=()=>close(false);progress();clearInterval(timer);timer=setInterval(tick,500);tick();}
function progress(){const n=quiz.questions.filter(q=>q.type==='sjt'?Number.isInteger(answers[q.id]):!!answers[q.id]?.trim()).length;$('#answered').textContent=n+' dari '+quiz.questions.length+' dijawab';$('#progress').style.width=n/quiz.questions.length*100+'%';}
function changed(){revision++;stashDraft();progress();clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),800);}
function save(){if(!active)return saving;clearTimeout(saveRetryTimer);const snapshot=structuredClone(answers),rev=revision,current=stage;message('#saveState','Menyimpan…',true);saving=saving.catch(()=>{}).then(async()=>{try{await api('save',{stage:current,answers:snapshot,revision:rev});message('#saveState','Tersimpan · '+new Date().toLocaleTimeString('id-ID'),true);}catch(e){message('#saveState','Belum tersimpan di server: '+e.message+' Jawaban tetap dicadangkan pada sesi browser ini.');if(active&&!closed)saveRetryTimer=setTimeout(()=>save(),3000);}});return saving;}
function tick(){if(!active)return;if(warningOpen){const remaining=Math.max(0,Math.ceil((warningDeadline-testNow())/1000));message('#warningCountdown','Konfirmasi dalam '+remaining+' detik, atau jawaban dikirim otomatis.');if(!remaining){warningAutoSubmit();return;}}if(quiz.expiresAt===null){$('#timer').textContent='Tanpa batas waktu';if($('#warningTimer'))$('#warningTimer').textContent='Tahap ini tanpa batas waktu.';return;}const secs=Math.max(0,Math.ceil((quiz.expiresAt-testNow())/1000));$('#timer').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0');if($('#warningTimer'))$('#warningTimer').textContent='Sisa waktu: '+$('#timer').textContent;if(!secs)close(true,'time_expired');}
async function close(violation,reason){if(closing||closed)return;const submittedStage=stage;if(!violation){const n=quiz.questions.filter(q=>q.type==='sjt'?Number.isInteger(answers[q.id]):!!answers[q.id]?.trim()).length;if(n!==quiz.questions.length)return message('#examMsg','Jawab seluruh pertanyaan sebelum mengirim.');}
 closing=true;active=false;warningOpen=false;warningDeadline=0;clearTimeout(warningTimeout);resuming=false;$('#securityWarning')?.remove();clearInterval(timer);clearTimeout(saveTimer);document.body.classList.remove('no-select');const payload={stage,answers:structuredClone(answers),type:reason};retryPayload={action:violation?'violation':'submit',payload};try{await saving;if((submittedStage==='leadership'||state.selfServeMaterials&&submittedStage==='comparison')&&!violation)loading('Jawaban sedang dianalisis…');await api(retryPayload.action,payload);closed=true;clearDraft();retryPayload=null;try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}await refresh();if(submittedStage==='pre')api('evaluate',{stage:submittedStage}).catch(e=>message('#profileMsg','Penilaian menunggu diproses: '+e.message));else if(state.stages[submittedStage]?.grading!=='complete')await grade(submittedStage);}catch(e){if(closed){committedRefreshError(e);return;}try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}$('#app').innerHTML='<section class="card hero"><h1>Jawaban belum terkirim.</h1><p id="retryMsg">'+esc(e.message)+'</p><p>Jawaban sesi ini masih ada di halaman. Jangan tutup halaman sebelum mencoba lagi.</p><button id="retry" class="btn blue">Coba kirim lagi</button></section>';$('#retry').onclick=async()=>{try{await api(retryPayload.action,retryPayload.payload);closed=true;clearDraft();retryPayload=null;await refresh();if(submittedStage==='pre')api('evaluate',{stage:submittedStage}).catch(e=>message('#profileMsg','Penilaian menunggu diproses: '+e.message));else if(state.stages[submittedStage]?.grading!=='complete')await grade(submittedStage);}catch(e){if(closed)committedRefreshError(e);else message('#retryMsg',e.message);}};}finally{closing=false;}}
const profileFields={interests:'Minat',talents:'Bakat',education:'Pendidikan',reading:'Bacaan',hobbies:'Hobi',learningInterests:'Hal yang ingin dipelajari',mbti:'MBTI',zodiac:'Zodiak',rolePreferences:'Catatan preferensi posisi',english:'English · ceritakan kemampuanmu bila ingin'};
function profile(){$('#app').innerHTML='<section class="card hero"><span class="tag">OPSIONAL · TANPA BATAS WAKTU · TIDAK DINILAI</span><h1>Profil personal.</h1>'+(state.stages.pre?.autoSubmitReason?'<p class="warning">Jawaban dikirim otomatis karena konfirmasi 10 detik terlewat.</p>':'')+'<p>Assessment sudah berakhir. Jawaban yang sempat tersimpan tetap dinilai. Kamu boleh mengisi profil ini atau melewatinya. Seluruh profil, termasuk English, tidak memengaruhi skor, ranking, kecocokan posisi maupun kelulusan.</p><div class="grid">'+Object.entries(profileFields).map(([k,v])=>'<div class="field"><label for="profile-'+k+'">'+esc(v)+'</label><textarea id="profile-'+k+'" maxlength="2000" class="profile-input">'+esc(state.profile?.[k]||'')+'</textarea></div>').join('')+'</div><div class="row"><button id="saveProfile" class="btn blue">Simpan &amp; lanjut</button><button id="skipProfile" class="btn">Lewati</button></div><p id="profileMsg"></p></section>';$('#saveProfile').onclick=()=>saveProfile(false);$('#skipProfile').onclick=()=>saveProfile(true);}
async function saveProfile(skip){const p=Object.fromEntries(Object.keys(profileFields).map(k=>[k,$('#profile-'+k).value]));try{await api('profile',{skip,profile:p});await refresh();if(!state.selfServeMaterials&&state.stages.pre)grade('pre');}catch(e){message('#profileMsg',e.message);}}
function dashboard(){if(state.selfServeMaterials)return selfServiceDashboard();const pre=state.stages.pre||{status:'not_started',grading:'complete'},terminated=pre.status==='terminated',roles=state.materialRoles||[];const done=roles.length&&roles.every(r=>state.stages['post:'+r.roleKey]?.status==='submitted'&&state.stages['post:'+r.roleKey]?.grading==='complete');
 $('#app').innerHTML='<section class="card hero"><span class="tag">'+(terminated?'PRE-ASSESSMENT BERAKHIR':pre.autoSubmitReason?'JAWABAN DIKIRIM OTOMATIS':done?'ASSESSMENT WEB SELESAI':'PROGRES ASSESSMENT')+'</span><h1>'+esc(state.candidateName)+'</h1><p>'+(terminated?'Pre-assessment diakhiri: '+esc(pre.terminationReason)+'. Jawaban yang tersimpan tetap dinilai. Profil personal dapat diisi tanpa batas waktu; materi tersedia setelah diterbitkan admin.':done?'Pre-assessment dan post-test sudah selesai. Seluruh jawaban tersimpan. Praktik dilakukan bersama tim di luar web.':state.materialsReleased?'Materi yang disepakati dengan admin tersedia di bawah. Baca materi. '+(state.postTestEnabled?'Post-test sudah dibuka oleh admin dan tanpa batas waktu.':'Post-test menunggu dibuka oleh admin.'):(pre.autoSubmitReason?'Jawaban dikirim otomatis karena konfirmasi 10 detik terlewat. ':'')+'Pre-assessment tersimpan. Hubungi admin untuk membahas nilai dan memilih materi pendalaman. Materi tersedia setelah pilihan diterbitkan admin.')+'</p>'+(state.accessCode?'<p class="small">Kode peserta: <b>'+esc(state.accessCode)+'</b> - gunakan kode yang sama sampai post-test.</p>':'')+'<p id="statusMsg"></p><button id="refresh" class="btn">Periksa status</button> '+(!state.comparisonEnabled&&pre.grading!=='complete'?'<button id="gradePre" class="btn blue">Proses penilaian</button>':'')+' <button id="editProfile" class="btn">Isi / ubah profil personal</button> <button id="logoutCandidate" class="btn">Keluar sesi</button>'+(roles.length?'<div class="spacer"></div><a class="btn blue" id="downloadPDF" href="/api?'+new URLSearchParams({action:'material-pdf',token})+'">Unduh PDF materi pilihan</a>':'')+'</section><div class="spacer"></div>'+(roles.length?'<div class="grid">'+roles.map(r=>{const post=state.stages['post:'+r.roleKey];const status=!post?'Belum dimulai':post.status==='terminated'?'Tes diakhiri':post.grading==='complete'?'Penilaian selesai':post.status==='submitted'?'Menunggu penilaian':'Sedang berjalan';return '<section class="card"><span class="tag">'+esc(r.team)+'</span><h2>'+esc(r.role)+'</h2><p class="small muted">Materi yang disepakati dengan admin</p><button class="btn" data-material="'+r.roleKey+'">Baca materi</button><div class="hr"></div><p>Post-test: '+status+'</p>'+(!post?(state.postTestEnabled?'<button class="btn blue" data-post="'+r.roleKey+'">Mulai post-test</button>':'<p class="small muted">Post-test belum dibuka oleh admin.</p>'):!state.postTestsLocked&&post.status==='submitted'&&post.grading!=='complete'?'<button class="btn" data-grade="post:'+r.roleKey+'">Proses nilai post-test</button>':'')+'</section>';}).join('')+'</div>':'');
 if(state.materialsHeld)$('#statusMsg').textContent='Materi belum dibagikan. Tunggu pengumuman penyelenggara.';
 const comparison=state.stages.comparison;if(state.comparisonEnabled||comparison){const section=document.createElement('section');section.className='card';section.innerHTML='<h2>Pendalaman pembanding</h2><p>10 kasus singkat yang sama untuk seluruh peserta, tanpa batas waktu. Bagian ini menjadi dasar pembandingan hasil kemampuan.</p>'+(!comparison?'<button class="btn blue" id="beginComparison">Mulai pendalaman pembanding</button>':comparison.grading==='complete'&&!comparison.comparable?'<p class="warning">Pendalaman belum lengkap ('+(comparison.answeredCount||0)+'/10). Hubungi admin untuk memulihkan kesempatan pengerjaan.</p>':comparison.grading==='complete'?'<p class="success">Jawaban dan penilaian pendalaman sudah tersimpan. Tunggu informasi penyelenggara.</p>':'<p>Jawaban sudah tersimpan. Penilaian '+esc(comparison.grading||'menunggu')+'.</p><button class="btn blue" id="gradeComparison">Proses penilaian pendalaman</button>')+'<p id="comparisonMsg"></p>';$('#app').prepend(section);if($('#beginComparison'))$('#beginComparison').onclick=comparisonGate;if($('#gradeComparison'))$('#gradeComparison').onclick=()=>grade('comparison');}
 $('#editProfile').onclick=()=>{if(!['submitted','terminated'].includes(pre.status)&&!['submitted','terminated'].includes(comparison?.status))return message('#statusMsg','Profil dapat diisi setelah assessment berakhir.');profile();};$('#refresh').onclick=()=>refresh().catch(e=>message('#statusMsg',e.message));$('#logoutCandidate').onclick=()=>{sessionStorage.removeItem('ccpw_token');token='';state=null;history.replaceState(null,'',location.pathname);landing();};if($('#gradePre'))$('#gradePre').onclick=()=>grade('pre');document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>materials(b.dataset.material));document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>stageGate('post:'+b.dataset.post));document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(b.dataset.grade));}
async function grade(s){if(gradingBusy)return;gradingBusy=true;autoGradingAttempted.add(s);message('#statusMsg','Jawaban sedang dianalisis…',true);message('#comparisonMsg','Jawaban sedang dianalisis…',true);message('#leadershipMsg','Jawaban sedang dianalisis…',true);document.querySelectorAll('[data-grade],#gradePre,#gradeComparison,#gradeLeadership').forEach(b=>b.disabled=true);try{await api('evaluate',{stage:s});await refresh();message('#statusMsg','Penilaian selesai.',true);}catch(e){message('#statusMsg',e.message+' Jawaban tetap tersimpan.');message('#comparisonMsg',e.message+' Jawaban tetap tersimpan. Klik Coba penilaian lagi.');message('#leadershipMsg',e.message+' Jawaban tetap tersimpan. Klik Coba penilaian lagi.');document.querySelectorAll('[data-grade],#gradePre,#gradeComparison,#gradeLeadership').forEach(b=>b.disabled=false);}finally{gradingBusy=false;}}
async function materials(role){try{const m=await api('materials',null,{role});$('#app').innerHTML='<section class="card hero"><span class="tag">MATERI PENDALAMAN</span><h1>'+esc(m.role.role)+'</h1><p>'+esc(m.module.focus)+'</p><h2>Prinsip bersama</h2>'+m.common.map(([h,t])=>'<h3>'+esc(h)+'</h3><p>'+esc(t)+'</p>').join('')+'<h2>Praktik posisi</h2><ol>'+m.module.steps.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol><h3>Contoh</h3><p>'+esc(m.module.case)+'</p><label class="option"><input id="read" type="checkbox"> Saya sudah membaca dan memahami materi.</label><div class="row"><button id="ack" class="btn blue">Simpan status membaca</button><button id="back" class="btn">Kembali</button></div><p id="materialMsg"></p></section>';$('#back').onclick=refresh;$('#ack').onclick=async()=>{if(!$('#read').checked)return message('#materialMsg','Centang setelah membaca materi.');try{await api('materials-read',{role});await refresh();}catch(e){message('#materialMsg',e.message);}};}catch(e){message('#statusMsg',e.message);}}
function stageGate(s){if(s==='leadership')return leadershipGate();if(s==='comparison')return comparisonGate();const role=s.split(':')[1];$('#app').innerHTML='<section class="card hero"><span class="tag">'+esc(state.roles[role].team)+'</span><h1>'+esc(label(s))+' · '+esc(state.roles[role].role)+'</h1><p>'+(s.startsWith('post:')?'6 soal · tanpa batas waktu. Gunakan prinsip dari materi pada kasus baru.':'1 tugas · 15 menit. Tuliskan hasil kerja sesuai brief. Ini practical berbasis teks; kualitas karya visual perlu validasi lanjutan bila relevan.')+'</p>'+rules()+'<div class="spacer"></div><div class="row"><button id="start" class="btn blue">Masuk fullscreen &amp; mulai</button><button id="back" class="btn">Kembali</button></div><p id="gateMsg"></p></section>';$('#start').onclick=()=>start(s);$('#back').onclick=refresh;}
const shouldWarn=()=>active&&!closed&&!closing&&!warningOpen&&!resuming&&testNow()>armed;
const isEditable=el=>!!el&&(el.matches?.('textarea,input:not([type=radio]):not([type=checkbox])')||el.isContentEditable);
const touchKeyboard=()=>Number(navigator.maxTouchPoints||0)>0&&isEditable(document.activeElement)&&!document.hidden;
function armWarningDeadline(deadline){warningDeadline=deadline;clearTimeout(warningTimeout);warningTimeout=setTimeout(warningAutoSubmit,Math.max(0,deadline-testNow()));}
async function warningAutoSubmit(){if(!active||!warningOpen||closing||closed)return;warningOpen=false;clearTimeout(warningTimeout);const current=stage;active=false;resuming=false;clearInterval(timer);clearTimeout(saveTimer);$('#securityWarning')?.remove();document.body.classList.remove('no-select');loading('Jawaban dikirim otomatis: konfirmasi 10 detik terlewat.');try{const logged=await warningRequest;if(!logged)await api('security-warning',{stage:current,answers:structuredClone(answers),revision,eventId:warningId,type:'security_warning'});await api('security-timeout',{stage:current});closed=true;clearDraft();try{if(document.fullscreenElement)await document.exitFullscreen();}catch{}await refresh();grade(current);}catch(e){if(closed){committedRefreshError(e);return;}$('#app').innerHTML='<section class="card hero"><h1>Konfirmasi terlewat.</h1><p>Jawaban dikunci. Sambungkan internet untuk menyelesaikan pengiriman otomatis.</p><button class="btn blue" id="retryTimeout">Coba kirim lagi</button><p id="timeoutMsg"></p></section>';message('#timeoutMsg',e.message);$('#retryTimeout').onclick=async()=>{try{await api('security-timeout',{stage:current});closed=true;clearDraft();await refresh();grade(current);}catch(e){if(closed)committedRefreshError(e);else message('#timeoutMsg',e.message);}};}}
function showSecurityWarning(reason,existing=null){if(!existing&&!shouldWarn())return;warningOpen=true;warningId=existing?.id||crypto.randomUUID();const data={stage,answers:structuredClone(answers),revision,eventId:warningId,type:reason};armWarningDeadline(existing?.deadlineAt||testNow()+10000);warningRequest=existing?Promise.resolve({ok:true,deadlineAt:existing.deadlineAt}):api('security-warning',data).catch(()=>null);
 const dialog=document.createElement('dialog');dialog.id='securityWarning';dialog.className='security-warning';dialog.setAttribute('aria-labelledby','warningTitle');dialog.innerHTML='<h2 id="warningTitle">Kecurangan terdeteksi</h2><p>Terdeteksi perpindahan tab/aplikasi atau tindakan yang dibatasi. Jawaban tetap tersimpan.</p><p id="warningCountdown" class="danger" aria-live="polite">Konfirmasi dalam 10 detik, atau jawaban dikirim otomatis.</p><p class="small" id="warningTimer">Timer tetap berjalan untuk tahap berbatas waktu. Pendalaman umum dan modul leader tanpa batas waktu.</p><button class="btn blue" id="continueTest">lanjutkan tes</button><p id="warningMsg" role="status"></p>';dialog.oncancel=e=>e.preventDefault();document.body.append(dialog);dialog.showModal();$('#continueTest').focus();
 // Keep the local ten-second bound; the server deadline prevents a reload or suspended tab bypass.
 $('#continueTest').onclick=async()=>{if(testNow()>=warningDeadline)return warningAutoSubmit();const btn=$('#continueTest');btn.disabled=true;resuming=true;clearTimeout(warningTimeout);warningOpen=false;try{const logged=await warningRequest;if(!logged)await api('security-warning',data);await api('security-resume',{stage,eventId:warningId});if(closed||closing||!active)return;armed=testNow()+500;warningId='';warningDeadline=0;dialog.close();dialog.remove();$('#submit')?.focus();if(document.hidden||(!document.hasFocus()&&!touchKeyboard())){resuming=false;armed=0;showSecurityWarning('tab_or_app_switch');}}catch(e){if(quiz.expiresAt!==null&&testNow()>quiz.expiresAt){await close(true,'time_expired');return;}if(testNow()>=warningDeadline){warningOpen=true;await warningAutoSubmit();return;}warningOpen=true;armWarningDeadline(warningDeadline);message('#warningMsg',e.message);btn.disabled=false;}finally{resuming=false;}};
 tick();
}
function blockAction(e,reason){if(!active)return;e.preventDefault();e.stopPropagation();showSecurityWarning(reason);}
for(const event of ['copy','cut','paste','contextmenu','dragstart','drop'])document.addEventListener(event,e=>blockAction(e,event+'_attempt'),{capture:true});
document.addEventListener('dragover',e=>{if(active)e.preventDefault();},{capture:true});
document.addEventListener('beforeinput',e=>{if(active&&['insertFromPaste','insertFromDrop','insertFromYank'].includes(e.inputType))blockAction(e,'clipboard_attempt');},{capture:true});
document.addEventListener('keydown',e=>{if(!active)return;const k=e.key.toLowerCase();const modifier=e.ctrlKey||e.metaKey;if(e.key==='F12'||e.key==='PrintScreen'||(modifier&&['c','v','x','p','s','u','r','t','n','w','l','k','o','tab','j','i'].includes(k))||(e.altKey&&['tab','arrowleft','arrowright','f4'].includes(k))||(['F5','F6'].includes(e.key)))blockAction(e,'restricted_shortcut');},{capture:true});
document.addEventListener('click',e=>{const link=e.target.closest?.('a');if(active&&link&&(link.target==='_blank'||e.ctrlKey||e.metaKey))blockAction(e,'new_window_attempt');},{capture:true});
document.addEventListener('auxclick',e=>{if(active)blockAction(e,'new_window_attempt');},{capture:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&shouldWarn())showSecurityWarning('tab_or_app_switch');else if(!document.hidden&&warningOpen)tick();});
window.addEventListener('blur',()=>{if(shouldWarn())setTimeout(()=>{if(shouldWarn()&&!document.hasFocus()&&!touchKeyboard())showSecurityWarning('window_focus_lost');},180);});
// Fullscreen exit alone is allowed, including on-screen keyboard transitions on iPad.
window.addEventListener('pagehide',()=>{if(active&&!closed&&!closing)navigator.sendBeacon('/api?action=security-warning',new Blob([JSON.stringify({token,stage,answers,revision,eventId:warningId||crypto.randomUUID(),type:'page_exit'})],{type:'application/json'}));});

function comparisonGate(){const selected=state.preferences||[];$('#app').innerHTML='<section class="card hero"><span class="tag">10 KASUS · TANPA BATAS WAKTU</span><h1>Pendalaman pembanding</h1><p>Seluruh peserta mengerjakan kasus yang sama. Gunakan pertimbanganmu sendiri, jawab singkat dan spesifik; poin-poin diperbolehkan. Tidak ada bonus karena menjawab lebih cepat. Bagian ini dikerjakan sebelum materi pembelajaran dibagikan.</p><div class="grid"><div class="field"><label for="comparisonName">NAMA</label><input id="comparisonName" maxlength="150" value="'+esc(state.candidateName)+'" '+(state.contact?'readonly':'')+'></div><div class="field"><label for="comparisonContact">EMAIL / NOMOR WA</label><input id="comparisonContact" maxlength="200" value="'+esc(state.contact||'')+'" '+(state.contact?'readonly':'')+'></div></div><h3>Posisi yang diminati</h3>'+Object.entries(state.roles).map(([k,r])=>'<label class="option"><input name="comparisonPreference" type="checkbox" value="'+k+'" '+(selected.includes(k)?'checked':'')+' '+(state.contact?'disabled':'')+'>'+esc(r.team+' · '+r.role)+'</label>').join('')+rules()+'<label class="option"><input id="comparisonConsent" type="checkbox"> Saya memahami aturan dan setuju jawaban kerja dinilai dengan AI berdasarkan rubrik. Profil personal tidak ikut dinilai.</label><div class="row"><button id="start" class="btn blue">Mulai pendalaman</button><button id="back" class="btn">Kembali</button></div><p id="gateMsg"></p></section>';$('#start').onclick=()=>start('comparison');$('#back').onclick=refresh;}

function leadershipGate(){$('#app').innerHTML='<section class="card hero"><span class="tag">LEADER PW · 4 KASUS · TANPA BATAS WAKTU</span><h1>Assessment kepemimpinan</h1><p>Bagian tambahan untuk pelamar Leader PW. Perkiraan pengerjaan 15–20 menit; tidak ada bonus kecepatan. Gunakan pertimbanganmu sendiri dan jawab spesifik. Poin-poin diperbolehkan.</p>'+rules()+'<label class="option"><input id="leaderConsent" type="checkbox"> Saya memahami aturan dan setuju jawaban dinilai dengan AI berdasarkan rubrik.</label><div class="row"><button id="start" class="btn blue">Mulai modul leader</button><button id="back" class="btn">Kembali</button></div><p id="gateMsg"></p></section>';$('#start').onclick=()=>start('leadership');$('#back').onclick=refresh;}
function leadershipPanel(){const s=state.stages.leadership;let html='<section class="card"><h2>Assessment Leader PW</h2><p>Empat kasus kepemimpinan, tanpa batas waktu. Selesaikan bagian ini sebelum memilih materi.</p>';
 if(!s)html+='<button id="beginLeadership" class="btn blue">Lanjut ke modul leader</button>';
 else if(state.leadershipReady)html+='<p class="success">Jawaban dan penilaian modul leader sudah tersimpan.</p>';
 else if(['submitted','terminated'].includes(s.status)&&(s.answeredCount||0)<4)html+='<p class="warning">Jawaban tersimpan: '+(s.answeredCount||0)+'/4. Jawaban sebelumnya terkunci; lengkapi soal yang tersisa.</p><button id="resumeLeadership" class="btn blue">Lanjutkan soal leader yang belum selesai</button>';
 else html+='<p>'+(s.grading==='running'?'Sedang dianalisis…':'Jawaban tersimpan. Penilaian belum selesai.')+'</p><button id="gradeLeadership" class="btn blue">Coba penilaian lagi</button>';
 return html+'<p id="leadershipMsg" role="status"></p></section>';}
function selfServiceDashboard(){
 clearTimeout(gradingPoll);const c=state.stages.comparison;const complete=c?.comparable&&c.grading==='complete';
 let content='<section class="card hero"><span class="tag">PENDALAMAN &amp; MATERI</span><h1>'+esc(state.candidateName)+'</h1><p class="small">Kode peserta: <b>'+esc(state.accessCode)+'</b></p><p>Lengkapi 10 kasus, lihat pemetaan posisi, lalu pilih materi yang ingin kamu lanjutkan.</p><div class="row"><button id="refresh" class="btn">Periksa status</button><button id="editProfile" class="btn">Profil personal</button><button id="logoutCandidate" class="btn">Keluar sesi</button></div><p id="statusMsg"></p></section><section class="card"><h2>Pendalaman pembanding</h2>';
 if(!c)content+='<p>10 kasus singkat, tanpa batas waktu. Jawab dengan pertimbanganmu sendiri; poin-poin diperbolehkan.</p>'+(state.comparisonEnabled?'<button id="beginComparison" class="btn blue">Mulai pendalaman pembanding</button>':'<p>Pendalaman belum dibuka oleh penyelenggara.</p>');
 else if(!complete&&(c.answeredCount||0)<10&&['submitted','terminated'].includes(c.status))content+='<p class="warning">Jawaban tersimpan: '+(c.answeredCount||0)+'/10. Lengkapi soal yang tersisa sebelum memilih materi. Jawaban sebelumnya tetap terkunci.</p><button id="resumeComparison" class="btn blue">Lanjutkan soal yang belum selesai</button>';
 else if(complete)content+='<p class="success">Jawaban dan penilaian pendalaman sudah tersimpan.</p>';
 else content+='<p>Jawaban tersimpan. '+(c.grading==='running'?'Sedang dianalisis…':'Penilaian sedang diproses. Jika proses belum selesai, coba lagi tanpa mengulang tes.')+'</p><button id="gradeComparison" class="btn blue">Coba penilaian lagi</button>';
 content+='<p id="comparisonMsg" role="status"></p></section>';
 if(complete&&state.leaderTrack)content+=leadershipPanel();
 if(complete&&(!state.leaderTrack||state.leadershipReady)&&state.roleSelection){content+='<section class="card"><h2>Pilih posisi yang ingin kamu lanjutkan</h2><p>Skor kecocokan posisi berasal dari jawaban pendalaman. Skor bukan peluang kelulusan. Centangan awal memuat pilihan awalmu dan dua rekomendasi sistem; kamu bebas mengubahnya.</p><div class="grid">'+state.roleSelection.choices.map(f=>'<label class="option"><input type="checkbox" name="candidateMaterialRole" value="'+f.roleKey+'" '+(f.selected?'checked':'')+'><span><b>'+esc(f.team+' · '+f.role)+'</b><br>Skor kecocokan: '+(f.score===null?'Belum terukur':f.score+'/100')+'<br><span class="small">'+(f.applied?'Pilihan awalmu · ':'')+(f.recommended?'Rekomendasi sistem':'')+'</span><br><span class="small muted">'+esc(f.reason)+'</span></span></label>').join('')+'</div><div class="spacer"></div><button id="confirmMaterialRoles" class="btn blue" '+(state.materialsHeld?'disabled':'')+'>Konfirmasi pilihan &amp; siapkan PDF</button><p id="selectionMsg" role="status"></p>'+(state.materialsHeld?'<p class="warning">Distribusi materi sedang ditahan oleh penyelenggara.</p>':'')+'</section>';}
 if(state.download&&state.materialsReleased)content+='<section class="card"><h2>Materi pilihanmu</h2><p>PDF memuat prinsip bersama dan modul posisi yang kamu konfirmasi.</p><a id="downloadPDF" class="btn blue" href="'+esc(state.download.url)+'">Unduh PDF materi pilihan</a><div class="spacer"></div><img class="material-qr" alt="QR unduh PDF materi pilihan" src="data:image/svg+xml;charset=utf-8,'+encodeURIComponent(state.download.qr)+'"></section><div class="grid">'+state.materialRoles.map(r=>{const post=state.stages['post:'+r.roleKey];return '<section class="card"><h3>'+esc(r.team+' · '+r.role)+'</h3><button class="btn" data-material="'+r.roleKey+'">Baca materi</button>'+(post?'<p>Post-test: '+esc(post.grading==='complete'?'Penilaian selesai':post.status)+'</p>'+(!state.postTestsLocked&&post.status==='submitted'&&post.grading!=='complete'?'<button class="btn" data-grade="post:'+r.roleKey+'">Proses nilai post-test</button>':''):state.postTestEnabled?'<button class="btn blue" data-post="'+r.roleKey+'">Mulai post-test</button>':'<p class="small muted">Post-test belum dibuka oleh admin.</p>')+'</section>';}).join('')+'</div>';
 $('#app').innerHTML=content;
 $('#refresh').onclick=()=>refresh().catch(e=>message('#statusMsg',e.message));$('#editProfile').onclick=()=>{if(!['submitted','terminated'].includes(c?.status)&&!['submitted','terminated'].includes(state.stages.pre?.status))return message('#statusMsg','Profil dapat diisi setelah assessment dikirim.');profile();};$('#logoutCandidate').onclick=()=>{sessionStorage.removeItem('ccpw_token');token='';state=null;history.replaceState(null,'',location.pathname);landing();};
 if($('#beginComparison'))$('#beginComparison').onclick=comparisonGate;
 if($('#beginLeadership'))$('#beginLeadership').onclick=leadershipGate;
 if($('#gradeLeadership'))$('#gradeLeadership').onclick=()=>grade('leadership');
 if($('#resumeLeadership'))$('#resumeLeadership').onclick=async()=>{const btn=$('#resumeLeadership');btn.disabled=true;try{await api('leadership-resume',{});await refresh();}catch(e){message('#leadershipMsg',e.message);btn.disabled=false;}};
 if($('#resumeComparison'))$('#resumeComparison').onclick=async()=>{const btn=$('#resumeComparison');btn.disabled=true;try{await api('comparison-resume',{});await refresh();}catch(e){message('#comparisonMsg',e.message);btn.disabled=false;}};
 if($('#gradeComparison'))$('#gradeComparison').onclick=()=>grade('comparison');
 if($('#confirmMaterialRoles'))$('#confirmMaterialRoles').onclick=async()=>{const btn=$('#confirmMaterialRoles');btn.disabled=true;try{const roles=[...document.querySelectorAll('[name=candidateMaterialRole]:checked')].map(el=>el.value);if(!roles.length)throw new Error('Pilih minimal satu posisi.');await api('candidate-materials',{roles});await refresh();message('#selectionMsg','Pilihan tersimpan. PDF dan QR tersedia di bawah.',true);}catch(e){message('#selectionMsg',e.message);btn.disabled=false;}};
 document.querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>materials(b.dataset.material));document.querySelectorAll('[data-post]').forEach(b=>b.onclick=()=>stageGate('post:'+b.dataset.post));document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(b.dataset.grade));
 const leader=state.stages.leadership;if(state.leaderTrack&&!state.leadershipReady&&leader&&['submitted','terminated'].includes(leader.status)&&leader.answeredCount===4){if(leader.grading==='running')gradingPoll=setTimeout(()=>refresh().catch(e=>message('#leadershipMsg',e.message)),4000);else if(!autoGradingAttempted.has('leadership')){autoGradingAttempted.add('leadership');setTimeout(()=>grade('leadership'),0);}}
 if(c&&!complete&&['submitted','terminated'].includes(c.status)&&(c.answeredCount||0)===10){if(c.grading==='running')gradingPoll=setTimeout(()=>refresh().catch(e=>message('#comparisonMsg',e.message)),4000);else if(!autoGradingAttempted.has('comparison')){autoGradingAttempted.add('comparison');setTimeout(()=>grade('comparison'),0);}}
}

window.addEventListener('online',()=>{if(active&&!closed)save();});
if(token){loading();refresh().catch(e=>{landing();message('#landingMsg',e.message);});}else landing();
