const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const time=value=>new Date(value).toLocaleTimeString('id-ID',{timeZone:'Asia/Jakarta',hour:'2-digit',minute:'2-digit',hour12:false});
const date=value=>new Date(value).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta',weekday:'long',day:'numeric',month:'long',year:'numeric'});
let requestNumber=0;
function renderInfo(data){const result=$('#infoResult'),schedule=data.schedule;result.hidden=false;
 const modules='<div class="module-list">'+data.modules.map(m=>'<span class="tag">'+esc(m.label)+'</span>').join('')+'</div>';
 let html='<div class="spacer"></div><section class="card info-card"><h1>'+esc(data.candidateName)+'</h1><p>'+data.modules.length+' modul · '+data.testMinutes+' menit tes + '+data.turnoverMinutes+' menit pergantian per modul.</p>'+modules;
 if(!schedule.published){html+='<div class="notice"><b>Jadwal belum diterbitkan.</b><p>Kloter, jam, komputer, dan urutan modul akan muncul di sini setelah jadwal final tersedia. Periksa kembali dengan kode yang sama.</p></div>'+(data.modules.length?'':'<p>Daftar modul pilihanmu belum tersedia. Hubungi penyelenggara.</p>');}
 else{html+=(schedule.location?'<p><b>Lokasi:</b> '+esc(schedule.location)+'</p>':'')+'<div class="schedule-list">'+schedule.slots.map((s,i)=>'<article class="schedule-slot"><span class="tag">'+esc(s.cohort)+'</span><h3>'+(i+1)+'. '+esc(s.label)+'</h3><p>'+esc(date(s.startAt))+'</p><div class="slot-time">'+esc(time(s.startAt))+'–'+esc(time(s.endAt))+' WIB</div><div class="schedule-meta"><div><span class="small muted">Komputer</span><strong>'+s.computer+'</strong></div><div><span class="small muted">Menit dalam kloter</span><strong>'+s.startMinute+'–'+s.endMinute+'</strong></div><div><span class="small muted">Kloter dimulai</span><strong>'+esc(time(s.cohortStartAt))+' WIB</strong></div></div><p class="small">Pergantian/login: '+esc(time(s.endAt))+'–'+esc(time(s.turnoverEndAt))+' WIB (menit '+s.endMinute+'–'+(s.startMinute+10)+').</p></article>').join('')+'</div><p class="small">Siapkan kode sebelum giliranmu. Timer 9 menit dimulai saat menekan Mulai post-test. Ikuti arahan pengawas untuk pergantian komputer.</p>';}
 result.innerHTML=html+'</section>';
}
$('#infoCode').addEventListener('input',()=>{requestNumber++;$('#infoResult').hidden=true;$('#infoStatus').textContent='';});
$('#infoForm').addEventListener('submit',async event=>{event.preventDefault();const code=$('#infoCode').value.trim(),request=++requestNumber;if(!/^[1-9]\d{5}$/.test(code)){$('#infoStatus').textContent='Masukkan kode peserta 6 digit.';return;}
 $('#infoSubmit').disabled=true;$('#infoResult').hidden=true;$('#infoStatus').textContent='Memuat jadwal…';try{const response=await fetch('/api?action=post-info',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code}),cache:'no-store'});const data=await response.json();if(request!==requestNumber)return;if(!response.ok)throw new Error(data.error||'Jadwal belum dapat dimuat.');renderInfo(data);$('#infoStatus').textContent='';}catch(error){if(request===requestNumber)$('#infoStatus').textContent=error.message||'Koneksi bermasalah. Coba lagi.';}finally{$('#infoSubmit').disabled=false;}});
