export const LEADERSHIP_VERSION='leader-pw-v1-2026-10-02';
export const LEADER_CAPS={delegation:'Pembagian tanggung jawab',monitoring:'Pemantauan hasil',diagnosis:'Diagnosis hambatan kerja',coaching:'Pembinaan dan evaluasi',fairness:'Penilaian yang adil',conflict:'Penyelesaian konflik',prioritization:'Prioritas berbasis risiko',escalation:'Eskalasi dan verifikasi keamanan'};
const tasks=[
 ['delegation','monitoring','Besok tim harus menjalankan training 20 peserta dan pembagian perlengkapan 40 karyawan. Ada empat anggota: satu berpengalaman dalam training, satu teliti mengurus barang, satu baru, dan satu menguasai keduanya tetapi sedang menyelesaikan pekerjaan mendesak. Data peserta belum final dan sebagian barang belum datang. Sebagai leader, susun pembagian kerja, batas keputusan anggota, titik pemeriksaan, dan tindakan jika persiapan tertinggal.',
 'Membagi pekerjaan sesuai kemampuan dan kapasitas, menetapkan satu penanggung jawab untuk tiap hasil, mendampingi anggota baru, serta menjelaskan batas kewenangan dan ketergantungan pekerjaan tanpa membebankan semuanya kepada anggota paling mampu.',
 'Menetapkan hasil siap yang dapat diperiksa, tenggat dan titik pembaruan sebelum acara, bukti status peserta/barang, serta alternatif atau eskalasi jika ada hambatan.'],
 ['diagnosis','coaching','Seorang anggota terlambat menyerahkan tiga laporan. Dua anggota lain ingin tugasnya langsung dipindahkan. Anggota tersebut mengatakan permintaan antarunit berubah dan prioritas tidak jelas. Kamu belum melihat alur kerjanya. Tuliskan langkah percakapan pertama, informasi yang kamu periksa, kesepakatan perbaikan, dan cara menentukan apakah perbaikan berhasil.',
 'Memeriksa contoh keterlambatan, beban kerja, standar, perubahan permintaan dan keputusan prioritas; mendengar penjelasan secara privat serta memisahkan fakta dari label sebelum menyimpulkan penyebab.',
 'Menyepakati tindakan yang sesuai penyebab, dukungan atau latihan yang spesifik, pemilik tindakan, indikator hasil dan waktu evaluasi; menjelaskan tindak lanjut yang proporsional bila masalah tetap berulang.'],
 ['fairness','conflict','Dua anggota saling menyalahkan setelah kegiatan gagal. Anggota A adalah teman dekatmu dan terlihat sering membantu. Anggota B lebih pendiam, tetapi mengaku sudah mengingatkan risiko melalui pesan. Ada keluhan bahwa pembagian tugasmu tidak jelas. Atasan meminta penilaian kontribusi hari ini. Bagaimana kamu menangani konflik, mengecek bukti, dan menyampaikan penilaian sementara?',
 'Menggunakan tugas yang disepakati, bukti kerja dan komunikasi kedua pihak dengan standar yang sama; mengakui kedekatan serta kemungkinan kesalahan pembagian tugas leader, dan menyatakan batas informasi serta status sementara penilaian.',
 'Menghentikan saling menyalahkan, mendengar masing-masing pihak, memeriksa kronologi dan tanggung jawab, lalu menyepakati perbaikan pembagian kerja dan tindak lanjut tanpa mempermalukan atau memihak karena kedekatan.'],
 ['prioritization','escalation','Training dimulai 30 menit lagi. Ruangannya memiliki kabel rusak di dekat lantai basah. Pada saat yang sama atasan meminta daftar lengkap nomor telepon karyawan segera dikirim ke vendor, tetapi tujuan dan izinnya belum jelas. Ada tenggat laporan bulanan sore ini. Kamu hanya memiliki dua anggota tersedia. Tentukan urutan tindakan, keputusan yang bisa kamu ambil, pihak yang perlu dilibatkan, dan syarat melanjutkan kegiatan atau pengiriman data.',
 'Memprioritaskan bahaya keselamatan segera, membagi penanganan sesuai kapasitas dan kewenangan, menunda atau mencari alternatif ruang; menahan pengiriman data yang belum jelas dasarnya sambil mengomunikasikan dampak terhadap tenggat laporan.',
 'Melibatkan penanggung jawab fasilitas/keamanan dan pemilik persetujuan data, membatasi area berbahaya tanpa melakukan perbaikan listrik di luar kompetensi, memverifikasi ruang aman sebelum dipakai, serta membatasi data pada tujuan/kebutuhan/izin yang terkonfirmasi dan mencatat keputusan.']
];
export const LEADERSHIP=tasks.map(([a,b,q,x,y],i)=>({id:'ldr0'+(i+1),type:'essay',role:null,q:q+' Jawab spesifik; poin-poin diperbolehkan.',maxLength:2400,criteria:[{cap:a,description:x},{cap:b,description:y}]}));
export function leadershipReady(r){if(!r.leaderTrack?.enabled)return true;const s=r.stages?.leadership;return ['submitted','terminated'].includes(s?.status)&&s.grading?.status==='complete'&&s.result?.comparable===true;}
export function postLeadershipReady(r){return leadershipReady(r)||r.postTestException?.leadershipPending===true;}
export function aggregateLeadership(answers,grades=[]){
 const capability=[],pending=[];let answeredCount=0;
 for(const q of LEADERSHIP){const answered=!!answers[q.id]?.trim();if(answered)answeredCount++;const g=grades.find(g=>g.id===q.id);if(answered&&!g)pending.push(q.id);
 for(const criterion of q.criteria){const c=answered?g?.criteria.find(c=>c.cap===criterion.cap):null;if(answered&&g&&!c)pending.push(q.id);capability.push({key:criterion.cap,label:LEADER_CAPS[criterion.cap],score:c?c.score/4*100:null,observations:c?1:0,essayObservations:c?1:0,possible:1,coverage:c?100:0,lowConfidence:c&&(c.confidence<.65||g.flags?.length)?1:0});}}
 const observed=capability.filter(c=>c.score!==null),complete=pending.length===0,comparable=answeredCount===4&&complete;
 const observedScore=observed.length?Math.round(observed.reduce((a,c)=>a+c.score,0)/observed.length):null;
 return{scoringVersion:LEADERSHIP_VERSION,capability,pending:[...new Set(pending)],answeredCount,totalQuestions:4,completion:answeredCount*25,complete,comparable,leadershipScore:comparable?observedScore:null,observedScore,reviewRequired:capability.some(c=>c.lowConfidence),policy:{equalCaseWeights:true,missing:'unmeasured',calibrated:false},roleFits:[]};
}
