export const POST_BANK_VERSION='role-advanced-20261008';
// Application/analysis cases: four plausible actions with explicit trade-offs.
// Scores are item-specific evidence; options are shuffled by the presentation layer.
export function advancedPostBank(sjt,essay){
 const mc=(r,n,q,caps,opts)=>{const rows=opts.map(([text,a,b])=>[text,{[caps[0]]:a,[caps[1]]:b}]);const shift=(n+[...r].reduce((sum,c)=>sum+c.charCodeAt(0),0))%4;return sjt(`${r}-post${n}`,r,q,[...rows.slice(shift),...rows.slice(0,shift)]);};
 const es=(r,n,q,c)=>essay(`${r}-post${n}`,q+' Jawab ringkas dalam poin; tidak perlu istilah teknis atau pengalaman pribadi.',c,r);
 return {
 'cc-strategist':[
 mc('cc-strategist',1,'Target bulan ini: memperoleh 30 pelamar yang memenuhi kualifikasi. Opsi A: event Rp18 juta, perkiraan 150 kontak tanpa data kualitas. Opsi B: empat sesi komunitas Rp12 juta, perkiraan 50 kontak; pilot sebelumnya menghasilkan 10 kontak dan 4 pelamar memenuhi kualifikasi. Sisa anggaran harus menutup evaluasi. Rekomendasi awal paling kuat?', ['strategy','documentation'],[
 ['Pilih pilot B dengan batas biaya dan ukur konversi ke pelamar memenuhi kualifikasi sebelum memperluas.',4,4],['Uji A dan B dengan anggaran dibagi, lalu bandingkan biaya per kontak agar kedua opsi mendapat kesempatan.',2,3],['Pilih A karena jangkauan terbesar memberi peluang paling besar untuk memenuhi target dalam satu bulan.',1,2],['Pilih B karena bukti awal lebih relevan, lalu alokasikan seluruh sisa biaya untuk menambah sesi.',3,2]]),
 mc('cc-strategist',2,'Kontrak sponsorship berakhir Jumat. Partner meminta perpanjangan hari ini; draft baru menambah kewajiban eksklusivitas yang belum direview. Event berlangsung Sabtu, dan pemilik keputusan bisnis sedang di luar kota. Apa paket eskalasi terbaik?', ['risk','ownership'],[
 ['Kirim perbedaan klausul, dampak event, opsi transisi terbatas dan batas waktu keputusan ke owner serta penasihat hukum.',4,4],['Minta penasihat hukum meninjau draft dahulu; setelah ada hasil, hubungi owner untuk keputusan bisnis.',3,2],['Negosiasikan biaya tambahan untuk mengimbangi eksklusivitas lalu ajukan draft hasil negosiasi kepada owner.',2,3],['Usulkan perpanjangan dengan syarat klausul akan dibahas kembali seusai event agar jadwal tetap berjalan.',1,2]]),
 mc('cc-strategist',3,'Dashboard CSR menunjukkan 800 peserta hadir dan 95% puas. Tujuan program adalah meningkatkan keterampilan; belum ada bukti praktik atau tindak lanjut. Sponsor meminta klaim program berhasil untuk proposal tahun depan. Bukti tambahan paling menentukan?', ['strategy','risk'],[
 ['Sampel tugas sebelum–sesudah dan bukti penerapan satu minggu, dengan batasan sampel dijelaskan dalam proposal.',4,4],['Wawancara peserta tentang manfaat program dan dokumentasi kehadiran untuk melengkapi data kepuasan.',2,3],['Bandingkan kepuasan dan kehadiran dengan program tahun lalu untuk menunjukkan peningkatan yang konsisten.',1,2],['Observasi tugas sesudah sesi dengan rubrik yang sama, sambil menyatakan perubahan belum dapat dipastikan tanpa baseline.',3,4]]),
 mc('cc-strategist',4,'Dua unit memakai nama brand berbeda pada kontrak dan materi publik. Kampanye mulai besok; mengganti semua materi perlu tiga hari. Nama resmi sudah dipastikan, tetapi beberapa partner belum menyetujui perubahan dokumen. Prioritas hari ini?', ['strategy','ownership'],[
 ['Pisahkan koreksi publik berisiko tinggi dari perubahan dokumen; tetapkan owner, approval dan batas waktu untuk masing-masing.',4,4],['Tunda seluruh kampanye sampai dokumen partner dan semua materi memakai nama yang sama.',2,3],['Perbaiki kanal milik perusahaan dahulu dan masukkan dokumen partner ke daftar tindak lanjut tanpa menghambat kampanye.',3,2],['Pertahankan versi yang sudah beredar sampai satu tanggal pergantian bersama disepakati semua partner.',1,2]]),
 es('cc-strategist',5,'Dana Rp15 juta harus memilih satu program: konten rutin dengan data konversi lama yang melemah, atau kolaborasi komunitas baru tanpa baseline. Targetnya 20 kandidat memenuhi kualifikasi dalam enam minggu. Buat memo singkat: pilihan atau pilot, alasan dan asumsi, batas biaya/risiko, pihak pemberi keputusan, serta kondisi yang membuatmu mengubah pilihan.',[['strategy','Memilih opsi/pilot berdasarkan target kandidat berkualifikasi, membedakan bukti lama dan ketidakpastian opsi baru serta menjelaskan trade-off.'],['risk','Menetapkan batas biaya/komitmen dan kondisi menghentikan atau mengubah program sebelum risiko meluas.'],['documentation','Mencatat asumsi dan bukti yang perlu diverifikasi; tidak mengarang tingkat konversi yang tidak tersedia.'],['ownership','Menetapkan pemilik keputusan dan tenggat evaluasi realistis dalam enam minggu.']]),
 es('cc-strategist',6,'Setelah satu minggu kampanye, jangkauan naik dua kali, tetapi pelamar memenuhi kualifikasi tetap 3 orang dan biaya sudah 40% dari anggaran enam minggu. Tentukan dua ukuran keputusan, data pembanding yang dibutuhkan, tindakan minggu kedua, dan syarat lanjut/ubah/hentikan.',[['strategy','Membedakan jangkauan dari pencapaian target dan memakai konversi/kualitas serta biaya sebagai dasar keputusan.'],['documentation','Menentukan sumber/segmentasi atau baseline untuk memeriksa penyebab, tanpa menyimpulkan dari jangkauan saja.'],['risk','Memberi batas belanja dan kriteria keputusan yang terhubung pada sisa waktu serta anggaran.'],['ownership','Menetapkan penanggung jawab, waktu review dan tindakan konkret setelah hasil evaluasi.']])],
 'cc-creative':[
 mc('cc-creative',1,'Poster registrasi akan dicetak A3 dan tampil sebagai layar ponsel. Pada proof A3 judul terbaca, tetapi syarat dan QR gagal dibaca dari jarak penggunaan; versi ponsel terlalu padat. Produksi harus dikirim satu jam lagi. Prioritas revisi?', ['creative','operations'],[
 ['Pisahkan layout menurut kanal, pertahankan hierarki brand, uji syarat penting dan QR pada ukuran/jarak nyata sebelum export.',4,4],['Besarkan seluruh teks dan QR pada layout yang sama agar kedua kanal tetap memakai komposisi identik.',2,3],['Pindahkan semua syarat ke QR lalu perbesar judul agar materi utama lebih sederhana di kedua kanal.',1,3],['Prioritaskan QR dan syarat wajib pada cetak, lalu buat turunan ponsel dari versi tersebut dengan pemeriksaan ulang.',3,3]]),
 mc('cc-creative',2,'Tiga unit membutuhkan signage dengan ukuran berbeda. Satu unit meminta warna di luar palette agar menonjol; acara memakai satu identitas bersama. Owner hanya sempat meninjau satu proof. Paket review paling membantu keputusan?', ['creative','strategy'],[
 ['Tampilkan komponen wajib dan variasi yang diizinkan dalam satu proof tiga ukuran, beserta dampak kontras dan keterbacaan.',4,4],['Pilih satu ukuran sebagai master dan minta approval gaya; adaptasi dua ukuran lain setelahnya.',3,2],['Tampilkan tiga gaya terpisah agar owner bisa memilih mana yang paling mewakili setiap unit.',2,2],['Gunakan warna yang diminta pada ketiga unit agar seluruh signage kembali konsisten.',1,1]]),
 mc('cc-creative',3,'Vendor meminta PDF cetak; folder berisi final-v3 dan final-v4. PIC sudah menyetujui v3, tetapi v4 memperbaiki tanggal dan memakai foto pengganti yang lisensinya belum jelas. Apa yang dikirim?', ['documentation','creative'],[
 ['Susun satu versi dengan tanggal benar dan aset berizin, verifikasi perubahan wajib, lalu ekspor serta tandai sumber final.',4,4],['Kirim v3 yang telah disetujui, disertai instruksi tertulis agar vendor mengoreksi tanggal saat produksi.',2,2],['Kirim v4 karena informasinya paling baru, sambil meminta pemasok melengkapi bukti lisensi foto.',1,3],['Koreksi tanggal pada v3 dan minta konfirmasi cepat PIC; foto pengganti ditunda sampai hak pakainya jelas.',3,4]]),
 mc('cc-creative',4,'Cetakan 100 banner menunjukkan warna menyimpang. Logo dan kontras masih terbaca; 10 banner panggung paling terlihat, 90 lainnya di area sekunder. Cetak ulang semua terlambat, 10 banner dapat selesai tepat waktu. Keputusan QC terbaik?', ['creative','operations'],[
 ['Bandingkan proof dengan toleransi brand, ajukan cetak ulang titik utama bila perlu, dan dokumentasikan penerimaan terbatas sisanya.',4,4],['Cetak ulang 10 banner panggung lalu gunakan sisanya karena perbedaan warna kurang terlihat di area sekunder.',3,3],['Terima seluruh banner karena informasi dan logo masih terbaca; evaluasi warna dengan vendor setelah acara.',2,4],['Tolak seluruh banner agar standar konsisten, lalu gunakan materi digital sebagai pengganti semua titik.',3,1]]),
 es('cc-creative',5,'Buat keputusan desain untuk signage registrasi: pintu masuk dibaca dari 3 meter, meja registrasi dari dekat, dan story ponsel. Informasi wajib: nama acara, arah/urutan registrasi, jam, dan syarat peserta. Sebutkan hierarki setiap kanal, elemen brand yang tetap, dua pemeriksaan proof, dan paket file yang diserahkan ke vendor/PIC. Tidak perlu menggambar.',[['creative','Membedakan hierarki dan keterbacaan menurut jarak/kanal sambil menjaga informasi wajib serta konsistensi brand.'],['strategy','Menghubungkan keputusan layout dengan tugas pengguna mencari lokasi/mengikuti registrasi, bukan selera visual semata.'],['operations','Menetapkan proof ukuran nyata dan pemeriksaan informasi/QR atau arah sebelum produksi.'],['documentation','Menentukan sumber editable, export per kanal, spesifikasi dan identitas versi final yang jelas.']]),
 es('cc-creative',6,'Seminggu setelah template baru dipakai, 2 dari 6 unit masih mengirim tanggal lama dan 3 unit mengubah ukuran logo. Tentukan cara memeriksa sumber kesalahan, perbaikan template/handover, bukti uji oleh pengguna, dan siapa yang menyetujui versi pengganti.',[['creative','Menentukan koreksi aturan logo dan struktur template agar penggunaan konsisten serta dapat dilakukan oleh unit.'],['documentation','Menelusuri sumber/versi yang dipakai dan mengganti atau mengarsipkan turunan lama secara terkontrol.'],['operations','Mengusulkan uji membuat/export materi oleh pengguna nyata, dengan pemeriksaan tanggal serta ukuran logo.'],['strategy','Membedakan masalah desain template dari masalah distribusi/pemahaman dan menetapkan approval yang sesuai.']])],
 'cc-publicist':[
 mc('cc-publicist',1,'Video antrean event beredar; antrean 40 menit terverifikasi dan petugas sudah ditambah. Ada tuduhan biaya liar yang belum terbukti. Media meminta jawaban 15 menit lagi. Respons awal terbaik?', ['communication','risk'],[
 ['Akui antrean dan tindakan terverifikasi, pisahkan tuduhan yang diperiksa, berikan waktu update melalui juru bicara berwenang.',4,4],['Kirim kronologi antrean dan penambahan petugas saja; tuduhan biaya ditanggapi setelah investigasi lengkap.',3,3],['Minta media menunda publikasi sampai semua tuduhan dapat dijawab agar pernyataan tidak berubah.',2,3],['Nyatakan petugas sudah ditambah dan tuduhan belum terbukti, lalu tekankan bahwa layanan kini berjalan normal.',2,1]]),
 mc('cc-publicist',2,'Partner mengumumkan Ansena akan memberi 100 paket. Notulen menyebut 60, sedangkan chat staf menyebut 100 sebelum approval. Partner meminta konfirmasi publik sore ini. Langkah terbaik?', ['documentation','communication'],[
 ['Susun urutan bukti dan status approval, minta owner menetapkan komitmen, lalu sepakati koreksi atau klarifikasi dengan partner.',4,4],['Minta partner mengganti angka menjadi 60 berdasarkan notulen agar kanal publik segera konsisten.',3,2],['Gunakan angka 100 untuk menjaga hubungan, lalu minta tim operasional menyesuaikan kebutuhan.',1,3],['Tawarkan wording tanpa angka sementara owner menilai bukti; tetapkan tenggat konfirmasi bersama partner.',3,4]]),
 mc('cc-publicist',3,'Keluhan yang sama muncul di kanal perusahaan dan akun partner. Dua admin sudah menjawab dengan angka berbeda, investigasi masih berjalan. Bagaimana menata update berikutnya?', ['communication','ownership'],[
 ['Tetapkan sumber fakta dan approval tunggal, sinkronkan pesan kedua kanal, koreksi angka lama dan catat waktu update berikutnya.',4,4],['Gunakan angka dari admin senior agar respons cepat konsisten, lalu periksa perbedaan angka seusai investigasi.',2,2],['Hentikan respons kedua kanal sampai investigasi selesai supaya informasi tidak kembali berubah.',1,3],['Terbitkan update bersama tanpa angka sambil menyelaraskan sumber data dan jadwal informasi rinci.',3,4]]),
 mc('cc-publicist',4,'Tamu partner ditolak registrasi karena daftar lama. Namanya ada di konfirmasi email, tetapi akses ruang tertentu memerlukan approval keamanan. Acara sedang berjalan. Tindakanmu?', ['communication','risk'],[
 ['Dampingi ke petugas yang berwenang, cocokkan email/daftar, jelaskan waktu penanganan, dan verifikasi approval akses secara terpisah.',4,4],['Minta tamu menunggu di area umum sambil mengirim bukti email kepada petugas registrasi dan keamanan.',3,4],['Antar tamu langsung ke ruang acara berdasarkan email agar hubungan partner tidak terganggu.',3,1],['Ikuti daftar registrasi yang tersedia dan arahkan partner menghubungi pengundang untuk konfirmasi ulang.',1,3]]),
 es('cc-publicist',5,'Tulis respons awal maksimal 80 kata: antrean event 40 menit terverifikasi, petugas sudah ditambah, tuduhan biaya liar belum terverifikasi. Setelah respons, tulis siapa yang menyetujui, fakta apa yang perlu diperiksa, dan kapan/di mana update diberikan. Jangan mengarang hasil investigasi.',[['communication','Mengakui dampak antrean, menyampaikan tindakan nyata dan update secara jelas serta menghormati pihak yang mengeluh.'],['risk','Memisahkan fakta pasti dari tuduhan; tidak menyangkal/mengakui tuduhan tanpa bukti atau membuka data pribadi.'],['documentation','Menentukan sumber atau bukti yang perlu diverifikasi untuk tuduhan dan kronologi.'],['ownership','Menetapkan approval/juru bicara dan tenggat serta kanal update yang dapat ditindaklanjuti.']]),
 es('cc-publicist',6,'Sepekan setelah perbaikan respons komplain, jumlah komentar negatif turun, tetapi 4 dari 10 pelapor menyatakan belum mendapat tindak lanjut. Tentukan cara mengevaluasi penyelesaian kasus, koreksi komitmen yang terlewat, dan laporan untuk owner. Bedakan reputasi di kanal dari masalah yang benar-benar selesai.',[['communication','Mengecek pemahaman/konfirmasi pelapor dan menyampaikan status tanpa menganggap penurunan komentar sebagai penyelesaian.'],['ownership','Memetakan empat komitmen terbuka ke PIC, tenggat dan eskalasi yang jelas.'],['documentation','Menggunakan log kasus, bukti tindakan dan konfirmasi penutupan sebagai dasar laporan.'],['risk','Menjaga privasi laporan serta memberi batas klaim keberhasilan sesuai bukti penyelesaian.']])],
 'cc-executor':[
 mc('cc-executor',1,'Acara pukul 16.00. Banner baru tiba 15.30 dan butuh 40 menit pemasangan. Vendor alternatif dapat memasang sebelum 15.30 dengan biaya tambahan; hanya PIC dapat menyetujui biaya. Cocard siap di lokasi lain. Prioritas tindakan?', ['operations','ownership'],[
 ['Laporkan jalur kritis dan opsi biaya/waktu ke PIC dengan batas keputusan, sambil mengatur pengambilan cocard yang tidak bergantung banner.',4,4],['Ambil cocard dahulu lalu tunggu banner; pemasangan bisa dipercepat dengan meminta tambahan orang di lokasi.',2,3],['Pesan vendor alternatif segera agar acara aman, lalu ajukan biaya tambahan kepada PIC sesudah pemasangan.',3,1],['Minta PIC memilih alternatif dan tunggu keputusan sebelum melakukan seluruh pengambilan barang.',3,2]]),
 mc('cc-executor',2,'Pesanan 40 cocard harus memuat nama final. Vendor menawarkan 40 kartu kosong lebih cepat dan murah; mencetak nama di kantor perlu 60 menit, daftar final baru disetujui 30 menit sebelum acara. Pilihan paling dapat dipertanggungjawabkan?', ['operations','risk'],[
 ['Jelaskan bahwa opsi kartu kosong tetap tidak memenuhi waktu nama final; ajukan alternatif minimum dan perubahan spesifikasi untuk approval PIC.',4,4],['Terima kartu kosong untuk memastikan jumlah tersedia, lalu cetak nama sebanyak mungkin sesudah daftar disetujui.',2,2],['Tetap pesan cocard lengkap dari vendor semula dan minta komitmen percepatan agar spesifikasi tidak berubah.',3,2],['Tunda seluruh pesanan sampai daftar final keluar supaya tidak ada nama salah atau pembelian ulang.',1,3]]),
 mc('cc-executor',3,'Sudah dibayar Rp1,2 juta untuk 3 banner. Dua diterima; vendor mengirim kuitansi Rp1 juta dan menjanjikan sisanya besok. Acara hari ini. Apa bukti/status yang dilaporkan?', ['documentation','ownership'],[
 ['Pisahkan jumlah diterima, kekurangan untuk acara dan selisih bukti pembayaran; lampirkan bukti, PIC serta tenggat koreksi masing-masing.',4,4],['Laporkan dua banner diterima dan satu menyusul; koreksi kuitansi setelah seluruh pesanan lengkap.',2,3],['Tutup pekerjaan berdasarkan bukti transfer dan janji vendor, dengan catatan satu barang belum tiba.',1,2],['Tahan penutupan administrasi dan minta vendor segera mengoreksi kuitansi, sambil memberi PIC status kekurangan barang.',3,3]]),
 mc('cc-executor',4,'Banner dan meja sudah terpasang. Foto terlihat rapi, tetapi satu banner menutup arah masuk dan meja registrasi mempersempit jalur tamu. PIC belum datang. Apa QC sebelum serah-terima?', ['operations','risk'],[
 ['Uji alur tamu dan arah signage, koreksi penempatan dalam kewenangan, lalu kirim bukti serta deviasi yang membutuhkan keputusan PIC.',4,4],['Kirim foto dan minta PIC menilai penempatan; hindari memindahkan barang sebelum ia tiba.',2,3],['Rapikan seluruh setup agar foto serah-terima jelas, lalu minta petugas mengarahkan tamu secara langsung.',2,1],['Pindahkan barang yang mengganggu akses, lalu lakukan walkthrough bersama petugas registrasi sebelum konfirmasi PIC.',3,4]]),
 es('cc-executor',5,'Acara pukul 16.00 membutuhkan 3 banner, 40 cocard dan meja registrasi. Pukul 14.30, banner tertunda satu jam dan pemasangan perlu 40 menit; cocard siap di lokasi lain. Buat urutan kerja sampai serah-terima, opsi cadangan yang perlu approval, batas waktu keputusan PIC, serta tiga bukti selesai. Kamu petugas lapangan, bukan pemilik keputusan anggaran.',[['operations','Menghitung konsekuensi banner tiba 15.30 dan pemasangan 40 menit, mengatur pekerjaan paralel/rute serta cadangan yang realistis.'],['risk','Meminta persetujuan untuk tambahan biaya/perubahan spesifikasi dan menjaga akses serta keselamatan pemasangan.'],['ownership','Mengeskalasi sebelum batas keputusan terlambat, dengan PIC, estimasi dan tindak lanjut konkret.'],['documentation','Menentukan bukti jumlah/spesifikasi, QC pemasangan dan penerimaan PIC, bukan hanya foto atau bukti belanja.']]),
 es('cc-executor',6,'Tiga setup terakhir selalu selesai tepat waktu, tetapi dua memiliki salah ukuran banner dan satu kehilangan kuitansi. Susun perbaikan proses dari permintaan, pemesanan, penerimaan sampai serah-terima; tentukan bukti uji pada setup berikutnya dan cara menutup deviasi yang masih terbuka.',[['operations','Menambahkan cek spesifikasi pada titik pemesanan/penerimaan dan QC sebelum penempatan akhir.'],['documentation','Menghubungkan permintaan yang disetujui, bukti transaksi, barang diterima dan serah-terima dengan versi yang jelas.'],['ownership','Menetapkan PIC/tenggat penyelesaian kuitansi atau deviasi dan memverifikasi bahwa kasus benar-benar ditutup.'],['risk','Membedakan koreksi yang dapat dilakukan petugas dari perubahan ukuran/biaya yang memerlukan approval.']])],
 'pw-curator':[
 mc('pw-curator',1,'Role membutuhkan ketelitian pencatatan. A sangat lancar interview dan CV lengkap, tetapi dua tugasnya salah data; B kurang lancar bicara, kedua tugas akurat, kontribusi pribadinya belum diverifikasi. Rekomendasi paling kuat?', ['people','documentation'],[
 ['Utamakan bukti ketelitian yang relevan, verifikasi kontribusi B dan cek gap A dengan rubrik sama sebelum rekomendasi final.',4,4],['Pilih B berdasarkan dua tugas akurat karena itu kebutuhan inti, lalu verifikasi kontribusinya saat penempatan.',3,2],['Pilih A karena komunikasi dan CV menunjukkan kesiapan kerja; kesalahan data dapat ditutup melalui training.',1,2],['Minta keduanya mengulang seluruh interview dan practical agar keputusan bebas dari kesan sebelumnya.',2,3]]),
 mc('pw-curator',2,'Dua penilai memberi skor 4 dan 1 untuk kemampuan handover. Yang pertama menilai kerapian tulisan; yang kedua menemukan belum ada PIC dan deadline. Rubrik meminta isi yang bisa diteruskan shift berikutnya. Apa kalibrasi yang tepat?', ['people','documentation'],[
 ['Cocokkan bukti PIC/deadline/status dengan rubrik, pisahkan kerapian dari kelengkapan, dan sepakati alasan skor berdasarkan unsur itu.',4,4],['Gunakan rata-rata 2,5 agar kedua penilai tetap terwakili dan kandidat tidak dirugikan perbedaan pendapat.',1,2],['Minta penilai ketiga memberi skor tanpa melihat alasan dua penilai, lalu gunakan skor median.',2,3],['Minta contoh handover tambahan pada unsur yang hilang dengan instruksi dan standar yang sama untuk kandidat sebanding.',3,4]]),
 mc('pw-curator',3,'Referensi memberi klaim kandidat sering terlambat sekaligus rumor kehidupan pribadi. Kandidat mengizinkan cek referensi kerja, tetapi sumber belum memberi tanggal/contoh kejadian. Langkahmu?', ['risk','people'],[
 ['Abaikan rumor pribadi, minta contoh kerja relevan dan konteks yang dapat diverifikasi, lalu klarifikasi sebelum memakai klaim keterlambatan.',4,4],['Catat keterlambatan sebagai risiko sementara dan cari referensi kerja kedua dengan izin kandidat.',3,2],['Turunkan rekomendasi kandidat karena referensi sudah diberi izin dan informasi datang dari rekan kerja.',1,1],['Tidak gunakan keduanya untuk keputusan saat ini; lakukan verifikasi terstruktur pada bukti relevan yang masih kurang.',4,3]]),
 mc('pw-curator',4,'Tim meminta tiga orang minggu ini. Database berisi 30 kontak lama; 12 pernah cocok, tetapi status minat dan izin kontak sudah setahun tidak dicek. Role sekarang membutuhkan skill berbeda. Prioritas pemetaan?', ['people','communication'],[
 ['Tetapkan skill/bukti role baru, validasi izin dan minat calon paling relevan, lalu cek kemampuan terkini sebelum shortlist.',4,4],['Hubungi 12 kandidat lama terlebih dahulu karena sudah pernah dinilai cocok dan tenggat kebutuhan pendek.',2,3],['Kirim undangan role baru ke seluruh 30 kontak agar peluang memenuhi tiga orang lebih besar.',1,2],['Audit izin serta status kontak, kemudian minta kandidat yang bersedia mengirim bukti skill untuk role baru.',3,4]]),
 es('pw-curator',5,'Role membutuhkan ketelitian data dan handover. A: interview lancar, dua salah data, tidak menyebut PIC. B: tugas akurat dan handover lengkap, tetapi kontribusi pada karya tim belum jelas. Buat perbandingan bukti, dua pertanyaan verifikasi, rekomendasi bersyarat, dan satu bias yang harus dihindari. Jangan memakai CV/gaya bicara sebagai pengganti bukti skill.',[['people','Membandingkan bukti ketelitian/handover yang relevan dan mengakui kontribusi B masih perlu validasi; tidak langsung menganggap B pasti mampu.'],['documentation','Memisahkan fakta tugas, interpretasi penilai dan gap bukti dalam rekomendasi bersyarat.'],['communication','Merumuskan pertanyaan spesifik tentang kontribusi/tindakan kandidat dan unsur handover, bukan pertanyaan umum.'],['risk','Menghindari bias kelancaran bicara/CV atau label pribadi dan memakai standar yang konsisten.']]),
 es('pw-curator',6,'Setelah satu minggu placement pilot, skor practical tiga kandidat tinggi, tetapi dua sering kehilangan detail handover. Leader ingin mengeluarkan keduanya segera. Tentukan bukti kerja yang perlu dikumpulkan, cara membedakan gap kemampuan dari proses/alat, dan rekomendasi tindak lanjut yang adil beserta batas evaluasinya.',[['people','Menguji gap pada bukti handover nyata dan membandingkan kondisi kerja dengan practical; tidak menyimpulkan hanya dari nilai tes.'],['documentation','Menentukan contoh, frekuensi, unsur detail yang hilang serta standar observasi yang sama.'],['communication','Menjelaskan rekomendasi dan meminta konteks/kontribusi kandidat serta leader secara terstruktur.'],['risk','Membatasi keputusan sementara sesuai bukti, menjaga kerahasiaan dan menentukan evaluasi sebelum rekomendasi final.']])],
 'pw-developer':[
 mc('pw-developer',1,'Skor SOP naik dari 55 ke 85 setelah training. Kesalahan handover tetap 6 per minggu; formulir baru tidak menyediakan kolom pekerjaan tertunda. Tim meminta training ulang. Diagnosis terbaik?', ['learning','strategy'],[
 ['Amati handover nyata dan cek pengaruh formulir/alat, lalu pilih latihan atau perbaikan proses sesuai sumber kesalahan.',4,4],['Ulangi training dengan simulasi dan feedback lebih banyak agar pengetahuan dapat menjadi kebiasaan.',3,2],['Tetapkan skor kelulusan 90 agar hanya peserta yang benar-benar memahami SOP melanjutkan pekerjaan.',1,1],['Tambahkan kolom pekerjaan tertunda lalu ukur kesalahan; lakukan latihan pada unsur yang tetap bermasalah.',3,4]]),
 mc('pw-developer',2,'Training hanya 15 menit saat pergantian shift. Tujuan: peserta menyerahkan status pekerjaan, PIC dan tenggat secara lengkap. Pilihan rancangan paling tepat?', ['learning','communication'],[
 ['Contoh singkat, latihan handover kasus nyata, feedback dengan checklist dan pengulangan bagian yang hilang.',4,4],['Paparkan seluruh SOP handover lalu beri kuis pemahaman agar dasar peserta sama sebelum praktik kerja.',2,3],['Bagikan template dan video untuk ditonton mandiri agar 15 menit dapat dipakai membahas pertanyaan peserta.',2,4],['Demonstrasikan handover yang benar lalu minta peserta melakukan teach-back dengan checklist pada akhir sesi.',3,4]]),
 mc('pw-developer',3,'Peserta berkata sudah menjalankan SOP. Observasi menunjukkan ia menyebut status, tetapi tidak menetapkan PIC ketika tugas tertunda. Ia defensif karena pernah dikritik di depan tim. Feedback terbaik?', ['communication','learning'],[
 ['Bahas secara pribadi contoh tugas tertunda, jelaskan dampak PIC tidak jelas, lalu sepakati latihan menetapkan PIC dan cek berikutnya.',4,4],['Minta peserta menjelaskan hambatannya dahulu, lalu gunakan checklist bersama untuk menilai satu contoh handover.',4,3],['Sampaikan bahwa SOP wajib lengkap dan minta peserta berkomitmen tidak mengulangi kesalahan di shift berikutnya.',2,1],['Berikan contoh handover tertulis yang lengkap dan minta peserta mengikuti format yang sama mulai besok.',3,2]]),
 mc('pw-developer',4,'Dua unit memakai modul training yang sama. Unit A punya alat praktik; unit B hanya menonton. Nilai kuis setara, tetapi B sering salah penggunaan alat. Ukuran keberhasilan program yang lebih kuat?', ['learning','strategy'],[
 ['Observasi tugas dengan standar sama dan kesempatan praktik setara, lalu cek penerapan pada pekerjaan setelahnya.',4,4],['Tambahkan kuis kasus yang lebih sulit agar perbedaan pemahaman kedua unit terlihat.',2,2],['Bandingkan kepuasan peserta dan nilai kuis untuk memastikan materi dipahami tanpa bergantung alat.',1,1],['Sediakan praktik bagi B dan nilai keterampilan setelah latihan; catat keterbatasan pembandingan baseline kedua unit.',3,4]]),
 es('pw-developer',5,'Handover shift sering kehilangan PIC dan tenggat. Peserta dapat menjelaskan SOP, tetapi template tidak memiliki kolom dua unsur itu. Rancang sesi 15 menit: diagnosis singkat, tujuan perilaku, contoh/latihan, feedback, dan satu perubahan proses. Jelaskan mengapa training saja belum tentu cukup.',[['learning','Merancang praktik serta pengulangan handover dengan PIC/tenggat, bukan ceramah atau kuis pengetahuan saja.'],['people','Membedakan pengetahuan yang sudah dimiliki, perilaku nyata dan hambatan template tanpa menyalahkan peserta.'],['communication','Menentukan feedback spesifik pada unsur yang hilang dan contoh yang dapat dipahami petugas shift.'],['strategy','Mengalokasikan sesi 15 menit dan menggabungkan perubahan template dengan intervensi belajar sesuai diagnosis.']]),
 es('pw-developer',6,'Seminggu setelah sesi, nilai kuis naik; handover lengkap meningkat dari 4/10 ke 7/10. Tiga kasus gagal terjadi saat pergantian shift ramai. Tentukan pemeriksaan lanjutan, dua indikator penerapan, perbaikan yang diuji, dan keputusan apakah mengulang training.',[['learning','Memakai kelengkapan handover nyata dan keberlanjutan penerapan sebagai indikator, bukan nilai kuis saja.'],['people','Mengamati kondisi tiga kasus gagal dan membedakan gap keterampilan dari beban/proses saat shift ramai.'],['strategy','Memilih uji perbaikan yang sesuai temuan serta kondisi keputusan lanjut/perbaiki/ulang training.'],['communication','Menetapkan cara feedback dan koordinasi dengan leader/petugas pada observasi berikutnya.']])],
 'pw-workplace':[
 mc('pw-workplace',1,'Toilet selalu lolos checklist pagi, tetapi lantai basah dan bau muncul pukul 16.00–17.00. OB malam masuk 15.00. Pengguna paling ramai 15.30. Tindakan awal paling tepat?', ['workplace','documentation'],[
 ['Mitigasi lantai licin, inspeksi pada jam keluhan, catat lokasi/sumber serta pola pemakaian, lalu sesuaikan handover dan cek shift.',4,4],['Tambah jadwal pel setiap jam pada shift malam agar kondisi kembali bersih sepanjang sore.',2,2],['Minta OB malam menandatangani checklist lebih rinci sehingga kondisi tiap area dapat dipertanggungjawabkan.',2,3],['Amati proses bersih-bersih sore dan cek drainase/ventilasi dengan pihak teknis sesuai temuan.',3,4]]),
 mc('pw-workplace',2,'Gudang penuh dan barang event menutup sebagian jalur evakuasi. PIC meminta menunggu acara selesai dua jam lagi; ruang alternatif perlu koordinasi. Prioritasmu?', ['risk','operations'],[
 ['Amankan akses jalur sekarang, koordinasikan pemindahan ke lokasi yang tidak membuat bahaya baru, lalu verifikasi dan laporkan.',4,4],['Pasang penanda dan tempatkan petugas agar orang tetap dapat melewati bagian jalur yang terbuka.',1,3],['Minta PIC memperoleh ruang alternatif terlebih dahulu agar pemindahan tidak mengganggu area lain.',2,2],['Bagi pekerjaan dengan tim setup: buka jalur inti segera sambil menyiapkan pemindahan seluruh barang.',3,4]]),
 mc('pw-workplace',3,'Ruang A panas sore hari, ruang B tidak. Kapasitas AC sama; A penuh 30 orang dan terkena matahari, B berisi 10. Teknisi menyarankan mengganti dua AC sekaligus. Dasar rekomendasi terbaik?', ['workplace','risk'],[
 ['Catat suhu/jam, okupansi dan fungsi AC, minta pemeriksaan teknis A serta uji mitigasi sebelum menentukan penggantian.',4,4],['Ganti AC A lebih dahulu karena keluhan terpusat, lalu evaluasi apakah B memerlukan peningkatan.',3,2],['Samakan setting kedua AC agar kondisi pengukuran setara, lalu bandingkan keluhan pengguna.',2,3],['Kurangi jumlah orang A sementara dan pantau kondisi; jadwalkan pengecekan teknis berdasarkan pola panas.',3,4]]),
 mc('pw-workplace',4,'Sarung tangan stoknya tercatat cukup, tetapi dua area kehabisan saat shift malam. Daftar stok hanya memuat total kantor; tidak ada penerima distribusi. Perbaikan kontrol paling tepat?', ['documentation','operations'],[
 ['Catat stok minimum per area, jumlah dan penerima distribusi, titik cek tiap shift serta PIC tindak lanjut kekurangan.',4,4],['Tambah stok total kantor agar distribusi selalu memiliki cadangan ketika pemakaian meningkat.',1,3],['Minta setiap OB melapor saat stok habis dan tunjuk satu PIC yang memenuhi permintaan area.',2,3],['Rekonsiliasi stok fisik per area dan tetapkan kebutuhan minimum sebelum pengadaan berikutnya.',3,4]]),
 es('pw-workplace',5,'Pukul 15.30: toilet basah, kabel melintang jalur tamu, dan ruang training panas. OB baru mulai shift; teknisi baru bisa datang pukul 16.30. Buat urutan tindakan, penanganan dalam kewenangan, batas yang membutuhkan teknisi/PIC, handover OB, dan bukti area aman sebelum dipakai.',[['risk','Memprioritaskan bahaya terpeleset/akses atau listrik, melakukan isolasi/mitigasi aman tanpa perbaikan listrik di luar kewenangan.'],['workplace','Menentukan standar teramati untuk lantai, jalur dan kenyamanan ruang serta alternatif pemakaian selama belum layak.'],['operations','Mengatur urutan/koordinasi OB dan teknisi sesuai waktu kedatangan serta penggunaan area.'],['documentation','Mencatat kondisi, PIC, status terbuka dan verifikasi fisik sebelum menyatakan area aman.']]),
 es('pw-workplace',6,'Bau toilet muncul lagi tiga sore setelah pembersihan tambahan. Checklist selalu ditandatangani, tetapi tidak mencatat lokasi/jam bau. Tentukan cara memeriksa akar masalah, data yang dicatat, bantuan teknis yang diperlukan, dan kriteria perbaikan efektif setelah satu minggu.',[['workplace','Menelusuri sumber drainase/ventilasi/metode atau pola pemakaian sesuai observasi, bukan hanya menambah pewangi/pel.'],['documentation','Mencatat lokasi, jam, frekuensi, kondisi dan metode sehingga sebelum–sesudah dapat dibandingkan pada jam keluhan.'],['risk','Membedakan inspeksi/mitigasi petugas dari pemeriksaan teknis yang memerlukan pihak berwenang.'],['operations','Menetapkan PIC serta jadwal cek dan memverifikasi tidak berulang pada kondisi penggunaan yang sebanding.']])],
 'pw-executor':[
 mc('pw-executor',1,'Training 20 orang mulai 09.00. Pukul 08.15 proyektor belum diuji, 15 lembar materi tersedia, dan sarung tangan untuk praktik tiba 09.30. Fasilitator dapat mengubah urutan sesi. Prioritasmu?', ['operations','risk'],[
 ['Uji alat dan laporkan kebutuhan minimum ke fasilitator; siapkan materi untuk 20 orang dan ubah urutan agar praktik berisiko menunggu APD.',4,4],['Fokus menjemput sarung tangan lebih cepat, lalu minta fasilitator memakai 15 materi bergantian sampai alat siap.',2,2],['Mulai sesi sesuai jadwal memakai peserta yang sudah memperoleh sarung tangan, lalu lengkapi peserta lainnya saat stok tiba.',2,1],['Uji proyektor dan siapkan materi alternatif, kemudian sepakati sesi nonpraktik sambil menunggu sarung tangan.',3,4]]),
 mc('pw-executor',2,'Vendor mengirim sarung tangan berbeda model untuk pembersihan dengan bahan kimia. Ukuran dan jumlah sesuai, tetapi kesetaraan perlindungan belum dibuktikan. Stok lama cukup untuk satu area. Tindakan terbaik?', ['risk','operations'],[
 ['Tahan penggunaan model baru, minta verifikasi spesifikasi pihak berwenang, dan koordinasikan prioritas kerja dengan stok yang sesuai.',4,4],['Gunakan stok lama untuk area berisiko tinggi dan model baru untuk pekerjaan lain sambil menunggu dokumen vendor.',2,3],['Minta vendor menukar barang, lalu hentikan seluruh pekerjaan pembersihan sampai pengganti datang.',3,1],['Pisahkan stok baru dan siapkan alternatif tugas tanpa paparan; minta PIC memutuskan kebutuhan kritis area.',4,3]]),
 mc('pw-executor',3,'Catatan gudang: 12 alat dikirim ke tiga area. Penerima A menandatangani 4, B melaporkan 3, C belum memberi konfirmasi. Pengantar menyatakan semuanya lengkap. Langkah rekonsiliasi terbaik?', ['documentation','ownership'],[
 ['Cocokkan jumlah keluar, fisik per area dan bukti penerima; tandai selisih serta konfirmasi C dengan PIC dan tenggat penutupan.',4,4],['Minta pengantar mengulangi penghitungan rute distribusi, lalu gunakan keterangannya untuk memperbarui daftar penerimaan.',2,2],['Kirim satu alat ke B agar kebutuhan terpenuhi dan tutup distribusi berdasarkan catatan gudang.',1,3],['Penuhi kebutuhan kritis B sebagai transaksi sementara terpisah, sambil menelusuri selisih dan konfirmasi C.',3,4]]),
 mc('pw-executor',4,'Dua training membutuhkan satu proyektor. Sesi A 09.00–10.00, B 09.30–10.30; pemindahan alat perlu 15 menit. A dapat memakai diskusi tanpa layar 30 menit, B perlu video di awal. Opsi yang paling layak diajukan?', ['operations','ownership'],[
 ['Ajukan proyektor A sampai 09.15, pindahkan ke B sebelum 09.30, dan konfirmasi penyesuaian sesi serta PIC serah-terima.',4,4],['Gunakan di A sampai 09.30 lalu pindahkan ke B; minta fasilitator B menunggu sebentar sebelum videonya.',2,2],['Prioritaskan B sepanjang sesi dan minta A menjalankan training tanpa proyektor agar tidak ada perpindahan.',2,3],['Cari alat pinjaman yang setara dan siap diuji, dengan rencana pengaturan sesi jika pinjaman tidak tersedia tepat waktu.',3,4]]),
 es('pw-executor',5,'Training 20 orang pukul 09.00: materi baru 15 lembar, proyektor belum diuji, sarung tangan safety tiba 09.30. Kamu menyiapkan dan mendistribusikan perlengkapan, bukan menentukan kurikulum. Buat rencana mulai pukul 08.15, alternatif setup minimum, koordinasi fasilitator, batas keamanan praktik, dan bukti serah-terima.',[['operations','Mengurutkan uji alat, pemenuhan materi 20 peserta serta alternatif setup sesuai waktu dan kebutuhan sesi.'],['risk','Tidak menjalankan praktik yang membutuhkan APD sebelum perlindungan sesuai tersedia; eskalasi deviasi spesifikasi.'],['ownership','Mengonfirmasi perubahan urutan ke fasilitator/PIC dan memberi estimasi serta tindak lanjut perlengkapan tertunda.'],['documentation','Mencatat jumlah/kondisi, penerima, uji fungsi dan status kekurangan pada serah-terima.']]),
 es('pw-executor',6,'Sepekan terakhir stok total cukup, tetapi dua area kekurangan alat dan satu proyektor rusak baru diketahui saat training. Buat kontrol distribusi serta pemeriksaan alat, siapa yang menerima/memverifikasi, dan bukti yang menunjukkan masalah berkurang pada kegiatan berikutnya.',[['operations','Menetapkan cek kebutuhan per area dan uji fungsi alat sebelum kegiatan, bukan hanya menghitung stok total.'],['documentation','Menghubungkan jumlah keluar/diterima, kondisi alat dan penerima dengan pencatatan serta rekonsiliasi deviasi.'],['ownership','Menetapkan PIC dan tenggat koreksi kekurangan/kerusakan serta konfirmasi penutupan.'],['risk','Memisahkan alat bermasalah dari alat siap pakai dan mengatur eskalasi atau alternatif yang disetujui.']])]
 };
}
