import {participantPhoto} from '../lib/participant-photo.js';
import {finalScoreColumns,finalScoreRow} from '../lib/final-score-table.js';
import {recoverPost} from '../lib/post-recovery.js';
import {extendActivePost} from '../lib/post-time-extension.js';
import {recalibrateComparison} from '../lib/recalibration.js';
import {tableParticipant,tableColumns} from '../lib/admin-table.js';
import {positionRecommendations,recommendationCandidate} from '../lib/position-recommendations.js';
import {validatePostSchedule,participantPostInfo,postTiming,POST_TIMING_VERSION} from '../lib/post-schedule.js';
import {PRE_POST_DEADLINE_AT,PRE_POST_CLOSED_MESSAGE,prePostClosed,blockedAfterDeadline} from '../lib/access-deadline.js';
import {leadershipReady,postLeadershipReady,LEADERSHIP_VERSION,LEADER_CAPS} from '../lib/leadership.js';
import {comparisonReady,selfServiceMaterialsReady,roleChoices,CANDIDATE_FLOW_VERSION} from '../lib/candidate-flow.js';
import {recalculateRecord} from '../lib/revision.js';
import crypto from 'node:crypto';
import {ROLES,CAPS,WEIGHTS,VERSION,PILOT,DURATION,HANDBOOK,COMMON_HANDBOOK,POST_BANK_VERSION,questionsFor,publicQuestions} from '../lib/assessment.js';
import {validateAnswers,aggregate,routing,candidateSummary,finalRoleResults,primaryAssessment,baselineReady,SCORING_VERSION,SCORING_POLICY} from '../lib/scoring.js';
import {gradeEssays,GRADING_VERSION,DEFAULT_GRADING_MODEL,reasoningFor} from '../lib/grading.js';
import {AUDIT_VERSION,inspectEvidence,auditInventory,auditSemantics,fingerprint,gradeChanges,applyEvidenceRevision} from '../lib/evidence-audit.js';
import {read,write,mutate,listValues,remove,Conflict} from '../lib/storage.js';
import {reserveCode,assignCode,resolveCode} from '../lib/access.js';
import {suggestedMaterials,selectedMaterials,materialPlan,materialDownload,materialPDF} from '../lib/materials.js';
const uid=()=>crypto.randomBytes(24).toString('base64url');
const shuffle=items=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
const presentation=stage=>{const qs=questionsFor(stage);return{questions:shuffle(qs.map(q=>q.id)),options:Object.fromEntries(qs.filter(q=>q.options).map(q=>[q.id,shuffle(q.options.map((_,i)=>i))]))};};
const response=(res,status,data)=>res.status(status).json(data);
const error=(status,message)=>Object.assign(new Error(message),{status});
const body=req=>{const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):req.body||{};if(JSON.stringify(b).length>80000)throw error(413,'Data terlalu besar');return b;};
const query=(req,k)=>new URL(req.url,'https://local').searchParams.get(k)||'';
const safeToken=t=>{if(!/^[A-Za-z0-9_-]{24,64}$/.test(t||''))throw error(400,'Kode tidak valid');return t;};
const path=t=>'assessments/v2/'+safeToken(t)+'.json';
const postMaterialRecallReady=r=>!!r.postTestAccess?.enabled&&baselineReady(r)&&postLeadershipReady(r)&&participantPostInfo(r).schedule.published;
const secret=()=>{if(!process.env.ADMIN_SECRET)throw error(503,'ADMIN_SECRET belum terpasang');return process.env.ADMIN_SECRET;};
const sign=s=>crypto.createHmac('sha256',secret()).update(s).digest('base64url');
const equal=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y);};
const cookie=req=>String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ansena_admin='))?.slice(13);
function isAdmin(req){try{const c=cookie(req);if(!c)return false;const [v,s]=c.split('.');if(v==='ok')return equal(s,crypto.createHmac('sha256',secret()).update('ok').digest('hex'));const exp=Number(v);return exp>Date.now()&&equal(s,sign(v));}catch{return false;}}
function admin(req){if(!isAdmin(req))throw error(401,'Silakan login admin');}
const keyMaterial=()=>crypto.createHash('sha256').update(secret()).digest();
function encrypt(value){const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',keyMaterial(),iv);const v=Buffer.concat([c.update(value,'utf8'),c.final()]);return[iv,c.getAuthTag(),v].map(x=>x.toString('base64')).join('.');}
function decrypt(value){const[iv,tag,v]=value.split('.').map(x=>Buffer.from(x,'base64'));const d=crypto.createDecipheriv('aes-256-gcm',keyMaterial(),iv);d.setAuthTag(tag);return Buffer.concat([d.update(v),d.final()]).toString('utf8');}
async function operations(){return{materialsHeld:true,comparisonEnabled:false,selfServeMaterials:false,postTestsLocked:true,...((await read('settings/v3-operations.json'))?.value||{})};}
async function aiConfig(){const settings=(await read('settings/v2-ai.json'))?.value||{};return{key:process.env.OPENAI_API_KEY||(settings.encryptedKey?decrypt(settings.encryptedKey):''),model:process.env.ASSESSMENT_AI_MODEL||settings.model||DEFAULT_GRADING_MODEL};}
const pendingWarning=s=>s.securityEvents.find(e=>e.kind==='warning'&&!e.confirmedAt&&e.deadlineAt);
function postExpiryDue(r,now=Date.now()){return Object.entries(r.stages).some(([stage,s])=>stage.startsWith('post:')&&s.status==='active'&&Number.isFinite(s.expiresAt)&&now>=s.expiresAt);}
function settlePostExpiry(r,now=Date.now()){for(const [stage,s] of Object.entries(r.stages)){if(!stage.startsWith('post:')||s.status!=='active'||!Number.isFinite(s.expiresAt)||now<s.expiresAt)continue;s.status='terminated';s.submittedAt=s.expiresAt;s.terminationReason='time_expired';s.result=aggregate(stage,s.answers,[],s.questionBankVersion||'legacy');s.grading={status:s.result.complete?'complete':'pending'};s.reviewRequired=true;s.securityEvents.push({type:'time_expired',at:s.expiresAt});}}
function securityDue(r,now=Date.now()){return Object.values(r.stages).some(s=>s.status==='active'&&pendingWarning(s)?.deadlineAt<=now);}
function settleSecurity(r,now=Date.now()){for(const [stage,s] of Object.entries(r.stages)){const warning=pendingWarning(s);if(s.status!=='active'||!warning||now<warning.deadlineAt)continue;s.status='submitted';s.submittedAt=warning.deadlineAt;s.autoSubmitReason='security_confirmation_timeout';s.result=aggregate(stage,s.answers,[],s.questionBankVersion||'legacy');s.grading={status:s.result.complete?'complete':'pending'};s.reviewRequired=true;warning.timedOutAt=warning.deadlineAt;}}
async function record(t,now=Date.now()){const r=await read(path(t));if(!r)throw error(404,'Undangan tidak ditemukan. Undangan versi lama perlu dibuat ulang oleh admin.');if(securityDue(r.value,now)||postExpiryDue(r.value,now)){await mutate(path(t),r=>{settlePostExpiry(r,now);settleSecurity(r,now);});return(await read(path(t))).value;}return r.value;}
function allowed(r,stage){if(!questionsFor(stage))throw error(400,'Tahap tidak valid');if(stage==='pre'||stage==='comparison')return;if(stage==='leadership'){if(!r.leaderTrack?.enabled)throw error(403,'Modul leader hanya untuk pelamar yang ditandai admin');if(!comparisonReady(r))throw error(409,'Selesaikan 10 soal umum dan penilaiannya dahulu');return;}const[kind,role]=stage.split(':');if(kind==='practical')throw error(409,'Practical dilakukan di luar web.');if(!postLeadershipReady(r)||!baselineReady(r)||!selectedMaterials(r).includes(role))throw error(409,'Materi dan post-test menunggu pilihan admin');if(!r.postTestAccess?.enabled&&!r.stages[stage])throw error(409,'Post-test belum dibuka oleh admin');if(!r.materialRead?.[role]&&!prePostClosed())throw error(409,'Baca materi sebelum post-test');}
function active(r,stage){const s=r.stages[stage];if(!s||s.status!=='active')throw error(409,'Tes tidak aktif');if(stage.startsWith('post:')&&Number.isFinite(s.expiresAt)&&Date.now()>=s.expiresAt)throw error(410,'Waktu tes habis');return s;}
function enforceLockedAnswers(s,answers){for(const[k,a]of Object.entries(s.lockedAnswers||{}))if(answers[k]!==a)throw error(409,'Jawaban yang telah tersimpan sebelum pemulihan tidak dapat diubah');}
function cleanProfile(p){const allowed=['interests','talents','education','reading','hobbies','learningInterests','mbti','zodiac','rolePreferences','english'];const out={};for(const k of allowed){if(p[k]!==undefined){if(typeof p[k]!=='string'||p[k].length>2000)throw error(400,'Profil tidak valid');out[k]=p[k].trim();}}return out;}
async function evaluate(token,stage){
 await record(token);
 const p=path(token);let snapshot;const jobId=uid();
 await mutate(p,r=>{allowed(r,stage);const s=r.stages[stage];if(!s||!['submitted','terminated'].includes(s.status))throw error(409,'Jawaban belum dikirim');if(s.grading?.status==='complete'){snapshot=null;return;}
 if(s.grading?.status==='running'&&s.grading.expiresAt>Date.now())throw error(409,'Penilaian sedang berjalan');s.grading={status:'running',jobId,expiresAt:Date.now()+80000};snapshot=structuredClone(s);});
 if(!snapshot)return{ok:true};
 try{const cfg=await aiConfig();const evaluated=await gradeEssays(stage,snapshot.answers,cfg.key,cfg.model,undefined,snapshot.questionBankVersion||'legacy');const result=aggregate(stage,snapshot.answers,evaluated.grades,snapshot.questionBankVersion||'legacy');
 await mutate(p,r=>{const s=r.stages[stage];if(s.grading?.jobId!==jobId)throw error(409,'Penilaian sudah diperbarui');s.grades=evaluated.grades;s.result=result;s.grading={...evaluated,status:'complete',grades:undefined};s.reviewRequired=evaluated.reviewRequired||s.status==='terminated'||s.securityEvents.some(e=>e.kind==='warning');});return{ok:true};
 }catch(e){await mutate(p,r=>{const s=r.stages[stage];if(s.grading?.jobId===jobId)s.grading={status:e.code==='AI_NOT_CONFIGURED'?'not_configured':'failed',error:e.code||'AI_REVIEW_REQUIRED',updatedAt:Date.now()};});throw error(e.code==='AI_NOT_CONFIGURED'?503:502,e.message);}
}
export default async function handler(req,res){
 res.setHeader('Cache-Control','no-store');
 try{
 const receivedAt=Date.now();const action=query(req,'action');const method=req.method;
 if(method==='POST'&&req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)throw error(403,'Origin tidak diizinkan');
 if(action==='health'&&method==='GET'){const migration=(await read('settings/scoring-v3-deployment-migration.json'))?.value;const flow=(await read('settings/self-service-flow-verification.json'))?.value;return response(res,200,{version:VERSION,gradingVersion:GRADING_VERSION,evidenceAuditVersion:AUDIT_VERSION,status:'ok',postDurationMinutes:DURATION.post,postTimingVersion:POST_TIMING_VERSION,postBankVersion:POST_BANK_VERSION,postDurationPolicy:{oneOrTwoModules:13,threeToEightModules:9},serverNow:Date.now(),prePostDeadlineAt:PRE_POST_DEADLINE_AT,prePostClosed:prePostClosed(),initialPreRestored:(await read('settings/initial-pre-restored-20261002.json'))?.value?.state==='complete',invitationReload:(await read('settings/invitation-reopen-20261002.json'))?.value||null,prePostAuditVerified:(await read('settings/pre-post-audit-20261002.json'))?.value?.state==='complete',postTestsLocked:(await operations()).postTestsLocked,candidateFlowVersion:CANDIDATE_FLOW_VERSION,candidateFlowVerified:flow?.state==='complete',pilot:true,scoringVersion:SCORING_VERSION,leadershipVersion:LEADERSHIP_VERSION,leadershipVerified:(await read('settings/leader-module-verification.json'))?.value?.state==='complete',scoringRevisionComplete:migration?.state==='complete',backendVerificationPassed:migration?.state==='complete'&&Object.values(migration.proof||{}).every(v=>v===true)});}
 if(action==='admin-me'&&method==='GET')return response(res,200,{authenticated:isAdmin(req)});
 if(action==='admin-login'&&method==='POST'){const{password}=body(req);if(!process.env.ADMIN_PASSWORD)throw error(503,'Login admin belum dikonfigurasi');if(!equal(password,process.env.ADMIN_PASSWORD))throw error(401,'Password salah');const exp=String(Date.now()+28800000);res.setHeader('Set-Cookie',`ansena_admin=${exp}.${sign(exp)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`);return response(res,200,{ok:true});}
 if(action==='admin-logout'&&method==='POST'){res.setHeader('Set-Cookie','ansena_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');return response(res,200,{ok:true});}
 if(action.startsWith('admin-')){
 admin(req);
 if(action==='admin-post-schedule'&&method==='POST'){
  const b=body(req),token=safeToken(b.token||await resolveCode(b.code,req));
  if(b.postAccess!==undefined&&typeof b.postAccess!=='boolean')throw error(400,'Status akses post-test tidak valid');
  if(b.leadershipException!==undefined&&(typeof b.leadershipException!=='string'||!b.leadershipException.trim()||b.leadershipException.length>500))throw error(400,'Alasan pengecualian leader wajib');
  if(b.notice!==undefined&&(typeof b.notice!=='string'||b.notice.length>300))throw error(400,'Keterangan jadwal tidak valid');
  await mutate(path(token),r=>{
   if(b.expectedName!==r.candidateName)throw error(409,'Nama peserta tidak sesuai.');
   if(b.leadershipException!==undefined){if(!baselineReady(r))throw error(409,'Pendalaman dan penilaian harus lengkap');r.postTestException={leadershipPending:true,reason:b.leadershipException.trim(),updatedAt:Date.now()};}
   if(b.roles!==undefined){const roles=b.roles;if(!Array.isArray(roles)||!roles.length||roles.length>8||new Set(roles).size!==roles.length||roles.some(k=>!ROLES[k]))throw error(400,'Pilihan modul tidak valid');if(!baselineReady(r)||!postLeadershipReady(r))throw error(409,'Penilaian belum siap');if(Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Modul tidak dapat diganti setelah post-test dimulai');r.materialSelectionHistory??=[];if(r.materialSelection)r.materialSelectionHistory.push({at:Date.now(),reason:'admin_post_test_schedule',previous:structuredClone(r.materialSelection)});r.materialSelection={roles:[...roles],releasedAt:Date.now(),source:'admin',baselineSource:primaryAssessment(r).source};}
   if(b.postAccess===true&&(!baselineReady(r)||!postLeadershipReady(r)||!selectedMaterials(r).length))throw error(409,'Penilaian dan modul belum siap');
   if(b.postAccess===false&&Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Post-test sudah dimulai');
   const schedule=b.schedule===null?null:validatePostSchedule(r,b.schedule);
   if(r.postSchedule){r.postScheduleHistory??=[];r.postScheduleHistory.push({at:Date.now(),previous:structuredClone(r.postSchedule)});}
   if(schedule)r.postSchedule=schedule;else delete r.postSchedule;
   if(b.notice!==undefined)r.postScheduleNotice=b.notice;else delete r.postScheduleNotice;
   if(b.postAccess!==undefined)r.postTestAccess={...r.postTestAccess,enabled:b.postAccess,updatedAt:Date.now()};
  });return response(res,200,{ok:true});
 }
 if((String(body(req).stage||query(req,'stage')).startsWith('post:')||action==='admin-post-access'&&body(req).enabled===true)&&(await operations()).postTestsLocked)throw error(409,'Post-test dikunci untuk seluruh peserta');

 if(action==='admin-recalibrate-comparison'&&method==='POST'){const b=body(req);const result=await recalibrateComparison(b.token,b.phase,await aiConfig(),{chunkSize:b.chunkSize??2});return response(res,200,{ok:true,...result});}
 // Audit/regrading is admin-only, separate from participant attempts and access rules.
 if(action==='admin-evidence-audit'&&method==='GET'){
  const token=query(req,'token');
  const records=token?[(await read(path(token)))?.value].filter(Boolean):await listValues('assessments/v2/');
  const items=auditInventory(records);return response(res,200,{version:AUDIT_VERSION,records:records.length,stages:items.length,affected:items.filter(x=>x.affected).length,items});
 }
 if(['admin-evidence-audit','admin-evidence-regrade','admin-evidence-apply'].includes(action)&&method==='POST'){
  const {token,stage,reason,proposalId,reviewModel}=body(req);const p=path(token);
  if(reviewModel!==undefined&&!['gpt-4.1','gpt-4o-mini',DEFAULT_GRADING_MODEL].includes(reviewModel))throw error(400,'Model review tidak didukung');
  const repairConfig=action==='admin-evidence-apply'?null:await aiConfig();const repairModel=reviewModel||repairConfig?.model;
  if(!['pre','comparison','leadership'].includes(stage))throw error(400,'Audit perbaikan hanya untuk pre, pendalaman dan leader');
  if(action==='admin-evidence-apply'){
   if(typeof reason!=='string'||!reason.trim()||reason.length>1000)throw error(400,'Alasan penerapan wajib');
   const result=await mutate(p,r=>{const s=r.stages[stage];if(!s)throw error(404,'Tahap tidak ditemukan');if(s.evidenceJob?.expiresAt>Date.now())throw error(409,'Tunggu audit/penilaian selesai');return applyEvidenceRevision(s,stage,proposalId,reason);});
   return response(res,200,{ok:true,...result});
  }
  const jobId=uid();let snapshot;let cached;
  await mutate(p,r=>{
   const s=r.stages[stage];if(!s||!['submitted','terminated'].includes(s.status)||s.grading?.status!=='complete'||!s.grades?.length)throw error(409,'Tahap harus sudah selesai dinilai');
   if(s.evidenceJob?.expiresAt>Date.now())throw error(409,'Audit/penilaian sedang berjalan');
   const source=fingerprint(s);
   if(action==='admin-evidence-audit'&&s.evidenceAudit?.version===AUDIT_VERSION&&s.evidenceAudit?.requestedModel===repairModel&&s.evidenceAudit?.sourceFingerprint===source){cached=s.evidenceAudit;return;}
   if(action==='admin-evidence-regrade'){
    if(s.evidenceRevision?.status==='ready'&&s.evidenceRevision.evaluated?.gradingVersion===GRADING_VERSION&&s.evidenceRevision.evaluated?.requestedModel===repairModel&&s.evidenceRevision.sourceFingerprint===source){cached=s.evidenceRevision;return;}
    const audit=inspectEvidence(stage,s),semantic=s.evidenceAudit;
    if(!audit.affected&&!(semantic?.version===AUDIT_VERSION&&semantic?.sourceFingerprint===source&&semantic.needsReview))throw error(409,'Tidak ada temuan audit yang memerlukan penilaian ulang');
   }
   snapshot=structuredClone(s);s.evidenceJob={id:jobId,action,expiresAt:Date.now()+80000};
  });
  if(cached)return response(res,200,{ok:true,cached:true,result:cached});
  try{
   const result=action==='admin-evidence-audit'?await auditSemantics(stage,snapshot,repairConfig.key,repairModel):await gradeEssays(stage,snapshot.answers,repairConfig.key,repairModel,undefined,snapshot.questionBankVersion||'legacy');result.requestedModel=repairModel;
   let saved;await mutate(p,r=>{const s=r.stages[stage];if(s.evidenceJob?.id!==jobId||fingerprint(s)!==fingerprint(snapshot))throw error(409,'Jawaban/nilai berubah selama pemeriksaan');
    if(action==='admin-evidence-audit'){if(s.evidenceAudit){s.evidenceAuditHistory??=[];s.evidenceAuditHistory.push(s.evidenceAudit);}s.evidenceAudit=result;saved=result;}
    else{if(s.evidenceRevision){s.evidenceRevisionHistory??=[];s.evidenceRevisionHistory.push(s.evidenceRevision);}s.evidenceRevision={id:jobId,status:'ready',sourceFingerprint:fingerprint(snapshot),createdAt:Date.now(),reason:'Perbaikan bukti rubrik berdasarkan audit',audit:inspectEvidence(stage,snapshot),semanticAudit:snapshot.evidenceAudit||null,evaluated:result,result:aggregate(stage,snapshot.answers,result.grades,snapshot.questionBankVersion||'legacy'),changes:gradeChanges(snapshot.grades,result.grades)};saved=s.evidenceRevision;}
    delete s.evidenceJob;
   });return response(res,200,{ok:true,result:saved});
  }catch(e){await mutate(p,r=>{const s=r.stages[stage];if(s.evidenceJob?.id===jobId){delete s.evidenceJob;s.evidenceAuditError={at:Date.now(),action,message:e.code||'AUDIT_OR_REGRADE_FAILED'};}});if(e.code?.startsWith('AI_'))return response(res,e.code.includes('rate_limit')?429:502,{error:e.message,code:e.code,retryAfter:e.retryAfter||null});throw e;}
 }
 if(action==='admin-recalculate'&&method==='POST'){const{token}=body(req);safeToken(token);await mutate(path(token),recalculateRecord);return response(res,200,{ok:true,scoringVersion:SCORING_VERSION});}
 if(action==='admin-comparison-reset'&&method==='POST'){const{token,reason}=body(req);if(typeof reason!=='string'||!reason.trim())throw error(400,'Isi alasan mengulang pendalaman');await mutate(path(token),r=>{const s=r.stages.comparison;if(r.materialSelection?.releasedAt||Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Tahan ulang materi dan selesaikan review admin sebelum mengulang pendalaman');if(!s||!['submitted','terminated'].includes(s.status))throw error(409,'Pendalaman belum berakhir');if(s.grading?.status==='running'&&s.grading.expiresAt>Date.now())throw error(409,'Tunggu penilaian selesai');r.comparisonHistory??=[];r.comparisonHistory.push({at:Date.now(),reason:reason.slice(0,500),previous:structuredClone(s)});delete r.stages.comparison;});return response(res,200,{ok:true});}
 if(action==='admin-operations'&&method==='POST'){const b=body(req);if(typeof b.materialsHeld!=='boolean'||typeof b.comparisonEnabled!=='boolean')throw error(400,'Status operasional tidak valid');if(b.postTestsLocked!==undefined&&typeof b.postTestsLocked!=='boolean')throw error(400,'Status kunci post-test tidak valid');if(b.selfServeMaterials!==undefined&&typeof b.selfServeMaterials!=='boolean')throw error(400,'Status pemilihan mandiri tidak valid');await write('settings/v3-operations.json',{...await operations(),materialsHeld:b.materialsHeld,comparisonEnabled:b.comparisonEnabled,...(b.selfServeMaterials!==undefined?{selfServeMaterials:b.selfServeMaterials}:{}),...(b.postTestsLocked!==undefined?{postTestsLocked:b.postTestsLocked}:{}),updatedAt:Date.now()});return response(res,200,{ok:true,...await operations()});}
 if(action==='admin-extend-active-post'&&method==='POST'){
  const {incidentId,snapshotAt,minutes}=body(req);if(typeof incidentId!=='string'||!/^[-a-zA-Z0-9_]{5,80}$/.test(incidentId)||!Number.isFinite(snapshotAt)||snapshotAt>Date.now()||Date.now()-snapshotAt>1800000||minutes!==5)throw error(400,'Parameter kompensasi waktu tidak valid.');
  const records=await listValues('assessments/v2/'),changes=[];
  for(const r of records){const probe=extendActivePost(structuredClone(r),{incidentId,snapshotAt,extraMs:minutes*60000});if(!probe.length)continue;const applied=await mutate(path(r.token),x=>extendActivePost(x,{incidentId,snapshotAt,extraMs:minutes*60000}));if(applied.length)changes.push({name:r.candidateName,code:r.accessCode,changes:applied});}
  return response(res,200,{ok:true,incidentId,snapshotAt,minutes,changes});
 }
 if(action==='admin-recover-post'&&method==='POST'){
  const {code,expectedName,roleKey,incidentId,minutes}=body(req);if(!ROLES[roleKey]||typeof expectedName!=='string'||typeof incidentId!=='string'||!/^[-a-zA-Z0-9_]{5,80}$/.test(incidentId)||minutes!==5)throw error(400,'Parameter pemulihan tidak valid.');
  const t=await resolveCode(code,req),stage='post:'+roleKey;
  const result=await mutate(path(t),r=>{if(r.candidateName!==expectedName)throw error(409,'Nama peserta tidak sesuai: '+r.candidateName);const before=JSON.stringify(r.stages?.[stage]?.answers||{}),result=recoverPost(r,{stage,incidentId,minutes});if(JSON.stringify(r.stages[stage].answers||{})!==before)throw error(500,'Jawaban pemulihan tidak sesuai.');return result;});
  return response(res,200,{ok:true,code,stage,...result});
 }
 if(action==='admin-config'&&method==='GET'){const ai=await aiConfig();return response(res,200,{roles:ROLES,caps:CAPS,leaderCaps:LEADER_CAPS,weights:WEIGHTS,pilot:PILOT,duration:DURATION,scoring:SCORING_POLICY,migration:(await read('settings/scoring-v3-deployment-migration.json'))?.value||null,comparisonBank:questionsFor('comparison'),operations:await operations(),ai:{configured:!!ai.key,model:ai.model,reasoning:reasoningFor(ai.model),modelFromEnvironment:!!process.env.ASSESSMENT_AI_MODEL},bank:questionsFor('pre')});}
 if(action==='admin-position-recommendations'&&method==='GET'){
  const records=await listValues('assessments/v2/'),selection=(await read('settings/admin-position-shortlists.json'))?.value||{choices:{}};
  return response(res,200,{positions:positionRecommendations(records,selection),generatedAt:Date.now()});
 }
 if(action==='admin-position-shortlist'&&method==='POST'){
  const {roleKey,token,checked,expectedSelection}=body(req);
  if(!ROLES[roleKey]||typeof checked!=='boolean'||!(expectedSelection===null||typeof expectedSelection==='boolean'))throw error(400,'Pilihan shortlist tidak valid.');
  const r=(await read(path(token)))?.value;if(!r||!recommendationCandidate(r,roleKey))throw error(409,'Hasil posisi peserta belum tersedia. Perbarui hasil.');
  const selectionPath='settings/admin-position-shortlists.json';
  if(!(await read(selectionPath))){try{await write(selectionPath,{choices:{}},undefined,{create:true});}catch(e){if(!(e instanceof Conflict))throw e;}}
  await mutate(selectionPath,s=>{s.choices??={};s.choices[roleKey]??={};const old=s.choices[roleKey][token]??null;if(old!==expectedSelection)throw error(409,'Pilihan sudah berubah di perangkat lain. Perbarui hasil sebelum memilih lagi.');s.choices[roleKey][token]=checked;s.updatedAt=Date.now();});
  return response(res,200,{ok:true,checked});
 }
 if(action==='admin-bank'&&method==='GET'){const qs=questionsFor(query(req,'stage'));if(!qs)throw error(400,'Tahap tidak valid');return response(res,200,{questions:qs});}
 if(action==='admin-ai'&&method==='POST'){
  const {apiKey,model}=body(req),previous=(await read('settings/v2-ai.json'))?.value||{};
  if(apiKey!==undefined&&(typeof apiKey!=='string'||apiKey.length>300||apiKey&&!apiKey.startsWith('sk-')))throw error(400,'API key tidak valid');
  if(model!==undefined&&(typeof model!=='string'||!/^[a-zA-Z0-9._-]{1,80}$/.test(model)))throw error(400,'Model tidak valid');
  if(model&&process.env.ASSESSMENT_AI_MODEL&&model!==process.env.ASSESSMENT_AI_MODEL)throw error(409,'Model dikunci environment Vercel; ubah environment agar konfigurasi efektif');
  if(!apiKey&&!previous.encryptedKey&&!process.env.OPENAI_API_KEY)throw error(400,'API key belum terpasang');
  const cfg={...previous,...(apiKey?{encryptedKey:encrypt(apiKey)}:{}),model:model||previous.model||DEFAULT_GRADING_MODEL,updatedAt:Date.now()};
  await write('settings/v2-ai.json',cfg);return response(res,200,{ok:true,model:cfg.model,reasoning:reasoningFor(cfg.model)});
 }
 // Read-only calibration: no candidate record, grades, review flags or access is modified.
 if(action==='admin-calibrate'&&method==='POST'){
  const {token,stage,questionIds}=body(req);
  if(!['pre','comparison','leadership'].includes(stage)||!Array.isArray(questionIds)||!questionIds.length||questionIds.length>3||new Set(questionIds).size!==questionIds.length)throw error(400,'Pilih 1–3 esai unik untuk kalibrasi');
  const r=(await read(path(token)))?.value,s=r?.stages?.[stage];
  if(!s||!['submitted','terminated'].includes(s.status))throw error(409,'Jawaban belum dikirim');
  if(questionIds.some(id=>!questionsFor(stage).some(q=>q.id===id&&q.type==='essay')||!s.answers?.[id]?.trim()))throw error(400,'Jawaban esai tidak tersedia');
  const answers=Object.fromEntries(questionIds.map(id=>[id,s.answers[id]])),cfg=await aiConfig();
  const evaluated=await gradeEssays(stage,answers,cfg.key,cfg.model);
  return response(res,200,{ok:true,dryRun:true,sourceFingerprint:fingerprint(s),evaluated,changes:gradeChanges(s.grades,evaluated.grades)});
 }
 if(action==='admin-invite'&&method==='POST'){const b=body(req);const name=String(b.candidateName||'').trim(),currentTeam=String(b.currentTeam||'').trim();if(!name||name.length>150||currentTeam.length>200)throw error(400,'Isi nama dan tim saat ini dengan benar');const token=uid(),now=Date.now(),duration=DURATION.pre;const hours=Number(b.expiresHours)||168;if(hours<1||hours>720)throw error(400,'Batas undangan 1–720 jam');const accessCode=await reserveCode(token);const r={token,accessCode,version:VERSION,candidateName:name,currentTeam,createdAt:now,expiresAt:now+hours*3600000,duration,preferences:[],stages:{},profileStatus:'not_set',materialRead:{},notes:''};await write(path(token),r,null,{create:true});return response(res,200,{token,accessCode,candidateName:name,currentTeam});}
 if(action==='admin-delete-candidate'&&method==='POST'){const{token,submissionId,expectedName}=body(req);if(typeof expectedName!=='string'||!expectedName.trim()||expectedName.length>150||!!token===!!submissionId)throw error(400,'Pilih satu kandidat dan cocokkan nama sebelum menghapus');if(token){const p=path(token);const r=(await read(p))?.value;if(!r)return response(res,200,{ok:true,alreadyDeleted:true});if(r.candidateName!==expectedName)throw error(409,'Nama kandidat berubah; periksa ulang sebelum menghapus');if(Object.values(r.stages).some(s=>s.grading?.status==='running'&&s.grading.expiresAt>Date.now()))throw error(409,'Tunggu penilaian selesai sebelum menghapus');if(/^[1-9]\d{5}$/.test(r.accessCode||'')){const cp='access/v2-codes/'+r.accessCode+'.json';const code=(await read(cp))?.value;if(code?.token===token)await remove(cp);}await remove(p);return response(res,200,{ok:true});}if(typeof submissionId!=='string'||submissionId.length>100)throw error(400,'ID riwayat tidak valid');const matches=(await listValues('submissions/',{paths:true})).filter(x=>x.value.submissionId===submissionId);if(matches.length>1)throw error(409,'ID riwayat tidak unik; penghapusan dibatalkan');if(!matches.length)return response(res,200,{ok:true,alreadyDeleted:true});if(matches[0].value.candidateName!==expectedName)throw error(409,'Nama kandidat tidak sesuai');await remove(matches[0].pathname);return response(res,200,{ok:true});}
 if(action==='admin-code'&&method==='POST'){const{token}=body(req);safeToken(token);return response(res,200,{accessCode:await assignCode(token)});}
 if(action==='admin-materials'&&method==='POST'){const{token,roles}=body(req);safeToken(token);if(!Array.isArray(roles)||!roles.length||roles.length>8||new Set(roles).size!==roles.length||roles.some(k=>!ROLES[k]))throw error(400,'Pilih minimal satu posisi untuk materi');await assignCode(token);await mutate(path(token),r=>{if(!leadershipReady(r))throw error(409,'Selesaikan modul leader dan penilaiannya dahulu');if(!baselineReady(r))throw error(409,'Selesaikan pendalaman pembanding dan penilaiannya sebelum menerbitkan materi');const started=Object.keys(r.stages).filter(k=>k.startsWith('post:')).map(k=>k.split(':')[1]);if(started.some(k=>!roles.includes(k)))throw error(409,'Posisi dengan post-test yang sudah dimulai tidak dapat dihapus');r.materialSelection={roles:[...roles],releasedAt:Date.now(),source:'admin',baselineSource:primaryAssessment(r).source};});const r=await record(token);return response(res,200,{ok:true,...await materialDownload(r,'https://'+req.headers.host)});}
 if(action==='admin-recover-premature'&&method==='POST'){const{token,expectedName}=body(req);safeToken(token);await mutate(path(token),r=>{if(r.candidateName!==expectedName)throw error(409,'Nama kandidat tidak sesuai');const s=r.stages.pre;if(s?.status==='paused'&&s.recoveryHistory?.length)return;if(!s||s.status!=='terminated'||s.terminationReason!=='time_expired'||!Number.isFinite(s.expiresAt)||s.submittedAt>=s.expiresAt-2000||Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Sesi ini tidak memenuhi kriteria pemulihan timer prematur');const history={at:Date.now(),reason:'client_clock_premature_expiry',previous:structuredClone(s)};s.recoveryHistory=[...(s.recoveryHistory||[]),history];s.remainingMs=Math.min(DURATION.pre*60000,s.expiresAt-s.submittedAt);s.status='paused';s.expiresAt=null;s.recoveredAt=Date.now();for(const key of ['submittedAt','terminationReason','autoSubmitReason','result','grading','grades'])delete s[key];s.reviewRequired=true;});return response(res,200,{ok:true});}
 if(action==='admin-post-access'&&method==='POST'){const{token,enabled}=body(req);safeToken(token);if(typeof enabled!=='boolean')throw error(400,'Status akses post-test tidak valid');await mutate(path(token),r=>{if(enabled&&(!baselineReady(r)||!leadershipReady(r)||!selectedMaterials(r).length))throw error(409,'Selesaikan penilaian dan terbitkan materi sebelum membuka post-test');if(!enabled&&Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Post-test yang sudah dimulai tidak dapat ditutup');r.postTestAccess={enabled,updatedAt:Date.now()};});return response(res,200,{ok:true,postTestEnabled:enabled});}
 if(action==='admin-final-score-table'&&method==='GET'){const records=await listValues('assessments/v2/');return response(res,200,{columns:finalScoreColumns,records:records.map(finalScoreRow).filter(Boolean).sort((a,b)=>a.name.localeCompare(b.name,'id',{sensitivity:'base'})),generatedAt:Date.now()});}
 if(action==='admin-participant-table'&&method==='GET'){const records=await listValues('assessments/v2/');return response(res,200,{columns:tableColumns,records:records.map(tableParticipant).filter(Boolean).sort((a,b)=>a.name.localeCompare(b.name,'id',{sensitivity:'base'})||a.code.localeCompare(b.code))});}
 if(action==='admin-submissions'&&method==='GET'){const id=query(req,'id');if(id){const r=await record(id);return response(res,200,{record:{...r,photo:participantPhoto(r)},roleResults:finalRoleResults(r),primaryAssessment:primaryAssessment(r),routing:primaryAssessment(r).result?routing(primaryAssessment(r).result,r.preferences):null,materials:materialPlan(r),operations:await operations(),download:!(await operations()).materialsHeld&&(!(await operations()).selfServeMaterials||selfServiceMaterialsReady(r))&&r.materialSelection?.releasedAt&&r.accessCode?await materialDownload(r,'https://'+req.headers.host):null});}
 const records=await listValues('assessments/v2/');for(let i=0;i<records.length;i++)if(securityDue(records[i])||postExpiryDue(records[i]))records[i]=await record(records[i].token);const legacy=await listValues('submissions/');return response(res,200,{records:records.sort((a,b)=>b.createdAt-a.createdAt).map(r=>({photo:participantPhoto(r),token:r.token,candidateName:r.candidateName,currentTeam:r.currentTeam||'',accessCode:r.accessCode||'',createdAt:r.createdAt,hidden:!!r.adminVisibility?.hidden,leaderTrack:!!r.leaderTrack?.enabled,requiresComparison:!!r.requiresComparison,preferences:r.preferences,scoreSummary:{final:comparisonReady(r)?r.stages.comparison.result.roleFits.map(({roleKey,score})=>({roleKey,score})):[],pre:['submitted','terminated'].includes(r.stages.pre?.status)&&r.stages.pre?.grading?.status==='complete'?(r.stages.pre.result?.roleFits||[]).map(({roleKey,score})=>({roleKey,score})):[]},stages:candidateSummary(r).stages,shortlist:candidateSummary(r).shortlist,profileStatus:r.profileStatus,reviewRequired:Object.values(r.stages).some(s=>s.reviewRequired)})),legacy:legacy.map(r=>({submissionId:r.submissionId,candidateName:r.candidateName,role:r.role,team:r.team,score:r.score,finishedAt:r.finishedAt}))});}
 if(action==='admin-grade'&&method==='POST'){const{token,stage}=body(req);await evaluate(token,stage);return response(res,200,{ok:true});}
 if(action==='admin-leader-track'&&method==='POST'){const{token,enabled}=body(req);safeToken(token);if(typeof enabled!=='boolean')throw error(400,'Status pelamar leader tidak valid');await mutate(path(token),r=>{r.leaderTrack={enabled,updatedAt:Date.now()};});return response(res,200,{ok:true,enabled});}
 if(action==='admin-visibility'&&method==='POST'){const{token,hidden}=body(req);safeToken(token);if(typeof hidden!=='boolean')throw error(400,'Status filter tidak valid');await mutate(path(token),r=>{r.adminVisibility={hidden,updatedAt:Date.now()};});return response(res,200,{ok:true,hidden});}
 if(action==='admin-notes'&&method==='POST'){const{token,notes,checklist={}}=body(req);if(typeof notes!=='string'||notes.length>5000)throw error(400,'Catatan terlalu panjang');if(!checklist||typeof checklist!=='object'||Array.isArray(checklist)||Object.entries(checklist).some(([cap,rating])=>!CAPS[cap]||!['yes','mid','no',''].includes(rating)))throw error(400,'Checklist tidak valid');await mutate(path(token),r=>{r.notes=notes;r.validationChecklist=checklist;r.notesUpdatedAt=Date.now();});return response(res,200,{ok:true});}
 if(action==='admin-review'&&method==='POST'){const{token,stage,grades,reason}=body(req);if(typeof reason!=='string'||!reason.trim())throw error(400,'Alasan override wajib');const{validateGrades}=await import('../lib/grading.js');await mutate(path(token),r=>{const s=r.stages[stage];if(!s||!['submitted','terminated'].includes(s.status))throw error(409,'Tahap belum dikirim');if(s.grading?.status==='running'&&s.grading.expiresAt>Date.now())throw error(409,'Tunggu penilaian AI selesai');if(stage==='pre'&&Object.keys(r.stages).some(k=>k!=='pre'))throw error(409,'Review pre-assessment harus selesai sebelum pendalaman dimulai');const qs=questionsFor(stage,s.questionBankVersion||'legacy').filter(q=>q.type==='essay'&&s.answers[q.id]?.trim());const checked=validateGrades(qs,{grades},s.answers);s.reviewHistory??=[];s.reviewHistory.push({at:Date.now(),reason,previousGrades:s.grades||[],previousGrading:s.grading,previousResult:structuredClone(s.result)});s.grades=checked;s.result=aggregate(stage,s.answers,checked,s.questionBankVersion||'legacy');s.grading={status:'complete',method:'manual_exception',gradedAt:Date.now()};s.reviewRequired=false;});return response(res,200,{ok:true});}
 throw error(404,'Aksi admin tidak ditemukan');
 }
 const b=method==='POST'?body(req):{};
 const ops=await operations();
 let recallToken='',materialRecall=false;
 if(action==='material-pdf'&&method==='GET'){recallToken=safeToken(query(req,'token')||(query(req,'code')?await resolveCode(query(req,'code'),req):''));materialRecall=postMaterialRecallReady(await record(recallToken));}
 if(blockedAfterDeadline(action,b.stage||query(req,'stage')||(['start','quiz'].includes(action)?'pre':''),receivedAt)&&!materialRecall)return response(res,423,{error:PRE_POST_CLOSED_MESSAGE,prePostClosed:true,deadlineAt:PRE_POST_DEADLINE_AT});
 if(ops.postTestsLocked&&String(b.stage||query(req,'stage')).startsWith('post:'))throw error(409,'Post-test dikunci untuk seluruh peserta');
 if(action==='start'&&b.stage==='comparison'&&!ops.comparisonEnabled)throw error(409,'Pendalaman pembanding belum dibuka oleh admin');
 if(ops.materialsHeld&&(['material-pdf','materials','materials-read'].includes(action)||(['start','quiz'].includes(action)&&(b.stage||query(req,'stage')).startsWith('post:'))))throw error(423,'Materi sedang ditahan untuk pembaruan penilaian. Tunggu pengumuman penyelenggara.');
 if(action==='resolve-code'&&method==='POST')return response(res,200,{token:await resolveCode(b.code,req)});
 if(action==='post-info'&&method==='POST'){const infoToken=await resolveCode(b.code,req),r=await record(infoToken);return response(res,200,{...participantPostInfo(r),download:!ops.materialsHeld&&postMaterialRecallReady(r)?await materialDownload(r,'https://'+req.headers.host):null});}
 const token=safeToken(b.token||query(req,'token')||recallToken);
 let requestRecord;if(['save','security-warning','security-resume','security-timeout','submit','violation'].includes(action))requestRecord=await record(token,receivedAt);
 if(!materialRecall&&ops.selfServeMaterials&&(['material-pdf','materials','materials-read'].includes(action)||(['start','quiz'].includes(action)&&(b.stage||query(req,'stage')).startsWith('post:')))&&!selfServiceMaterialsReady(await record(token))&&!(String(b.stage||query(req,'stage')).startsWith('post:')&&baselineReady(await record(token))&&postLeadershipReady(await record(token))))throw error(403,'Selesaikan 10 soal pendalaman, penilaian dan pilihan posisi sebelum membuka materi');
 if(!materialRecall&&['material-pdf','materials','materials-read'].includes(action)&&!leadershipReady(await record(token)))throw error(403,'Selesaikan modul leader dan penilaiannya dahulu');
 if(action==='candidate-materials'&&method==='POST'){if(!ops.selfServeMaterials)throw error(409,'Pemilihan materi mandiri belum dibuka');if(ops.materialsHeld)throw error(423,'Materi sedang ditahan oleh penyelenggara');const roles=b.roles;if(!Array.isArray(roles)||!roles.length||roles.length>8||new Set(roles).size!==roles.length||roles.some(k=>!ROLES[k]))throw error(400,'Pilih minimal satu posisi yang tersedia');await mutate(path(token),r=>{if(!leadershipReady(r))throw error(409,'Selesaikan modul leader dan penilaiannya dahulu');if(!comparisonReady(r))throw error(409,'Selesaikan seluruh 10 soal dan penilaiannya terlebih dahulu');const started=Object.keys(r.stages).filter(k=>k.startsWith('post:')).map(k=>k.split(':')[1]);if(started.some(k=>!roles.includes(k)))throw error(409,'Posisi dengan post-test yang sudah dimulai tidak dapat dihapus');if(r.materialSelection){r.materialSelectionHistory??=[];r.materialSelectionHistory.push({at:Date.now(),reason:'candidate_material_selection',previous:structuredClone(r.materialSelection)});}r.materialSelection={roles:[...roles],releasedAt:Date.now(),source:'candidate',baselineSource:'comparison',flowVersion:CANDIDATE_FLOW_VERSION};});return response(res,200,{ok:true,...await materialDownload(await record(token),'https://'+req.headers.host)});}
 if(['comparison-resume','leadership-resume'].includes(action)&&method==='POST'){const resumeStage=action==='leadership-resume'?'leadership':'comparison',requiredCount=resumeStage==='leadership'?4:10;if(!ops.selfServeMaterials)throw error(409,'Pemulihan mandiri belum dibuka');await mutate(path(token),r=>{allowed(r,resumeStage);const s=r.stages[resumeStage];if(!s||!['submitted','terminated'].includes(s.status)||Object.values(s.answers||{}).filter(a=>typeof a==='string'&&a.trim()).length>=requiredCount)throw error(409,'Tidak ada pendalaman belum lengkap untuk dilanjutkan');if(r.materialSelection?.baselineSource==='comparison'&&r.materialSelection.releasedAt||Object.keys(r.stages).some(k=>k.startsWith('post:')))throw error(409,'Pendalaman tidak dapat diubah setelah materi atau post-test diterbitkan');if(s.grading?.status==='running'&&s.grading.expiresAt>Date.now())throw error(409,'Penilaian sedang berjalan. Coba lanjutkan setelah selesai');s.resumeHistory??=[];s.resumeHistory.push({at:Date.now(),previous:structuredClone({...s,resumeHistory:undefined})});s.lockedAnswers={...s.lockedAnswers,...Object.fromEntries(Object.entries(s.answers).filter(([,a])=>typeof a==='string'&&a.trim()))};s.status='active';s.expiresAt=null;s.resumedAt=Date.now();delete s.result;delete s.grading;delete s.grades;delete s.autoSubmitReason;delete s.submittedAt;delete s.terminationReason;for(const e of s.securityEvents)if(e.kind==='warning'&&!e.confirmedAt)e.confirmedAt=Date.now();});return response(res,200,{ok:true});}
 if(action==='invite'&&method==='GET'){const r=await record(token);if(Date.now()>r.expiresAt&&!Object.keys(r.stages||{}).length&&!ops.comparisonEnabled)throw error(410,'Undangan kedaluwarsa');const summary=candidateSummary(r),available=!prePostClosed(receivedAt)&&!ops.materialsHeld&&(!ops.selfServeMaterials||selfServiceMaterialsReady(r)),postTestPrepared=!!r.postTestAccess?.enabled&&baselineReady(r)&&postLeadershipReady(r)&&selectedMaterials(r).length>0;return response(res,200,{...summary,serverNow:receivedAt,prePostDeadlineAt:PRE_POST_DEADLINE_AT,prePostClosed:prePostClosed(receivedAt),initialPreRequired:!!ops.initialPreRequired&&!r.stages.comparison,leaderTrack:!!r.leaderTrack?.enabled,leadershipReady:leadershipReady(r),materialsHeld:ops.materialsHeld,comparisonEnabled:ops.comparisonEnabled,selfServeMaterials:ops.selfServeMaterials,roleSelection:ops.selfServeMaterials&&!prePostClosed(receivedAt)?roleChoices(r):null,download:available&&r.materialSelection?.releasedAt?await materialDownload(r,'https://'+req.headers.host):null,materialRoles:available||postTestPrepared?summary.materialRoles:[],materialsReleased:available&&!!r.materialSelection?.releasedAt,postTestsLocked:ops.postTestsLocked,postTestPrepared,postTiming:postTiming(r),postTestEnabled:!ops.postTestsLocked&&!ops.materialsHeld&&postTestPrepared,duration:r.stages.pre?r.duration:DURATION.pre,roles:ROLES,expiresAt:r.expiresAt});}
 if(action==='start'&&method==='POST'){const stage=b.stage||'pre';await mutate(path(token),r=>{allowed(r,stage);if(stage==='comparison'&&ops.initialPreRequired&&!r.stages.comparison&&!['submitted','terminated'].includes(r.stages.pre?.status))throw error(409,'Selesaikan pre-test 32 soal terlebih dahulu');if(r.stages[stage])throw error(409,'Tahap ini sudah dimulai; hanya satu kesempatan');if(stage==='pre'){r.duration=DURATION.pre;if(Date.now()>r.expiresAt)throw error(410,'Undangan kedaluwarsa');if(!b.identity?.name?.trim()||!b.identity?.contact?.trim())throw error(400,'Nama dan kontak wajib');r.identity={name:String(b.identity.name).trim().slice(0,150),contact:String(b.identity.contact).trim().slice(0,200),currentRole:String(b.identity.currentRole||'').trim().slice(0,200)};r.candidateName=r.identity.name;const prefs=b.preferences;if(!Array.isArray(prefs)||!prefs.length||prefs.length>8||prefs.some(x=>!ROLES[x]))throw error(400,'Pilih minimal satu posisi');r.preferences=[...new Set(prefs)];r.aiConsent=true;}
 if(stage==='leadership'&&b.consent!==true)throw error(400,'Setujui aturan dan penilaian AI untuk modul leader');if(stage==='comparison'){if(b.consent!==true)throw error(400,'Setujui aturan dan penilaian AI untuk pendalaman');if(!r.identity){if(!b.identity?.name?.trim()||!b.identity?.contact?.trim())throw error(400,'Nama dan kontak wajib');r.identity={name:String(b.identity.name).trim().slice(0,150),contact:String(b.identity.contact).trim().slice(0,200)};r.candidateName=r.identity.name;const prefs=b.preferences;if(!Array.isArray(prefs)||!prefs.length||prefs.some(k=>!ROLES[k]))throw error(400,'Pilih posisi yang diminati');r.preferences=[...new Set(prefs)];}r.requiresComparison=true;r.aiConsent=true;}
 const minutes=stage==='pre'?DURATION.pre:stage.startsWith('post:')?postTiming(r).testMinutes:null;const startedAt=Date.now();r.stages[stage]={status:'active',...(stage.startsWith('post:')?{questionBankVersion:POST_BANK_VERSION}:{}),presentation:['comparison','leadership'].includes(stage)?{questions:questionsFor(stage).map(q=>q.id),options:{}}:presentation(stage),startedAt,expiresAt:minutes===null?null:startedAt+minutes*60000,answers:{},revision:0,securityEvents:[]};});const r=await record(token);return response(res,200,{questions:publicQuestions(stage,r.stages[stage].presentation,r.stages[stage].questionBankVersion||'legacy'),expiresAt:r.stages[stage].expiresAt,stage,serverNow:Date.now()});}
 if(action==='resume-recovered'&&method==='POST'){await mutate(path(token),r=>{const s=r.stages[b.stage];if(s?.status!=='paused'||(b.stage!=='pre'&&!(b.stage?.startsWith('post:')&&s.recoveryHistory?.length)))throw error(409,'Sesi tidak menunggu pemulihan');if(b.stage.startsWith('post:')){allowed(r,b.stage);if(Object.entries(r.stages).some(([k,v])=>k!==b.stage&&k.startsWith('post:')&&v.status==='active'))throw error(409,'Selesaikan modul post-test yang sedang aktif terlebih dahulu.');}s.status='active';s.resumedAt=Date.now();s.expiresAt=Date.now()+s.remainingMs;delete s.remainingMs;});const r=await record(token),s=r.stages[b.stage];return response(res,200,{questions:publicQuestions(b.stage,s.presentation,s.questionBankVersion||'legacy'),answers:s.answers,revision:s.revision,expiresAt:s.expiresAt,stage:b.stage,serverNow:Date.now(),lockedAnswers:Object.keys(s.lockedAnswers||{})});}
 if(action==='quiz'&&method==='GET'){const stage=query(req,'stage')||'pre';const r=await record(token);allowed(r,stage);const s=r.stages[stage]?.status==='paused'?r.stages[stage]:active(r,stage);return response(res,200,{serverNow:Date.now(),recoverable:s.status==='paused',questions:publicQuestions(stage,s.presentation,s.questionBankVersion||'legacy'),answers:s.answers,revision:s.revision,expiresAt:s.expiresAt,stage,lockedAnswers:Object.keys(s.lockedAnswers||{}),warning:s.securityEvents.findLast(e=>e.kind==='warning'&&!e.confirmedAt)||null});}
 if(action==='save'&&method==='POST'){const stage=b.stage;const answers=validateAnswers(stage,b.answers,{partial:true,bankVersion:requestRecord?.stages?.[stage]?.questionBankVersion||'legacy'});await mutate(path(token),r=>{const s=active(r,stage);enforceLockedAnswers(s,answers);if(s.expiresAt!==null&&Date.now()>s.expiresAt)throw error(410,'Waktu tes habis');if(!Number.isInteger(b.revision)||b.revision<=s.revision)return;s.answers=answers;s.revision=b.revision;s.savedAt=Date.now();});return response(res,200,{ok:true,savedAt:Date.now()});}
 if((action==='security-warning'||(action==='violation'&&!['time_expired'].includes(b.type)))&&method==='POST'){const answers=validateAnswers(b.stage,b.answers||{},{partial:true,bankVersion:requestRecord?.stages?.[b.stage]?.questionBankVersion||'legacy'});let eventId=String(b.eventId||uid()).slice(0,80),deadlineAt;await mutate(path(token),r=>{const s=active(r,b.stage);enforceLockedAnswers(s,answers);const pending=pendingWarning(s);if(pending){eventId=pending.id;deadlineAt=pending.deadlineAt;return;}if((s.expiresAt===null||Date.now()<=s.expiresAt)&&Number.isInteger(b.revision)&&b.revision>=s.revision){s.answers=answers;s.revision=b.revision;s.savedAt=Date.now();}const prior=s.securityEvents.find(e=>e.id===eventId);if(prior){deadlineAt=prior.deadlineAt;return;}deadlineAt=Date.now()+10000;s.securityEvents.push({id:eventId,kind:'warning',type:String(b.type||'security_warning').slice(0,80),at:Date.now(),deadlineAt,confirmedAt:null});s.reviewRequired=true;});return response(res,200,{ok:true,eventId,deadlineAt});}
 if(action==='security-resume'&&method==='POST'){let timedOut=false;await mutate(path(token),r=>{settleSecurity(r,receivedAt);const s=r.stages[b.stage];if(s?.status!=='active'&&s?.autoSubmitReason==='security_confirmation_timeout'){timedOut=true;return;}active(r,b.stage);if(s.expiresAt!==null&&Date.now()>s.expiresAt+2000)throw error(410,'Waktu tes habis');const pending=pendingWarning(s);if(pending&&pending.id!==b.eventId)throw error(409,'Konfirmasi peringatan tidak sesuai');for(const e of s.securityEvents)if(e.kind==='warning'&&!e.confirmedAt)e.confirmedAt=receivedAt;});if(timedOut)throw error(410,'Konfirmasi 10 detik terlewat; jawaban sudah dikirim otomatis');return response(res,200,{ok:true});}
 if(action==='security-timeout'&&method==='POST'){await mutate(path(token),r=>{settleSecurity(r);const s=r.stages[b.stage];if(!s)throw error(404,'Tahap tidak ditemukan');if(s.status!=='active')return;const w=pendingWarning(s);if(!w)throw error(409,'Tidak ada peringatan aktif');/* A client may reach its local deadline before the server received the warning. */s.status='submitted';s.submittedAt=Date.now();s.autoSubmitReason='security_confirmation_timeout';s.result=aggregate(b.stage,s.answers,[],s.questionBankVersion||'legacy');s.grading={status:s.result.complete?'complete':'pending'};s.reviewRequired=true;w.timedOutAt=Date.now();});return response(res,200,{ok:true,summary:candidateSummary(await record(token))});}
 if(['submit','violation'].includes(action)&&method==='POST'){const stage=b.stage;let answers=validateAnswers(stage,b.answers||{},{partial:action==='violation',bankVersion:requestRecord?.stages?.[stage]?.questionBankVersion||'legacy'});await mutate(path(token),r=>{const s=r.stages[stage];if(!s)throw error(404,'Tahap tidak ditemukan');if(s.status!=='active')return;enforceLockedAnswers(s,answers);if(action==='violation'&&b.type==='time_expired'&&(s.expiresAt===null||Date.now()<s.expiresAt))throw error(409,'Waktu server belum habis; muat ulang untuk menyinkronkan timer');if(action==='submit'&&pendingWarning(s))throw error(409,'Konfirmasi peringatan sebelum mengirim jawaban');const expired=s.expiresAt!==null&&(stage.startsWith('post:')?Date.now()>=s.expiresAt:Date.now()>s.expiresAt+2000);const terminated=action==='violation'||expired;const reason=expired?'time_expired':String(b.type||'security_violation').slice(0,80);if(expired)answers=s.answers;s.answers=answers;s.status=terminated?'terminated':'submitted';s.submittedAt=Date.now();if(terminated){s.terminationReason=reason;s.securityEvents.push({type:reason,at:Date.now()});}s.result=aggregate(stage,answers,[],s.questionBankVersion||'legacy');s.grading={status:s.result.complete?'complete':'pending'};s.reviewRequired=terminated||s.securityEvents.some(e=>e.kind==='warning');});if((stage==='leadership'||ops.selfServeMaterials&&stage==='comparison')&&(await record(token)).stages[stage].result?.answeredCount===(stage==='leadership'?4:10)){try{await evaluate(token,stage);}catch{/* Answers remain committed; the candidate can retry grading. */}}return response(res,200,{ok:true,summary:candidateSummary(await record(token))});}
 if(action==='evaluate'&&method==='POST'){await evaluate(token,b.stage);return response(res,200,{ok:true});}
 if(action==='profile'&&method==='POST'){await mutate(path(token),r=>{if(!['submitted','terminated'].includes(r.stages.pre?.status)&&!['submitted','terminated'].includes(r.stages.comparison?.status))throw error(409,'Selesaikan assessment dahulu');r.profile=b.skip?{}:cleanProfile(b.profile||{});r.profileStatus=b.skip?'skipped':'saved';r.profileUpdatedAt=Date.now();});return response(res,200,{ok:true});}
 if(action==='material-pdf'&&method==='GET'){const r=await record(token),roles=selectedMaterials(r);if(!baselineReady(r)||!roles.length)throw error(403,'Materi belum diterbitkan oleh admin');const pdf=await materialPDF(roles);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="Ansena-Materi-${r.accessCode||'CC-PW'}.pdf"`);return res.status(200).send(pdf);}
 if(action==='materials'&&method==='GET'){const r=await record(token);const role=query(req,'role');if(!postLeadershipReady(r)||!baselineReady(r)||!selectedMaterials(r).includes(role))throw error(403,'Posisi tidak tersedia');return response(res,200,{common:COMMON_HANDBOOK,module:HANDBOOK[role],role:ROLES[role]});}
 if(action==='materials-read'&&method==='POST'){await mutate(path(token),r=>{if(!baselineReady(r)||!selectedMaterials(r).includes(b.role))throw error(403,'Posisi tidak tersedia');r.materialRead[b.role]=Date.now();});return response(res,200,{ok:true});}
 throw error(404,'Aksi tidak ditemukan');
 }catch(e){const status=e.status||(e instanceof Conflict?409:500);if(status===500)console.error('assessment_error',e.constructor.name,e.code||'',String(e.message).replace(/sk-[A-Za-z0-9_-]+/g,'[redacted]').slice(0,400));return response(res,status,{error:status===500?'Terjadi kendala server. Coba lagi; data yang sudah tersimpan tetap tersedia.':e.message});}
}
